\documentclass{article}
\usepackage{color}
\usepackage[hidelinks]{hyperref}
\usepackage{float}
\usepackage[left=1.00in, right=1.00in, top=1.00in, bottom=1.00in]{geometry}
\usepackage[]{authblk}
\pretolerance=99999 
\author{Prepared by:\\Ben Williams\\
   \href{mailto:ben.williams@alaska.gov}{ben.williams@alaska.gov}}
\affil{Alaska Department of Fish \& Game\\
   1255 W 8th Street\\
   Juneau, AK 99811-5526}
\title{Scallop Observer Data Summary\\

\begin{document}
   \maketitle
   \tableofcontents
\listoftables
\listoffigures

\section{Background}
This report summarizes weathervane scallop \textit{Patinopecten caurinus} fishery data for data collected by the onboard observer program during the 2014/15 season. 
The information is provided by the scallop observer program to aid ADF\&G Southeast Region staff in setting guideline harvest levels (GHLs) for the 2015/16 scallop season scheduled to begin July 1. 
Although scallop vessel operators sign waivers that allow ADF\&G to publish data collected by the onboard observer program, material included in this report such as individual vessel fishing locations, catches, and catch rates are \textit{\color{red}{Confidential}} and should not be released to the public.

Amendment 3 to the Fishery Management Plan for the Scallop Fishery off Alaska (FMP) delegated authority to manage all aspects of the federal waters scallop fishery except limited access to the State of Alaska. 
ADF\&G sets GHLs prior to each season, opens and closes scallop fishing areas and districts, oversees the onboard observer program, monitors scallop fishery catch and bycatch inseason, summarizes scallop management activities in department publications, and participates in the federal management process through the North Pacific Fishery Management Council (NPFMC) and Scallop Plan Team (SPT).

Amendment of the weathervane scallop FMP to incorporate Annual Catch Limits (ACLs) required by the 2006 reauthorization of the Magnuson-Stevens Act redefined the statewide overfishing level (OFL) from 1.24 million lb to 1.29 million lb of shucked scallop meats. 
The change was made to account for all sources of fishing mortality including harvest, discarded scallop catch in the directed fishery, bycatch in other fisheries, and survey catches. 
The annual ACL will equal 90\% of OFL, or 1.161 million lb of shucked meats, subject to annual approval by the NPFMC. 
For the ACL amendment analysis leading to the new OFL definition, mortality of scallops discarded in the fishery was assumed to be 20\%, and meat recovery was set at 10\% of scallop round weight.

The state's vessel-based limited entry program for the state-waters scallop fishery sunsetted on December 31, 2013.
Subsequently, the Alaska Board of Fisheries (BOF) passed a new state waters scallop fishery management plan (FMP).
Details on the  BOF action are available at

\url{http://www.adfg.alaska.gov/index.cfm?adfg=fisheriesboard.meetinginfo&date=01-07-2014&meeting=kodiak}.

At present, it appears that no new participants will be entering the 2015/16 state waters scallop fishery. 
We do know that all four vessels with federal-waters licenses will legally be able to fish scallops in state waters beginning July 1, 2015; previously, only one Alaska Scallop Association vessel held a state-waters permit.

Estimates of scallop abundance from fishery-independent surveys are not available. 
ADF\&G managers rely on data collected by the onboard scallop observer program including logbook data on fishing locations, catch, effort, catch-per-unit-effort (cpue), and bycatch. 
Inseason cpue and bycatch data from onboard observers may also be used in making scallop management decisions such as time/area closures. 
Summaries of inseason data (when fishing is open) as well as edited observer data summaries from the 2009/10-2014/15 seasons are available inside the ADF\&G firewall at

\url{http://kodweb.fishgame.state.ak.us/index/Data_Access:Scallop_Observer}.

\section{Problems with cpue data}

The use of cpue as an index of abundance is based upon a fundamental relationship in fisheries analysis

\begin{equation}
C_t/E_t=qN_t,
\end{equation}

where $C_t$ is catch at time $t$, $E_t$ is the effort expended at time $t$, $N_t$ is abundance at time $t$, and $q$ is the portion of the stock captured by one unit of effort (catchability coefficient). Provided $q$ is constant over time, cpue is proportional to abundance. It is rare that $q$ is constant over the entire exploitation history. 

Fishery statistics presented in this report are affected by many factors. 
In particular, these data are influenced by the spatial structure of the Alaska scallop population and non-random allocation of fishing effort.
Scallop cpue is affected by each vessel's choice of fishing locations as well as weather, currents, sea state, captain and crew performance, gear tuning, processing capacity, markets etc. 
Scallop shell height (SH) distributions from observer sampling are likewise affected by fishing locations and discarding as well as by the 4" diameter rings required by Alaska regulations that retain small scallops with lower efficiency than large scallops. 

Standardizing cpue (controlling for variables that affect catch aside from population abundance) is difficult, though standardized data are presented in some sections of this document. \textit{This standardization is a cursory effort and needs to be fully evaluated}.

Standardization was done with generalized additive models (GAMs) of form:
\begin{equation}
log(cpue)=f_1(depth)+f_2(lon,lat)+f_3(bed)+year_i+vessel_j+\epsilon_{ij},
\end{equation}

where $f_i$ are smoothing functions, year and vessel are categorical variables and bed is incorporated as a random effect.
 

\section{Data sources and updates}
   \subsection{Data}
The scallop catch by haul data used in this document originate from the Kodiak Wiki in the ``Finalized Observer Data Reports" \url{http://kodweb.fishgame.state.ak.us/apps/scalobs/catchbyhaul/index}. All available data from this location (e.g., shell height, bycatch, crab sizes, scallop observer data) have been included. Age data were provided by Ryan Burt (ryan.burt@alaska.gov). 

Keep in mind when comparing the cpue over different years the changes in spatial sampling (Figure~\ref{fig:akmap}).

 \subsection{Analysis updates/changes}
Catch per unit of effort is calculated as retained shelled meat weight/area swept (cpue). 
This is different from how it is reported in previous summaries, where cpue is calculated as the shelled meat weight/hours dredged. This has been changed to reflect that there are different trawl configurations (e.g., size, number, etc.) and the speed that a trawl is fished, therefore an evaluation by time is not the best descriptor of effort and area-based estimates of cpue should be more precise. \emph{Unfortunately while exploring these data it is obvious that a number of values are ``generalized", that is they are rounded, something that may add up to a substantial bias. It would be good to work with the fleet and observer program to try and generate more accurate values (i.e., actual dredge times, not 20 min, 30 min, etc.)}. I've adjusted the cpue estimates with a multiplier of 10\% of the mean cpue  following methods in Campbell (2004) and log transformed (Figure~\ref{fig:cpue}). The transformed cpue distribution meets the assumption of normality, non-transformed data do not.

<<load,echo=FALSE,message=FALSE,warning=FALSE>>=
#load inputs
library(lubridate)
library(extrafont);library(ggplot2)
#font_import() only do this one time - it takes a while
loadfonts(device="win")
windowsFonts(Times=windowsFont("TT Times New Roman"))
theme_set(theme_bw(base_size=12,base_family='Times New Roman')+theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank()))
library(mgcv)
library(maps)
library(mapdata)
library(mapproj)
library(gridExtra)
library(gtools)
library(RColorBrewer)
library(plyr)

#import data To update with a new year simply add a new file and bind it with the others
scallops09 <- read.csv("C:/Users/bcwilliams/Documents/Fisheries/scallops/Data/2009-scallopCatchByHaul.csv")
scallops10 <- read.csv("C:/Users/bcwilliams/Documents/Fisheries/scallops/Data/2010-scallopCatchByHaul.csv")
scallops11 <- read.csv("C:/Users/bcwilliams/Documents/Fisheries/scallops/Data/2011-scallopCatchByHaul.csv")
scallops12 <- read.csv("C:/Users/bcwilliams/Documents/Fisheries/scallops/Data/2012-scallopCatchByHaul.csv")
scallops13 <- read.csv("C:/Users/bcwilliams/Documents/Fisheries/scallops/Data/2013-scallopCatchByHaul.csv")
scallops14 <- read.csv("C:/Users/bcwilliams/Documents/Fisheries/scallops/Data/2014-scallopCatchByHaul.csv")
scallops <- rbind(scallops09,scallops10, scallops11, scallops12,scallops13, scallops14)

sh09 <- read.csv("C:/Users/bcwilliams/Documents/Fisheries/scallops/Data/2009-scallopShellHeights.csv")
sh10 <-  read.csv("C:/Users/bcwilliams/Documents/Fisheries/scallops/Data/2010-scallopShellHeights.csv")
sh11 <- read.csv("C:/Users/bcwilliams/Documents/Fisheries/scallops/Data/2011-scallopShellHeights.csv")
sh12 <- read.csv("C:/Users/bcwilliams/Documents/Fisheries/scallops/Data/2012-scallopShellHeights.csv")
sh13 <- read.csv("C:/Users/bcwilliams/Documents/Fisheries/scallops/Data/2013-scallopShellHeights.csv")
sh14 <- read.csv("C:/Users/bcwilliams/Documents/Fisheries/scallops/Data/2014-scallopShellHeights.csv")
sh <- rbind(sh09,sh10,sh11,sh12,sh13,sh14)

cr09 <- read.csv("C:/Users/bcwilliams/Documents/Fisheries/scallops/Data/2009-crabSizes.csv")
cr10 <-  read.csv("C:/Users/bcwilliams/Documents/Fisheries/scallops/Data/2010-crabSizes.csv")
cr11 <- read.csv("C:/Users/bcwilliams/Documents/Fisheries/scallops/Data/2011-crabSizes.csv")
cr12 <- read.csv("C:/Users/bcwilliams/Documents/Fisheries/scallops/Data/2012-crabSizes.csv")
cr13 <- read.csv("C:/Users/bcwilliams/Documents/Fisheries/scallops/Data/2013-crabSizes.csv")
cr14 <- read.csv("C:/Users/bcwilliams/Documents/Fisheries/scallops/Data/2014-crabSizes.csv")
crab <- rbind(cr09,cr10,cr11,cr12,cr13,cr14)

by09 <- read.csv("C:/Users/bcwilliams/Documents/Fisheries/scallops/Data/2009-scallopBycatchByDay.csv")
by10 <-  read.csv("C:/Users/bcwilliams/Documents/Fisheries/scallops/Data/2010-scallopBycatchByDay.csv")
by11 <- read.csv("C:/Users/bcwilliams/Documents/Fisheries/scallops/Data/2011-scallopBycatchByDay.csv")
by12 <- read.csv("C:/Users/bcwilliams/Documents/Fisheries/scallops/Data/2012-scallopBycatchByDay.csv")
by13 <- read.csv("C:/Users/bcwilliams/Documents/Fisheries/scallops/Data/2013-scallopBycatchByDay.csv")
by14 <- read.csv("C:/Users/bcwilliams/Documents/Fisheries/scallops/Data/2014-scallopBycatchByDay.csv")
by <- rbind(by09,by10,by11,by12,by13,by14)

ages <- read.csv("C:/Users/bcwilliams/Documents/Fisheries/scallops/Data/scallop_ages_bcw.csv")
ages <- ages[,2:47]
ages14 <- read.csv("C:/Users/bcwilliams/Documents/Fisheries/scallops/Data/2014ScallopShellAgeData.csv")


#adjust names to match other files
names(ages14) <- c('id', 'trip_id', 'haul_id', 'aged_by','fishery', 'fishery_season','district','vessel','trip_or_packet','date','small_or_retained','haul','shell','annuli','letter_code','number_code','shell_height' ,'a1','a2','a3','a4','a5','a6','a7','a8','a9','a10' ,'a11', 'a12','a13','a14','a15','a16','a17','a18','a19','a20','a21','a22','a23','a24','a25','a26','a27')

ages<- smartbind(ages,ages14)

names(ages) <- c('id', 'Trip_ID', 'Haul_ID', 'aged_by','date_aged','Fishery', 'season','District','ADFG','packetnum','stat_area','Set_Date','Rtnd_Disc','haul','shell_num','annuli','code_let','code_num','Shell_Height','a1','a2','a3','a4','a5','a6','a7','a8','a9','a10' ,'a11', 'a12','a13','a14','a15','a16','a17','a18','a19','a20','a21','a22','a23','a24','a25','a26','a27')
#adjust dates
scallops$set_date <- as.Date(scallops$Set_Date, "%m-%d-%Y")
scallops$year <- as.numeric(format(scallops$set_date, "%Y"))
scallops$date <- yday(scallops$set_date)
scallops$year <- ifelse(scallops$date<100, scallops$year-1, scallops$year)
scallops$Year <- factor(scallops$year)
scallops$vessel <- factor(scallops$ADFG)

ages$set_date <- as.Date(ages$Set_Date, "%m/%d/%Y")
ages$year <- as.numeric(format(ages$set_date, "%Y"))
ages$date <- yday(ages$set_date)
ages$year <- ifelse(ages$date<100, ages$year-1, ages$year)
ages$Year <- factor(ages$year)

by$set_date <- as.Date(by$Set_Date, "%m-%d-%Y")
by$year <- as.numeric(format(by$set_date, "%Y"))
by$date <- yday(by$set_date)
by$year <- ifelse(by$date<100, by$year-1, by$year)
by$Year <- factor(by$year)
by$vessel <- factor(by$ADFG)

#plotting smotting
#year 2009-2014 colors and breaks
values <- c('2014'='#542788bb','2013'='#998ec340','2012'='#d8daeb40',
         '2011'='#fee0b640','2010'='#f1a34040','2009'='#b3580640') 
breaks <- c('2014', '2013','2012','2011','2010','2009')
@

<<akmap, fig.pos="H", fig.cap="Map of all scallop dredge hauls. Top pane shows fishing locations from the 2009/10-2014/15 fishing season. Bottom pane shows fishing locations from the 2014/15 fishing season.",echo=FALSE, warning=FALSE ,fig.height=7, cache=TRUE,dev='png', dpi=300>>=
# Map
ak <- map_data('worldHires', c('USA:Alaska','Canada'))
akmap <- ggplot()+geom_polygon(data=ak,aes(long,lat,group=group),fill=8,color='black') +
   theme(panel.background=element_rect(fill='white')) + 
   xlab(expression(paste(Longitude^o,~'W'))) +
   ylab(expression(paste(Latitude^o,~'W'))) + 
   coord_map(xlim=c(min(scallops$Set_Lon,na.rm=T)-.2,max(scallops$Set_Lon,na.rm=T)+.2),
             ylim=c(min(scallops$Set_Lat,na.rm=T)-.2,max(scallops$Set_Lat,na.rm=T)+.2))

#akmap1
ak1 <- akmap + geom_point(data=scallops,aes(Set_Lon,Set_Lat,color=District),alpha=.35)+
   scale_colour_manual(values=c('D16'='#662506','YAK'='#cc4c02','EKI'='#fe9929',
                                'WKI'='#081d58','KNE'='#225ea8','KSH'='#41b6c4','KSW'
                                ='#54278f','KSEM'='#807dba','UB'='#045a8d', 'Q'="#3690c0"
                                ,'O'="#e31a1c", 'C'='#31a354'),  
                       breaks=c('D16', 'YAK','EKI','WKI','KNE','KSH','KSW','KSEM','UB',
                                'Q','O','C'), name='District')+
   guides(colour = guide_legend(override.aes = list(alpha = 1, size=3
   )))+ theme(legend.key = element_blank())+
   theme(plot.margin=unit(c(0,0,0,0),"mm"))

#akmap2
ak2 <- akmap + geom_point(data=subset(scallops, year==2014),aes(Set_Lon,Set_Lat,color=District),alpha=.35)+
   scale_colour_manual(values=c('D16'='#662506','YAK'='#cc4c02','EKI'='#fe9929',
                                'WKI'='#081d58','KNE'='#225ea8','KSH'='#41b6c4','KSW'
                                ='#54278f','KSEM'='#807dba','UB'='#045a8d', 'Q'="#3690c0"
                                ,'O'="#e31a1c"),  
                       breaks=c('D16', 'YAK','EKI','WKI','KNE','KSH','KSW','KSEM','UB',
                                'Q','O'), name='District')+
   guides(colour = guide_legend(override.aes = list(alpha = 1, size=3
   )))+ theme(legend.key = element_blank())+
   theme(plot.margin=unit(c(0,0,0,0),"mm"))
grid.arrange(ak1,ak2,ncol=1)
@


<<cpue, fig.pos="H", fig.cap="Log transformed cpue (weight/area swept) by round weight and shell weight.",echo=FALSE, warning=FALSE ,fig.height=4, cache=TRUE,dev='png', dpi=300, message=FALSE>>=

#remove data where dredge hours & area swept are zero
scallops <- subset(scallops,Area_Swept.nm2.>0)

#calculate round weight cpue by time and by area 
scallops$rw.cpue.t <- scallops$Round_Weight/scallops$Dredge_Hrs
scallops$rw.cpue.a <- scallops$Round_Weight/scallops$Area_Swept.nm2.

#calculate meat weight cpue by time and by area
scallops$mw.cpue.t <- scallops$Meat_Weight/scallops$Dredge_Hrs
scallops$mw.cpue.a <- scallops$Meat_Weight/scallops$Area_Swept.nm2.

#Subset scallop data to eliminate zeros in the cpue
scallop <- subset(scallops,rw.cpue.t>0)

#look for normality in cpue data
#h1 <- ggplot(scallop,aes(rw.cpue.t))+geom_histogram()
#h2 <- ggplot(scallop,aes(rw.cpue.a))+geom_histogram()+xlab('Round weight CPUE')
#h3 <- ggplot(scallop,aes(mw.cpue.t))+geom_histogram()
#h4 <- ggplot(scallop,aes(mw.cpue.a))+geom_histogram()+xlab('Meat weight CPUE')
#grid.arrange(h2,h4,ncol=2)

#adjust area cpue for log transformed data (Cambell et al 1996; Cambell 2004)
rwt.adjust <- mean(scallop$rw.cpue.t)*.10
rwa.adjust <- mean(scallop$rw.cpue.a)*.10
mwt.adjust <- mean(scallop$mw.cpue.t)*.10
mwa.adjust <- mean(scallop$mw.cpue.a)*.10

#log transform cpue data
scallop$rwt.cpue <- log(scallop$rw.cpue.t+rwt.adjust)
scallop$rwa.cpue <- log(scallop$rw.cpue.a+rwa.adjust)
scallop$mwt.cpue <- log(scallop$mw.cpue.t+mwt.adjust)
scallop$mwa.cpue <- log(scallop$mw.cpue.t+mwa.adjust)

#Subset data
eki <- subset(scallop,District=='EKI')
wki <- subset(scallop,District=='WKI')
yak <- subset(scallop,District=='YAK' |District=='D16' )
d16 <- subset(scallop,District=='D16')
kne <- subset(scallop,District=='KNE' )
ksh <- subset(scallop,District=='KSH' )
ksw <- subset(scallop,District=='KSW' )
m <- subset(scallop,District=='UB' )
o <- subset(scallop,District=='O')
q <- subset(scallop,District=='Q')
c <- subset(scallop,District=='C' )

#look for normality in cpue data
h1 <- ggplot(scallop,aes(rwt.cpue))+geom_histogram(alpha=.5,color='black')+xlab('Round weight CPUE')
#h2 <- ggplot(scallop,aes(rwa.cpue))+geom_histogram(alpha=.5,color='black')+xlab('Round weight CPUE')
h3 <- ggplot(scallop,aes(mwt.cpue))+geom_histogram(alpha=.5,color='black')+xlab('Meat weight CPUE')
#h4 <- ggplot(scallop,aes(mwa.cpue))+geom_histogram(alpha=.5,color='black')+xlab('Round weight CPUE')
grid.arrange(h1,h3,ncol=2)
@

\section{Area D Scallop Observer Data Summary}
\subsection{Yakutat \& District 16}
   \subsubsection{Fishery performance}
   A total of 120,353 pounds of meat were retained from three vessels (ADF\&G \#40924, \#54966, \#58200) that participated in the 2014/2015 Yakutat District fishery (Table~\ref{table:yakt1}). Two vessels (ADF\&G \#40924, \#58200) participated in the District 16 fishery (note that all of Bed 6 is included in this assessment) and caught a total of 9,140 pounds of scallop meat (Table~\ref{table:d16t1}).

It is evident that there is substantial spatial fishing variability within a given bed by year (Figures~\ref{fig:yak} and \ref{fig:yak2}). The non-standardized cpue shows a general trend in 2014/15 of higher cpue to the West (bed B) and lower cpue to the East (bed D16). In particular bed 3 saw very little directed effort during the 2014/15 season.


\begin{table}
\centering
\caption{Yakutat district catch summary for the 2014/15 season.}

\label{table:yakt1}
   \begin{tabular}{lcccccc}
         	&  \multicolumn{2}{c}{Retained catch} & Dredge  & Number  &   \\ 
		Year	&(lb meat)  & (lb round) & hours & hauls  & cpue$^a$    \\ 
\hline	1995	& 242,491& 3,214,968 &  4,712&  2,597&  51   \\ 
		1996	& 238,736& 3,195,254 &  3,982&  2,102&  60    \\ 
		1997/98	& 242,940& 	3,282,860& 	3,956& 	1,958& 	61\\
		1998/99	& 241,678& 	3,475,996& 	4,192& 	2,193& 	58\\
		1999/00	& 249,681& 	3,119,103& 	3,840& 	1,720& 	65\\
		2000/01	& 195,699& 	2,734,559& 	4,241& 	2,111& 	46\\
		2001/02	& 103,800& 	1,521,537& 	2,406& 	1,096& 	43\\
		2002/03	& 122,718& 	1,541,867& 	2,439& 	1,243& 	50\\
		2003/04	& 160,918& 	1,939,004& 	3,358& 	1,716& 	48\\
		2004/05	& 86,950& 	1,262,499& 	2,134& 	1,194& 	41\\
		2005/06	& 199,351& 	2,662,031& 	5,089& 	2,585& 	39\\
		2006/07	& 150,950& 	1,771,229& 	2,817& 	1,533& 	54\\
		2007/08	& 125,960& 	1,593,223& 	2,601& 	1,416& 	48\\
		2008/09	& 150,289& 	2,053,912& 	3,286& 	1,825& 	46\\
		2009/10	& 158,901& 	2,218,840& 	3,975& 	2,580& 	40\\
		2010/11	& 156,612& 	2,087,228& 	3,495& 	2,020& 	45\\
		2011/12	& 157,025& 	2,386,748& 	4,622& 	2,703& 	34\\
		2012/13	& 120,577& 	1,708,044& 	3,402& 	1,988& 	35\\
		2013/14	& 122,290& 	1,540,114&	2,391& 	1,348& 	51\\
		2014/15	& 120,353& 	1,446,693& 	2,727& 	1,597& 	44\\
	\hline	
	\multicolumn{3}{l}{$^a$lb scallop meat/dredge hour}	
	\end{tabular} 
\end{table}
   
\begin{table}
\centering
\caption{District 16 catch summary for the 2014/15 season.}

\label{table:d16t1}
   \begin{tabular}{lcccccc}
   			&  \multicolumn{2}{c}{Retained catch} & Dredge  & Number  &   \\ 
		Year	&(lb meat)  & (lb round) & hours & hauls  & cpue$^a$    \\ 
\hline   1995&   33,302	 &  447,469&	1,095&	599&	30\\
         1996&	34,060	  & 422,064&	917&	554&	37\\
         1997/98&	22,890&	265,882&	561&	105&	41\\
         1998/99&	34,153&	384,286&	702&	449&	49\\
         1999/00&	34,624&	292,625&	674&	299&	51\\
         2000/01&	30,904&	310,370&	476&	359&	65\\
         2001/02&	20,398&	245,319&	417&	291&	49\\
         2002/03&	3,685	 &  60,928&	100&	244&	37\\
         2003/04&	1,072	 &  16,780&	18	 &  193&	60\\
         2004/05&	24,430&	326,228&	419&	55	 &  58\\
         2005/06&	13,650&	209,487&	407&	12	  & 34\\
         2006/07&	13,445&	184,106&	309&	111&	44\\
         2007/08&	180	 &  8,888	 &  14	 &  197&	13\\
         2008/09&	20,986&	207,251&	423&	160&	50\\
         2009/10&	13,591&	210,006&	498	&299&	27\\
         2010/11&	2,655&	   31,266&	83	  & 54	 &  32\\
         2011/12&	1,826	 &  21,978&	59	 &  51	 &  31\\
         2012/13&	26,713&	335,178&	734&	448&	36\\
         2013/14&	25,110&	313,000&	634&	368&	40\\
         2014/15&	9,140&	   108,803&	413&	223&	22\\

	\hline	
	\multicolumn{3}{l}{$^a$lb scallop meat/dredge hour}	
	\end{tabular} 
\end{table}

<<yak, fig.pos="H", fig.cap="Maps of Area D fishing locations by fishing year.",echo=FALSE, warning=FALSE ,fig.height=8.5, cache=TRUE,dev='png', dpi=300>>=
#######################
#Yak
#######################

#split by bed
yak$bed = NA
yak<-within(yak,bed[Set_Lon > -138.3]<-6)#actually bed D16
yak<-within(yak,bed[Set_Lon < -138.3]<-5)
yak<-within(yak,bed[Set_Lon < -138.79]<-4)
yak<-within(yak,bed[Set_Lon < -140.1]<-3)
yak<-within(yak,bed[Set_Lon < -142.15]<-2)
yak<-within(yak,bed[Set_Lon < -142.7]<-1)
yak<-within(yak,bed[Set_Lon < -143.5]<-0)#actually bed B

#remove incomplete data
yak <- yak[complete.cases(yak),]
yak$Bed <- factor(yak$bed)
#change bed names
replace <- c("0"="B", "6"='D16')
yak$Bed <- revalue(yak$Bed, replace)

#reorder levels for plotting
#neworder <- c("B","1","2", "3", "4", "5",'D16')
#yak2 <- arrange(transform(yak,Bed=factor(Bed,levels=neworder)),Bed)

#map of sample locations

yakmap <- ggplot()+geom_polygon(data=ak,aes(long,lat,group=group),fill=8,color='black') +
   theme(panel.background=element_rect(fill='white')) + 
   xlab(expression(paste(Longitude^o,~'W'))) +
   ylab(expression(paste(Latitude^o,~'W'))) + 
   coord_map(xlim=c(min(yak$Set_Lon,na.rm=T)-.2,max(yak$Set_Lon,na.rm=T)+.2),
             ylim=c(min(yak$Set_Lat,na.rm=T)-.2,max(yak$Set_Lat,na.rm=T)+.2))

#yakmap1
yakmap+geom_point(data=subset(yak, year<2012),aes(Set_Lon,Set_Lat,color=Bed,width=1.2),alpha=.2) +
   guides(colour = guide_legend(override.aes = list(alpha = 1)))+facet_grid(Year~.)
@

<<yak2, fig.pos="H", fig.cap="Maps of Area D fishing locations by year.",echo=FALSE, warning=FALSE ,fig.height=8.5, cache=TRUE, dev='png', dpi=300>>=
#yakmap2
yakmap+geom_point(data=subset(yak, year>2011),aes(Set_Lon,Set_Lat,color=Bed,width=1.2),alpha=.2) +
   guides(colour = guide_legend(override.aes = list(alpha = 1)))+facet_grid(Year~.)
@

\subsection{Author's assessemnt}
I've presented raw and standardized cpue below in a format that differs from previous observer data summaries. In Figure~\ref{fig:yakcpue} the left panes show the density of cpue data. This is the distribution of cpue by haul irrespective of the number of hauls. The right pane is a histogram showing the number of hauls for a bed in a given year, note that the histogram shows stacked bars. The same plots are shown in Figure~\ref{fig:yakfit} for the standardized data. Figure~\ref{fig:yakfit2} shows annual cpue with 95\% confidence limits. This is followed by plots of shell height and shell ages.
\\

\noindent \textbf{Bed B}\\
Bed B had a higher mean cpue than in past years, and the amount of effort in the area was higher than in most years. The standardized cpue shows a stronger uptick in 2014 than previous years as well as a binomial distribution in cpue. The last time this bed was fished as heavily was in 2009, after which cpue declined the number of tows was lower. The distribution of shell heights was similar to that observed in 2013, however there was a poor showing in 2014 of smaller shell heights, possibly an indication of poor recruitment. Some of the discarded shells were fairly large, an indication that quality may not be great. Last it appears that the 2014 catch was predominantly of age-14 shells, these first appeared in the fishery in 2009.
\\

\noindent \textbf{Bed 1}\\
Bed 1 had a lower cpue in 2014 than in 2013, though peformed better than the previous years. However, the number of hauls in bed 1 was less than in 2013. The shell heights in bed 1 have a strong bimodal distribution, possibly indicating another cohorrt recruiting to the fishery (this assumes that shell measurements are proportional to the distribution of shells in the population). There is also a rather flat age structure.
\\

\noindent \textbf{Bed 2}\\  
Bed 2 had a generally high cpue and a relatively high number of hauls compared to years past. Standardized cpue shows a decline in 2014 from 2013, although shell heights indicate that there may be a size group ready to recruit into the fishery. 
\\

\noindent \textbf{Bed 3}\\  
Cpue in bed 3 was widely distributed, possibly due to test hauls in different areas to ascertain the viability of the bed in 2014? Very few hauls were made in bed 3. The shell heights sampled were similar to thos of previous years, thoug teh age structure was rather flat. This is likely due to the low number of samples available, more than a reflexion of what is going on in the population.
\\

\noindent \textbf{Bed 4}\\  
Bed 4 saw quite limited harvest relative to past years with a cpue in line with that observed in 2013. However standardized cpue shows a decline from 2013 and an overall cpue slightly lower than that observed in 2010. The shell heights sampled were comparable to previous years, though discards were sometimes large, ppotentially indicating poor quality of product. The age distribution is also lower than it was for years with greater numbers of hauls.

\noindent \textbf{Bed 5}\\  
Bed 5 generally has one of the higher cpues, however the number of hauls is low compared to some prior years. Similar to  bed 4 the shell heights were similar to past years, though the discard rate by shell size was high and the age structure is indicates a dominant age cohort(s).
\\

\noindent \textbf{Bed D16}\\  
CPUE in bed D16 was lower in 2014 than in 2013, though the number of hauls were similar. This typically has the lowest cpue of any of the beds. Shell height is more broadly dispersed than in previous years, and teh ages are coparable to previous years, aside from 2009, when older ages were prevelent.

<<yakcpue, fig.pos="H", fig.cap="Density and number of tows by bed and year for Area D cpue. The left pane shows the cpue distribution for all of the hauls, the right pane shows the number of hauls.",echo=FALSE, warning=FALSE ,fig.height=8.5, cache=TRUE, dev='png', dpi=300>>=

#density and number of tows
m1 <- ggplot(yak, aes(mwt.cpue,fill=Year,color=Year))+geom_density()+
   facet_grid(Bed~., scales='free_y')+xlab('log(cpue)')+
   scale_fill_manual(values=values, breaks=breaks, name='Year')+
   scale_color_manual(values=values, breaks=breaks, name='Year')+
   guides(colour = guide_legend(override.aes = list(alpha = 1)))+ 
   theme(legend.key = element_blank(),legend.position = c(0.15, 0.22),legend.background = 
            element_rect(fill = "#ffffffaa", colour = NA),legend.key.height=unit(.6,'line'))

m2 <- ggplot(yak, aes(mwt.cpue,fill=Year,color=Year))+geom_histogram()+
   facet_grid(Bed~.)+xlab('log(cpue)')+
   scale_fill_manual(values=values, breaks=breaks, name='Year')+
   scale_color_manual(values=values, breaks=breaks, name='Year')+
   guides( fill=FALSE, color=FALSE)+ theme(legend.key = element_blank())

grid.arrange(m1,m2,ncol=2)
@

<<yakfit, fig.pos="H", fig.cap="Density and number of tows by bed and year for Area D standardized cpue. The left pane shows the cpue distribution for all of the hauls, the right pane shows the number of hauls.",echo=FALSE, warning=FALSE ,fig.height=8.5, cache=TRUE,dev='png', dpi=300>>=
#Model the CPUE

fit <- gam(mwt.cpue~s(Depth,k=4)+te(Set_Lon,Set_Lat)+Year+s(Bed, bs='re')+vessel-1, data=yak, gamma=1.4)
#ggplot(yak, aes(year, fit, color=Bed, fill=Bed))+stat_summary(fun.data=mean_cl_boot, geom='smooth')
#plot(yak$Bed,resid(fit))
yak$fit <- fitted(fit)

#plot Yak model fits
f1 <- ggplot(yak, aes(fit,fill=Year,color=Year))+geom_density()+facet_grid(Bed~., scales='free_y')+
   scale_fill_manual(values=values,  
                     breaks=breaks, name='Year')+
   scale_color_manual(values=values,  
                      breaks=breaks, name='Year')+
   guides(colour = guide_legend(override.aes = list(alpha = 1)))+ 
   theme(legend.key = element_blank(),legend.position = c(0.15, 0.22),legend.background = 
            element_rect(fill = "#ffffffaa", colour = NA),legend.key.height=unit(.6,'line'))

f2 <- ggplot(yak, aes(fit,fill=Year,color=Year))+geom_histogram()+facet_grid(Bed~.)+
   scale_fill_manual(values=values,  
                     breaks=breaks, name='Year')+
   scale_color_manual(values=values,  
                      breaks=breaks, name='Year')+
   guides( fill=FALSE, color=FALSE)+ theme(legend.key = element_blank())
grid.arrange(f1,f2,ncol=2)
@

<<yakvessel, fig.pos="H", fig.cap="Annual vessel effect from model fit, Area D.",echo=FALSE, warning=FALSE ,fig.height=4, cache=TRUE,dev='png',dpi=300>>=
#Model the CPUE

#ggplot(yak, aes(Year,fit, fill=interaction(vessel,Bed)))+geom_boxplot()
#ggplot(yak, aes(vessel,fit, fill=Bed))+geom_boxplot()
ggplot(yak, aes(Year,fit, fill=vessel))+geom_boxplot(width=.35)
@

<<yakfit2, fig.pos="H", fig.cap="Standardized and raw cpue by year and bed for District D. Standardized cpue have bootstrap estimates 95\\% confidence levels, the raw cpue have normal approximate 95\\% confidence levels.",echo=FALSE, warning=FALSE ,fig.height=4, cache=TRUE, dev='png', dpi=300>>=
r1 <- ggplot(yak, aes(year, fit, color=Bed, fill=Bed))+stat_summary(fun.data=mean_cl_boot, geom='smooth')+
   scale_fill_manual(values = c('B'='#66250610','1'='#cc4c0210','2'='#fe992910',
         '3'='#e31a1c10','4'='#225ea810','5'='#41b6c410', 'D16'='#54278f10'),
         breaks= c('B', '1','2','3','4','5', 'D16'), name='bed')+
   scale_color_manual(values = c('B'='#662506','1'='#cc4c02','2'='#fe9929',
         '3'='#e31a1c','4'='#225ea8','5'='#41b6c4', 'D16'='#54278f'),
         breaks= c('B', '1','2','3','4','5', 'D16'), name='bed')+
   theme(legend.key = element_blank(),legend.position = c(0.75, 0.2),legend.background = 
            element_rect(fill = "#ffffffaa", colour = NA),legend.key.height=unit(.6,'line'))+ylab('standardized cpue')

a <- aggregate(mwt.cpue~year+Bed,data=yak, FUN=mean)
b <- aggregate(mwt.cpue~year+Bed,data=yak, FUN=sd)
names(b) <- c('year','Bed', 'sd')
c <- aggregate(mwt.cpue~year+Bed,data=yak, FUN=length)
names(c) <- c('year','Bed', 'n')
d <- merge(a,b, by=c('year','Bed'))
d <- merge(c,d, by=c('year','Bed'))
d$lci <- d$mwt.cpue-2*d$sd/sqrt(d$n)
d$uci <- d$mwt.cpue+2*d$sd/sqrt(d$n)
r2 <- ggplot(d, aes(year,mwt.cpue, fill=Bed))+geom_line(aes(color=Bed))+
   geom_ribbon(aes(ymin=lci, ymax=uci))+
   scale_fill_manual(values = c('B'='#66250610','1'='#cc4c0210','2'='#fe992910',
         '3'='#e31a1c10','4'='#225ea810','5'='#41b6c410', 'D16'='#54278f10'),
         breaks= c('B', '1','2','3','4','5', 'D16'), name='bed')+
   scale_color_manual(values = c('B'='#662506','1'='#cc4c02','2'='#fe9929',
         '3'='#e31a1c','4'='#225ea8','5'='#41b6c4', 'D16'='#54278f'),
         breaks= c('B', '1','2','3','4','5', 'D16'), name='bed')+
      guides( fill=FALSE, color=FALSE)+ theme(legend.key = element_blank())+ylab('cpue')
grid.arrange(r1,r2,ncol=2)

@

<<yaksh, fig.pos="H", fig.cap="Shell heights by bed and year for Area D. The left pane shows the density of shell heights, the right pane is a stacked bar histogram of sample sizes by shell height.",echo=FALSE, warning=FALSE ,fig.height=8.5, cache=TRUE,dev='png', dpi=300>>=
#Shell heights
yak.sh <- merge(yak,sh,by=c('Fishery', 'District','Haul_ID','ADFG'))

#SH by year
s1 <- ggplot(yak.sh, aes(Shell_Height, fill=Year,color=Year))+geom_density()+facet_grid(Bed~.)+
   scale_fill_manual(values=values,  
                     breaks=breaks, name='Year')+
   scale_color_manual(values=values,  
                      breaks=breaks, name='Year')+
   guides(colour = guide_legend(override.aes = list(alpha = 1)))+ 
   theme(legend.key = element_blank(),legend.position = c(0.15, 0.075),legend.background = 
            element_rect(fill = "#ffffffaa", colour = NA),legend.key.height=unit(.6,'line'))

s2 <- ggplot(yak.sh, aes(Shell_Height, fill=Year,color=Year))+geom_histogram()+facet_grid(Bed~.)+
   scale_fill_manual(values=values,   breaks=breaks, name='Year')+
   scale_color_manual(values=values,  breaks=breaks, name='Year')+
   guides( fill=FALSE, color=FALSE)+ theme(legend.key = element_blank())
grid.arrange(s1,s2,ncol=2)
@

<<yaksh14, fig.pos="H", fig.cap="Retained and discarded shell heights by bed for Area D in 2014. The left pane shows the density of shell heights, the right pane is a stacked bar histogram of sample sizes by shell height.",echo=FALSE, warning=FALSE ,fig.height=8.5, cache=TRUE, dev='png', dpi=300>>=
#SH by bed
s1 <- ggplot(subset(yak.sh, year==2014), aes(Shell_Height, fill=Rtnd_Disc,color=Rtnd_Disc))+geom_density(alpha=.2)+facet_grid(Bed~.)+
   scale_color_manual( values=c('D'='#e41a1c','R'='#377eb8'), labels=c('discard', 'retain'),name='')+
   scale_fill_manual( values=c('D'='#e41a1c','R'='#377eb8'), labels=c('discard', 'retain'),name='')+ 
   theme(legend.key = element_blank(),legend.position = c(0.2, 0.2),legend.background = 
   element_rect(fill = "#ffffffaa", colour = NA),legend.key.height=unit(.6,'line'))
s2 <- ggplot(subset(yak.sh, year==2014), aes(Shell_Height, fill=Rtnd_Disc,color=Rtnd_Disc))+geom_histogram(alpha=.2)+facet_grid(Bed~.)+
   scale_color_manual( values=c('D'='#e41a1c','R'='#377eb8'), labels=c('discard', 'retain'),name='')+
   scale_fill_manual( values=c('D'='#e41a1c','R'='#377eb8'), labels=c('discard', 'retain'),name='')+
   guides( fill=FALSE, color=FALSE)+ theme(legend.key = element_blank())
grid.arrange(s1,s2,ncol=2)

@

<<yaksh3, fig.pos="H", fig.cap="Retained and discarded shell heights by year for Area D in 2014. The left pane shows the density of shell heights, the right pane is a stacked bar histogram of sample sizes by shell height.",echo=FALSE, warning=FALSE ,fig.height=8.5, cache=TRUE,dev='png', dpi=300>>=

#SH by year
s1 <- ggplot(yak.sh, aes(Shell_Height, fill=Rtnd_Disc,color=Rtnd_Disc))+geom_density(alpha=.2)+facet_grid(Year~.)+
   scale_color_manual( values=c('D'='#e41a1c','R'='#377eb8'), labels=c('discard', 'retain'),name='')+
   scale_fill_manual( values=c('D'='#e41a1c','R'='#377eb8'), labels=c('discard', 'retain'),name='')+ 
   theme(legend.key = element_blank(),legend.position = c(0.2, 0.25),legend.background = 
   element_rect(fill = "#ffffffaa", colour = NA),legend.key.height=unit(.6,'line'))

s2 <- ggplot(yak.sh, aes(Shell_Height, fill=Rtnd_Disc,color=Rtnd_Disc))+geom_histogram(alpha=.2)+facet_grid(Year~.)+
   scale_color_manual( values=c('D'='#e41a1c','R'='#377eb8'), labels=c('discard', 'retain'),name='')+
   scale_fill_manual( values=c('D'='#e41a1c','R'='#377eb8'), labels=c('discard', 'retain'),name='')+
   guides( fill=FALSE, color=FALSE)+ theme(legend.key = element_blank())
grid.arrange(s1,s2,ncol=2)
@

<<yakage, fig.pos="H", fig.cap="Shell ages (annuli) by bed and year for Area D.",echo=FALSE, warning=FALSE ,fig.height=8, cache=TRUE,dev='png', dpi=300>>=
#Ages
yak.age <- merge(yak, ages,by=c('Fishery', 'District','Haul_ID','ADFG', 'set_date', 'year', 'date', 'Year'))
#age by year
a1 <- ggplot(yak.age, aes(annuli, fill=Year, color=Year))+geom_density()+facet_grid(Bed~.)+
   scale_fill_manual(values=values, breaks=breaks, name='Year')+
   scale_color_manual(values=values,  breaks=breaks, name='Year')+
   guides(colour = guide_legend(override.aes = list(alpha = 1)))+ 
   theme(legend.key = element_blank(),legend.position = c(0.75, 0.23),legend.background = 
            element_rect(fill = "#ffffffaa", colour = NA),legend.key.height=unit(.6,'line'))
a2 <- ggplot(yak.age, aes(annuli, fill=Year, color=Year))+geom_histogram()+facet_grid(Bed~.)+
   scale_fill_manual(values=values, breaks=breaks, name='Year')+
   scale_color_manual(values=values,  breaks=breaks, name='Year')+
   guides(colour = guide_legend(override.aes = list(alpha = 1)))+
   guides( fill=FALSE, color=FALSE)+ theme(legend.key = element_blank())
grid.arrange(a1,a2,ncol=2)
@

<<yakage3, fig.pos="H", fig.cap="Shell ages (annuli) by year for Area D, all beds combined. The left pane shows the density of shell heights, the right pane is a stacked bar histogram of sample sizes by shell height.",echo=FALSE, warning=FALSE ,fig.height=8.5, cache=TRUE,dev='png', dpi=300>>=

#SH by year
s1 <- ggplot(yak.age, aes(annuli))+geom_density(alpha=.2, fill='4')+facet_grid(Year~.)+
   theme(legend.key = element_blank(),legend.position = c(0.2, 0.25),legend.background = 
   element_rect(fill = "#ffffffaa", colour = NA),legend.key.height=unit(.6,'line'))

s2 <- ggplot(yak.age, aes(annuli))+geom_histogram(alpha=.2, color='black', fill=4)+facet_grid(Year~.)+
      guides( fill=FALSE, color=FALSE)+ theme(legend.key = element_blank())
grid.arrange(s1,s2,ncol=2)
@

<<yakagesh, fig.pos="H", fig.cap="Comparison between shells measured for height and shell height of aged scallops by bed and year for Area D. The left pane shows the density of all shell heights collected (blue) and the density of shell heights from ages shells (gray). The right pane shows the densities of shell heights from retained shells, discarded shell, and aged shells.",echo=FALSE, warning=FALSE ,fig.height=8.5, cache=TRUE, dev='png', dpi=300>>=
#difference between shell height samples and shell height ages
as1 <- ggplot(yak.age, aes(Shell_Height))+geom_density(alpha=.2,fill='black')+facet_grid(Year~.)+
   geom_density(data=yak.sh, aes(Shell_Height), alpha=.2,fill=4)

as2 <- ggplot(yak.age, aes(Shell_Height))+geom_density(alpha=.2,fill='black')+facet_grid(Year~.)+
   geom_density(data=yak.sh, aes(Shell_Height, fill=Rtnd_Disc), alpha=.2)+guides(colour = guide_legend(override.aes = list(alpha = 1)))+ 
   theme(legend.key = element_blank(),legend.position = c(0.15, 0.23),legend.background = 
            element_rect(fill = "#ffffffaa", colour = NA),legend.key.height=unit(.6,'line'))+
   scale_fill_manual( values=c('D'='#e41a1c','R'='#377eb8'), labels=c('discard', 'retain'),name='')
grid.arrange(as1,as2,ncol=2)

@

<<yakagex,echo=FALSE,message=FALSE,warning=FALSE,dev='png', dpi=300, fig.height=8>>=
#Extras
#yakmap+geom_point(data=subset(yak.age, year<2012),aes(Set_Lon,Set_Lat,color=annuli,width=1.2),alpha=.2) +
   #guides(colour = guide_legend(override.aes = list(alpha = 1)))+facet_grid(Year~.)+scale_colour_gradientn(colours=rainbow(5))
#yakmap+geom_point(data=subset(yak.age, year>2011),aes(Set_Lon,Set_Lat,color=annuli,width=1.2),alpha=.2) +
   #guides(colour = guide_legend(override.aes = list(alpha = 1)))+facet_grid(Year~.)+scale_colour_gradientn(colours=rainbow(5))

#ggplot(yak.age, aes(annuli))+geom_density(alpha=.2,fill=4)+facet_grid(Year~.)
#ggplot(yak.age, aes(annuli))+geom_histogram(alpha=.2,color='black', fill=4)+facet_grid(Year~.)   
#ggplot(yak.age, aes(annuli, Meat_Weight, fill=Bed))+geom_point(alpha=.2,color='black')+stat_smooth(method='gam',formula=y~s(x,k=3))+coord_cartesian(ylim=c(0,155),xlim=c(0,20))

#ggplot(yak.age, aes(annuli, Meat_Weight, group=Year,color=Year,fill=Year))+geom_point(alpha=.2,color='black')+stat_smooth()+coord_cartesian(ylim=c(0,155),xlim=c(0,20))


#ggplot(yak.age, aes(Depth,annuli, group=Year,color=Year,fill=Year))+geom_point(alpha=.2,color='black')+stat_smooth()
#ggplot(yak.sh, aes(Depth,Shell_Height, group=Year,color=Year,fill=Year))+geom_point(alpha=.2,color='black')+stat_smooth(method='lm')


#ggplot(yak.age, aes(Depth,annuli, group=Year,color=Year,fill=Year))+geom_point(alpha=.2,color='black')+stat_smooth(method='gam',formula=y~s(x,k=4))
#ggplot(yak.sh, aes(Meat_Weight,Shell_Height, group=Year,color=Year,fill=Year))+geom_point(alpha=.2,color='black')+stat_smooth(method='lm')
@

\section{Area K}
\subsection{Kodiak Northeast District}
\subsubsection{Fishery performance}
The 2014/15 Kodiak Northeast District scallop fishery opened on July 1. 2014 with a GHL of 55,000 lb scallop meat. Three vessels particpated in the fishery (Figure~\ref{fig:knevessel}) harvesting 55,659 lb scallop meat with a cpue of 74 lb meat/dredge hour (Table~\ref{table:knet1}). This high cpue is most similar to levels observed in 2000-2002. 

Harvest was limited to bed 2 (Figure~\ref{fig:kne})
\subsubsection{Size and age structure of catch}

Larger shell sizes were observed in 2014/15 than in the 2013/14 fishery (bed 2 only). Though there appears to be a limited age cohort present in the fishery and smaller shell sizes are poorly represented, possibly indicating limited recruitment to the fishery in the future. Note that harvest only occured in bed 2.
\subsubsection{Scallop discards and crab/halibut bycatch}

An estimated 16,322 Tanner Crab, a decrease from previous years, and 1,432 Pacific Halibut were incidentically caught (Figure~\ref{fig:knecrab}). An estimated 52,719 lb of scallops were discarded, 7.9\% of retained round weight.

   \begin{table}[H]
      \centering
		\caption{Kodiak Northeast District catch summary for the 2014/15 season.}
		
		\label{table:knet1}
		\begin{tabular}{lcccccc}
					& 		&  Catch 	& Dredge  & Number  &  		 \\ 
			Year	& GHL 	&(lb meat)  & (hours) & hauls  & cpue$^a$\\ 
			\hline	
			1993/94 &   &  			155,187 &	6,940 &	4,099&	22 \\
			1994/95 &   &			35,517  &	1,773 &	986&	20 \\
			1995/96 &   &			closed	&			 &			\\
			1996/97 &   &			11,430  &	581 &	319 &	20 \\
			1997/98 &   &			95,858  &	2,604 &	1,418 &	37 \\
			1998/99 &   &			120,010 &	2,747 &	1,331 &	44 \\
			1999/00 &	75,000 &	77,119 &	1,383 &	673 &	56 \\
			2000/01 &	80,000 &	79,965 &	1,101 &	556 &	73 \\
			2001/02 &	80,000 &	80,470 &	1,142 &	591 &	70 \\
			2002/03 &	80,000 &	79,987 &	1,350 &	725 &	59 \\
			2003/04 &	80,000 &	79,965 &	1,248 &	685 &	64 \\
			2004/05 &	80,000 &	79,472 &	1,227 &	662 &	65 \\
			2005/06 &	80,000 &	80,034 &	1,759 &	881 &	46 \\
			2006/07 &	90,000 &	74,902 &	1,168 &	688 &	64 \\
			2007/08 &	90,000 &	73,276 &	1,170 &	671 &	63 \\
			2008/09 &	90,000 &	75,030 &	1,356 &	793 &	56 \\
			2009/10 &	75,000 &	69,057 &	1,222 &	625 &	57 \\
			2010/11 &	65,000 &	64,465 &	1,015 &	618 &	64 \\
			2011/12 &	70,000 &	61,152 &	986 &	699 &	62 \\
			2012/13 &	60,000 &	62,496 &	1,322 &	938 &	47 \\
			2013/14 &	55,000 &	54,926 &	934 &	681 &	59 \\
			2014/15 &	55,000&	55,659 & 	748	& 	442	&	74	\\
			\hline	
			\multicolumn{3}{l}{$^a$lb scallop meat/dredge hour}	
		\end{tabular} 
	\end{table}

<<kne, fig.pos="H", fig.cap="Maps of District KNE fishing locations by fishing year.",echo=FALSE, warning=FALSE ,fig.height=8, cache=TRUE, dev='png', dpi=300>>=
#######################
#KNE
#######################

#split by bed
kne$bed = NA
kne<-within(kne,bed[Set_Lat > 57.8]<-1)
kne<-within(kne,bed[Set_Lat < 57.8& Set_Lat > 57.17 & Set_Lon>-151.9]<-2)
kne<-within(kne,bed[ Set_Lon< -151.9]<-3)
kne<-within(kne,bed[ Set_Lat<57.03 & Set_Lon> -152.2]<-4)
kne<-within(kne,bed[ Set_Lat<56.9 & Set_Lon> -152.3]<-5)
kne<-within(kne,bed[ Set_Lat<56.95 & Set_Lon< -152.5]<-6)
kne$Bed <- factor(kne$bed)

#remove incomplete data
kne <- kne[complete.cases(kne),]

#map of sample locations

knemap <- ggplot()+geom_polygon(data=ak,aes(long,lat,group=group, color=Bed),fill=8,color='black') +
   theme(panel.background=element_rect(fill='white')) + 
   xlab(expression(paste(Longitude^o,~'W'))) +
   ylab(expression(paste(Latitude^o,~'W'))) + 
   coord_map(xlim=c(min(kne$Set_Lon,na.rm=T)-.2,max(kne$Set_Lon,na.rm=T)+.2),
             ylim=c(min(kne$Set_Lat,na.rm=T)-.2,max(kne$Set_Lat,na.rm=T)+.2))

knemap+geom_point(data=kne, aes(Set_Lon,Set_Lat, color=Bed), alpha=.2)+facet_wrap(~ Year)+
   guides(colour = guide_legend(override.aes = list(alpha = 1)))+
   theme(legend.key = element_blank(),legend.position = c(0.79, 0.1),legend.background = 
            element_rect(fill = "#ffffffaa", colour = NA),legend.key.height=unit(.6,'line'))
@

<<knecpue, fig.pos="H", fig.cap="Density and number of tows by bed and year for District KNE cpue. The left pane shows the cpue distribution for all of the hauls, the right pane shows the number of hauls.",echo=FALSE, warning=FALSE ,fig.height=8.5, cache=TRUE, dev='png', dpi=300>>=
#RAW density and number of tows
m1 <- ggplot(kne, aes(mwt.cpue,fill=Year,color=Year))+geom_density()+facet_grid(Bed~., scales='free_y')+xlab('log(cpue)')+
   scale_fill_manual(values=values,breaks=breaks, name='Year')+
   scale_color_manual(values=values,breaks=breaks, name='Year')+
   guides(colour = guide_legend(override.aes = list(alpha = 1)))+ 
   theme(legend.key = element_blank(),legend.position = c(0.15, 0.075),legend.background = 
            element_rect(fill = "#ffffffaa", colour = NA),legend.key.height=unit(.6,'line'))

m2 <- ggplot(kne, aes(mwt.cpue,fill=Year,color=Year))+geom_histogram()+facet_grid(Bed~.)+xlab('log(cpue)')+
   scale_fill_manual(values=values,breaks=breaks, name='Year')+
   scale_color_manual(values=values,breaks=breaks, name='Year')+
   guides( fill=FALSE, color=FALSE)+ theme(legend.key = element_blank())
grid.arrange(m1,m2,ncol=2)
@

<<knefit, fig.pos="H", fig.cap="Density and number of tows by bed and year for District KNE standardized cpue. The left pane shows the cpue distribution for all of the hauls, the right pane shows the number of hauls.",echo=FALSE, warning=FALSE ,fig.height=8.5, cache=TRUE, dev='png', dpi=300>>=
#Model the CPUE
                                           
fit <- gam(mwt.cpue~s(Depth,k=4)+te(Set_Lon,Set_Lat)+Year+s(Bed, bs='re')+vessel-1, data=kne, gamma=1.4)
#ggplot(kne, aes(year, fit, color=Bed, fill=Bed))+stat_summary(fun.data=mean_cl_boot, geom='smooth')
#plot(kne$Bed,resid(fit))
kne$fit <- fitted(fit)
f1 <- ggplot(kne, aes(fit,fill=Year,color=Year))+geom_density()+facet_grid(Bed~., scales='free_y')+
   scale_fill_manual(values=values,breaks=breaks, name='Year')+
   scale_color_manual(values=values,breaks=breaks, name='Year')+
   guides(colour = guide_legend(override.aes = list(alpha = 1)))+ 
   theme(legend.key = element_blank(),legend.position = c(0.15, 0.075),legend.background = 
            element_rect(fill = "#ffffffaa", colour = NA),legend.key.height=unit(.6,'line'))

f2 <- ggplot(kne, aes(fit,fill=Year,color=Year))+geom_histogram()+facet_grid(Bed~.)+
   scale_fill_manual(values=values,breaks=breaks, name='Year')+
   scale_color_manual(values=values,breaks=breaks, name='Year')+
   guides( fill=FALSE, color=FALSE)+ theme(legend.key = element_blank())
grid.arrange(f1,f2,ncol=2)
@                                           

<<knevessel, fig.pos="H", fig.cap="Annual vessel effect from model fit, District KNE.",echo=FALSE, warning=FALSE ,fig.height=3.9, cache=TRUE,dev='png',dpi=300>>=
#Model the CPUE
#ggplot(kne, aes(Year,fit, fill=Bed))+geom_boxplot()
#ggplot(kne, aes(vessel,fit, fill=Bed))+geom_boxplot()
ggplot(kne, aes(Year,fit, fill=vessel))+geom_boxplot(width=.35)
@

<<knefit2, fig.pos="H", fig.cap="Standardized and raw and standardized CPUE by year and bed for District KNE.  Standardized cpue have bootstrap estimated 95\\% confidence levels, the raw cpue have normal approximate 95\\% confidence levels.",echo=FALSE, warning=FALSE ,fig.height=3.9, cache=TRUE,dev='png', dpi=300>>=
r1 <- ggplot(kne, aes(year, fit, color=Bed, fill=Bed))+stat_summary(fun.data=mean_cl_boot, geom='smooth')+
   scale_fill_manual(values = c('1'='#a6bddb40','2'='#998ec340','3'='#99d8c940',
         '4'='#fee0b640','5'='#f1a34030','6'='#3690c030', '7'='#a3580610'),
         breaks= c('1', '2','3','4','5','6', '7'), name='bed')+
   scale_color_manual(values = c('1'='#542788','2'='#998ec3','3'='#99d8c9',
         '4'='#fee0b6','5'='#f1a340','6'='#3690c0', '7'='#a35806'),
         breaks= c('1', '2','3','4','5','6', '7'), name='bed')+coord_cartesian(ylim=c(3,4.5))+ 
   theme(legend.key = element_blank(),legend.position = c(0.75, 0.16),legend.background = 
            element_rect(fill = "#ffffffaa", colour = NA),legend.key.height=unit(.6,'line'))+ylab('standardized cpue')

a <- aggregate(mwt.cpue~year+Bed,data=kne, FUN=mean)
b <- aggregate(mwt.cpue~year+Bed,data=kne, FUN=sd)
names(b) <- c('year','Bed', 'sd')
c <- aggregate(mwt.cpue~year+Bed,data=kne, FUN=length)
names(c) <- c('year','Bed', 'n')
d <- merge(a,b, by=c('year','Bed'))
d <- merge(c,d, by=c('year','Bed'))
d$lci <- d$mwt.cpue-2*d$sd/sqrt(d$n)
d$uci <- d$mwt.cpue+2*d$sd/sqrt(d$n)
r2 <- ggplot(d, aes(year,mwt.cpue, fill=Bed))+geom_line(aes(color=Bed))+
   geom_ribbon(aes(ymin=lci, ymax=uci))+
   scale_fill_manual(values = c('1'='#a6bddb40','2'='#998ec340','3'='#99d8c940',
         '4'='#fee0b640','5'='#f1a34030','6'='#3690c030', '7'='#a3580610'),
         breaks= c('1', '2','3','4','5','6', '7'), name='bed')+
   scale_color_manual(values = c('1'='#542788','2'='#998ec3','3'='#99d8c9',
         '4'='#fee0b6','5'='#f1a340','6'='#3690c0', '7'='#a35806'),
         breaks= c('1', '2','3','4','5','6', '7'), name='bed')+coord_cartesian(ylim=c(3,4.5))+
      guides( fill=FALSE, color=FALSE)+ theme(legend.key = element_blank())+ylab('raw cpue')
grid.arrange(r1,r2,ncol=2)
@

<<knefit3, fig.pos="H", fig.cap="Standardized and raw and standardized CPUE by year and bed for District KNE.  Standardized cpue have bootstrap estimated 95\\% confidence levels, the raw cpue have normal approximate 95\\% confidence levels.",echo=FALSE, warning=FALSE ,fig.height=3.9, cache=TRUE,dev='png', dpi=300, eval=FALSE>>=
r1 <- ggplot(kne, aes(year, fit))+stat_summary(fun.data=mean_cl_boot, geom='smooth')+
   theme(legend.key = element_blank(),legend.position = c(0.75, 0.16),legend.background = 
            element_rect(fill = "#ffffffaa", colour = NA),legend.key.height=unit(.6,'line'))+ylab('standardized cpue')

a <- aggregate(mwt.cpue~year,data=kne, FUN=mean)
b <- aggregate(mwt.cpue~year,data=kne, FUN=sd)
names(b) <- c('year', 'sd')
c <- aggregate(mwt.cpue~year,data=kne, FUN=length)
names(c) <- c('year', 'n')
d <- merge(a,b, by=c('year'))
d <- merge(c,d, by=c('year'))
d$lci <- d$mwt.cpue-2*d$sd/sqrt(d$n)
d$uci <- d$mwt.cpue+2*d$sd/sqrt(d$n)
r1+stat_summary(aes(year, mwt.cpue),fun.y=mean, geom='line')
   
   
   ggplot()+geom_line(data=d, aes(year,mwt.cpue), color='black')+
   geom_ribbon(data=d,aes(year,ymin=lci, ymax=uci), fill=1, alpha=.3)
grid.arrange(r1,r2,ncol=2)
@

<<knesh, fig.pos="H", fig.cap="Shell heights by bed and year for District KNE. The left pane shows the cpue distribution for all of the hauls, the right pane shows the number of hauls.",echo=FALSE, warning=FALSE ,fig.height=8.5, cache=TRUE, dev='png', dpi=300>>=                                           
#Shell heights
kne.sh <- merge(kne,sh,by=c('Fishery', 'District','Haul_ID','ADFG'))
                                           
#SH by year
s1 <- ggplot(kne.sh, aes(Shell_Height, fill=Year,color=Year))+geom_density()+facet_grid(Bed~.)+
   scale_fill_manual(values=values,breaks=breaks, name='Year')+
   scale_color_manual(values=values,breaks=breaks, name='Year')+
   guides(colour = guide_legend(override.aes = list(alpha = 1)))+ 
   theme(legend.key = element_blank(),legend.position = c(0.15, 0.075),legend.background = 
   element_rect(fill = "#ffffffaa", colour = NA),legend.key.height=unit(.6,'line'))
                                           
s2 <- ggplot(kne.sh, aes(Shell_Height, fill=Year,color=Year))+geom_histogram()+facet_grid(Bed~.)+
   scale_fill_manual(values=values,breaks=breaks, name='Year')+
   scale_color_manual(values=values,breaks=breaks, name='Year')+
   guides(colour = guide_legend(override.aes = list(alpha = 1)))+
   guides( fill=FALSE, color=FALSE)+ theme(legend.key = element_blank())
grid.arrange(s1,s2,ncol=2)
@

<<knesh14, fig.pos="H", fig.cap="Retained and discarded shell heights by bed for District KNE in 2014. The left pane shows the cpue distribution for all of the hauls, the right pane shows the number of hauls.",echo=FALSE, warning=FALSE ,fig.height=4, cache=TRUE, dev='png', dpi=300>>=
#SH by bed
s1 <- ggplot(subset(kne.sh, year==2014), aes(Shell_Height, fill=Rtnd_Disc,color=Rtnd_Disc))+geom_density(alpha=.2)+facet_grid(Bed~.)+
   scale_color_manual( values=c('D'='#e41a1c','R'='#377eb8'), labels=c('discard', 'retain'),name='')+
   scale_fill_manual( values=c('D'='#e41a1c','R'='#377eb8'), labels=c('discard', 'retain'),name='')+ 
   theme(legend.key = element_blank(),legend.position = c(0.2, 0.75),legend.background = 
   element_rect(fill = "#ffffffaa", colour = NA),legend.key.height=unit(.6,'line'))
s2 <- ggplot(subset(kne.sh, year==2014), aes(Shell_Height, fill=Rtnd_Disc,color=Rtnd_Disc))+geom_histogram(alpha=.2)+facet_grid(Bed~.)+
   scale_color_manual( values=c('D'='#e41a1c','R'='#377eb8'), labels=c('discard', 'retain'),name='')+
   scale_fill_manual( values=c('D'='#e41a1c','R'='#377eb8'), labels=c('discard', 'retain'),name='')+
   guides( fill=FALSE, color=FALSE)+ theme(legend.key = element_blank())
grid.arrange(s1,s2,ncol=2)
@

<<knesh3, fig.pos="H", fig.cap="Shell heights by year, all beds combined, for District KNE. The left pane shows the cpue distribution for all of the hauls, the right pane shows the number of hauls.",echo=FALSE, warning=FALSE ,fig.height=8.5, cache=TRUE,dev='png', dpi=300>>=

#SH by year
s1 <- ggplot(kne.sh, aes(Shell_Height, fill=Rtnd_Disc,color=Rtnd_Disc))+geom_density(alpha=.2)+facet_grid(Year~.)+
   scale_color_manual( values=c('D'='#e41a1c','R'='#377eb8'), labels=c('discard', 'retain'),name='')+
   scale_fill_manual( values=c('D'='#e41a1c','R'='#377eb8'), labels=c('discard', 'retain'),name='')+ 
   theme(legend.key = element_blank(),legend.position = c(0.2, 0.25),legend.background = 
   element_rect(fill = "#ffffffaa", colour = NA),legend.key.height=unit(.6,'line'))

s2 <- ggplot(kne.sh, aes(Shell_Height, fill=Rtnd_Disc,color=Rtnd_Disc))+geom_histogram(alpha=.2)+facet_grid(Year~.)+
   scale_color_manual( values=c('D'='#e41a1c','R'='#377eb8'), labels=c('discard', 'retain'),name='')+
   scale_fill_manual( values=c('D'='#e41a1c','R'='#377eb8'), labels=c('discard', 'retain'),name='')+
   guides( fill=FALSE, color=FALSE)+ theme(legend.key = element_blank())
grid.arrange(s1,s2,ncol=2)
@

<<kneage, fig.pos="H", fig.cap="Shell ages (annuli) by bed and year for District KNE. The left pane shows the cpue distribution for all of the hauls, the right pane shows the number of hauls.",echo=FALSE, warning=FALSE ,fig.height=8.5, cache=TRUE, dev='png', dpi=300>>=                               
 #Ages
                                           
kne.age <- merge(kne, ages,by=c('Fishery', 'District','Haul_ID','ADFG', 'set_date', 'year', 'date', 'Year'))
                                           
                                           
#age by year
a1 <- ggplot(kne.age, aes(annuli, fill=Year, color=Year))+geom_density()+facet_grid(Bed~.)+
   scale_fill_manual(values=values, breaks=breaks, name='Year')+
   scale_color_manual(values=values,  breaks=breaks, name='Year')+
   guides(colour = guide_legend(override.aes = list(alpha = 1)))+ 
   theme(legend.key = element_blank(),legend.position = c(0.75, 0.08),legend.background = 
            element_rect(fill = "#ffffffaa", colour = NA),legend.key.height=unit(.6,'line'))
a2 <- ggplot(kne.age, aes(annuli, fill=Year, color=Year))+geom_histogram()+facet_grid(Bed~.)+
   scale_fill_manual(values=values, breaks=breaks, name='Year')+
   scale_color_manual(values=values,  breaks=breaks, name='Year')+
   guides(colour = guide_legend(override.aes = list(alpha = 1)))+
   guides( fill=FALSE, color=FALSE)+ theme(legend.key = element_blank())
grid.arrange(a1,a2,ncol=2)
@                                           

<<kneage2, fig.pos="H", fig.cap="Shell ages (annuli) by year for District KNE. The left pane shows the cpue distribution for all of the hauls, the right pane shows the number of hauls.",echo=FALSE, warning=FALSE ,fig.height=8.5, cache=TRUE, dev='png', dpi=300>>=                               
 #Ages
                                           
                        
#age by year
a1 <- ggplot(kne.age, aes(annuli,fill=Rtnd_Disc))+geom_density(alpha=.3)+facet_grid(Year~.)+
   guides(colour = guide_legend(override.aes = list(alpha = 1)))+ 
   theme(legend.key = element_blank(),legend.position = c(0.75, 0.08),legend.background = 
            element_rect(fill = "#ffffffaa", colour = NA),legend.key.height=unit(.6,'line'))
a2 <- ggplot(kne.age, aes(annuli,fill=Rtnd_Disc))+geom_histogram(color='white', alpha=.6)+facet_grid(Year~.)+
      guides(colour = guide_legend(override.aes = list(alpha = 1)))+
   guides( fill=FALSE, color=FALSE)+ theme(legend.key = element_blank())
grid.arrange(a1,a2,ncol=2)
@                                           


<<kneagesh, fig.pos="H", fig.cap="Comparison between shells measured for height and shell height of aged scallops by bed and year for District KNE. The left pane shows the density of all shell heights collected (blue) and the density of shell heights from ages shells (gray). The right pane shows the densities of shell heights from retained shells, discarded shell, and aged shells.",echo=FALSE, warning=FALSE ,fig.height=8.5, cache=TRUE, dev='png', dpi=300>>=
#yakmap+geom_point(data=subset(kne.age, year<2012),aes(Set_Lon,Set_Lat,color=annuli,width=1.2),alpha=.2) +
   #guides(colour = guide_legend(override.aes = list(alpha = 1)))+facet_grid(Year~.)+scale_colour_gradientn(colours=rainbow(5))
#yakmap+geom_point(data=subset(kne.age, year>2011),aes(Set_Lon,Set_Lat,color=annuli,width=1.2),alpha=.2) +
   #guides(colour = guide_legend(override.aes = list(alpha = 1)))+facet_grid(Year~.)+scale_colour_gradientn(colours=rainbow(5))

#ggplot(kne.age, aes(annuli))+geom_density(alpha=.2,fill=4)+facet_grid(Year~.)
#ggplot(kne.age, aes(annuli))+geom_histogram(alpha=.2,color='black', fill=4)+facet_grid(Year~.)

#difference between shell height samples and shell height ages
as1 <- ggplot(kne.age, aes(Shell_Height))+geom_density(alpha=.2,fill='black')+facet_grid(Year~.)+
   geom_density(data=kne.sh, aes(Shell_Height), alpha=.2,fill=4)

as2 <- ggplot(kne.age, aes(Shell_Height))+geom_density(alpha=.2,fill='black')+facet_grid(Year~.)+
   geom_density(data=kne.sh, aes(Shell_Height, fill=Rtnd_Disc), alpha=.2)+guides(colour = guide_legend(override.aes = list(alpha = 1)))+ 
   theme(legend.key = element_blank(),legend.position = c(0.15, 0.23),legend.background = 
            element_rect(fill = "#ffffffaa", colour = NA),legend.key.height=unit(.6,'line'))+
   scale_fill_manual( values=c('D'='#e41a1c','R'='#377eb8'), labels=c('discard', 'retain'),name='')
grid.arrange(as1,as2,ncol=2)
@

<<kneagex,echo=FALSE,message=FALSE,warning=FALSE,dev='png', dpi=300>>=
#Extras
#knemap+geom_point(data=subset(kne.age, year<2012),aes(Set_Lon,Set_Lat,color=annuli,width=1.2),alpha=.2) +
#      guides(colour = guide_legend(override.aes = list(alpha = 1)))+facet_grid(Year~.)+
#      scale_colour_gradientn(colours = =rainbow(5))

#knemap+geom_point(data=subset(kne.age, year>2011),aes(Set_Lon,Set_Lat,color=annuli,width=1.2),alpha=.2) +
#       guides(colour = guide_legend(override.aes = list(alpha = 1)))+facet_grid(Year~.)+
#      scale_colour_gradientn(colours=rainbow(5))
                                           
#ggplot(kne.age, aes(annuli))+geom_density(alpha=.2,fill=4)+facet_grid(Year~.)
#ggplot(kne.age, aes(annuli))+geom_histogram(alpha=.2,color='black', fill=4)+facet_grid(Year~.)
                                           
#difference between shell height samples and shell height ages
#ggplot(kne.age, aes(Shell_Height))+geom_density(alpha=.2,fill='black')+facet_grid(Year~.)+
#      geom_density(data=kne.sh, aes(Shell_Height), alpha=.2,fill=4)
                                           
#ggplot(kne.age, aes(Shell_Height))+geom_density(alpha=.2,fill='black')+facet_grid(Year~Bed, scales='free_y')+
#       geom_density(data=kne.sh, aes(Shell_Height, fill=Rtnd_Disc), alpha=.2)
                                           
                                           
#ggplot(kne.age, aes(annuli, Meat_Weight))+geom_point(alpha=.2,color='black')+facet_grid(Year~.)+
#      stat_smooth()+coord_cartesian(xlim=c(0,20))
#ggplot(kne.age, aes(annuli, Meat_Weight, group=Year,color=Year,fill=Year))+geom_point(alpha=.2,color='black')+
#      stat_smooth()+coord_cartesian(xlim=c(0,20))
                                           
                                           
#ggplot(kne.age, aes(Depth,annuli, group=Year,color=Year,fill=Year))+geom_point(alpha=.2,color='black')+stat_smooth()
#ggplot(kne.age, aes(Depth,annuli, group=Bed,color=Bed,fill=Bed))+geom_point(alpha=.2,color='black')+stat_smooth(method='lm')
#ggplot(kne.sh, aes(Depth,Shell_Height, group=Year,color=Year,fill=Year))+geom_point(alpha=.2,color='black')+stat_smooth(method='lm')
#ggplot(kne.sh, aes(Depth,Shell_Height, group=Bed,color=Bed,fill=Bed))+geom_point(alpha=.2,color='black')+stat_smooth(method='lm')
                                           
                                           
#ggplot(kne.age, aes(Depth,annuli, group=Year,color=Year,fill=Year))+geom_point(alpha=.2,color='black')+stat_smooth()
#ggplot(kne.sh, aes(Shell_Height, Meat_Weight,group=Year,color=Year,fill=Year))+geom_point(alpha=.2,color='black')+stat_smooth(method='lm')

@

<<knecrab, fig.pos="H", fig.cap="Estimated Tanner Crab and Pacific Halibut catch for District KNE.",echo=FALSE, warning=FALSE ,fig.height=4, cache=TRUE, dev='png', dpi=300, eval=TRUE>>=   
kne.by <- merge(by, kne, by=c('Fishery', 'District','ADFG', 'set_date', 'year', 'date', 'Year', 'vessel'))

a <- aggregate(Halibut_Count~year,data=subset(by, District=='KNE'), FUN=sum)
a1 <- aggregate(Tanner_Count~year,data=subset(by, District=='KNE'), FUN=sum)
b <- aggregate(Sample_Hrs~year,data=subset(by, District=='KNE'), FUN=sum)
c <- aggregate(Dredge_Hrs~year,data=kne, FUN=sum)

d <- merge(a,b, by='year')
d <- merge(a1,d, by='year')
d <- merge(c,d, by='year')

d$hal <- d$Halibut_Count/d$Sample_Hrs*d$Dredge_Hrs
d$tan <- d$Tanner_Count/d$Sample_Hrs*d$Dredge_Hrs

d <- d[,c(1,6,7)]
d<- melt(d, id.vars=c( 'year'))
ggplot(d, aes(year, value, color=variable, group=variable))+geom_line()+geom_point(size=3)+
    scale_color_discrete(name="species",
                         breaks=c("tan", "hal"),
                         labels=c("Tanner", "Halibut"))
@

<<knedisc, fig.pos="H", fig.cap="Scallop estimated discard weight for District KNE.",echo=FALSE, warning=FALSE ,fig.height=4, cache=TRUE, dev='png', dpi=300, eval=TRUE>>=   
kne.by <- merge(by, kne, by=c('Fishery', 'District','ADFG', 'set_date', 'year', 'date', 'Year', 'vessel'))

a <- aggregate(Sample_Hrs~year,data=subset(by, District=='KNE'), FUN=sum)
a1 <- aggregate(Discard_Weight~year,data=subset(by, District=='KNE'), FUN=sum)
a2 <- aggregate(Broken_Weight~year,data=subset(by, District=='KNE'), FUN=sum)
a3 <- aggregate(Rem_Disc_Wt~year,data=subset(by, District=='KNE'), FUN=sum)
b <- aggregate(Dredge_Hrs~year,data=kne, FUN=sum)
c <- aggregate(Round_Weight~year,data=kne, FUN=sum)

d <- merge(a,a1, by='year')
d <- merge(d,a2, by='year')
d <- merge(d,a3, by='year')
d <- merge(b,d, by='year')
d <- merge(c,d, by='year')
d$wt <- d[,5]+d[,6]+d[,7]
d$disc <- d$wt/d$Sample_Hrs*d$Dredge_Hrs
d$per <- d$disc/d$Round_Weight*100
ggplot(d, aes(year, disc))+geom_line()+geom_point(size=3)+ylim(0, max(d$disc))+ylab('Scallop discard weight (lbs)')
    
@

<<tablksh, eval=FALSE, echo=FALSE>>=
a <- aggregate(Dredge_Hrs~year, data=ksh, FUN=sum)
b <- aggregate(Meat_Weight~year, data=ksh, FUN=sum)
c <- merge(a,b, by='year')
d <- aggregate(Haul_ID~year, data=ksh, FUN=length)
d <- merge(c,d, by='year')
d$cpue <- d$Meat_Weight/d$Dredge_Hrs
d
@

\subsection{Kodiak Shelikof District}
\subsubsection{Fishery performance}
The 2014/15 Kodiak Shelikof District scallop fishery opened on July 1. 2014 with a GHL of 65,000 lb scallop meat. Three vessels particpated in the fishery (Figure~\ref{fig:kshvessel}) harvesting 65,938 lb scallop meat with a cpue of 41 lb meat/dredge hour (Table~\ref{table:ksh1}). This high cpue is most similar to levels observed in 2000-2002. 


\subsubsection{Size and age structure of catch}

Shell heights were comparable to those of the 2013/14 fishery, the discard group was sizeable and close in size to being recruited to the fishery.
\subsubsection{Scallop discards and crab/halibut bycatch}

An estimated 51,593 Tanner Crab, a substatial increase from previous years, and 200 Pacific Halibut were incidentically caught (Figure~\ref{fig:kshcrab}). Estimated scallop discards for the 2014/15 season were 42,994 lb (7\% of landed round weight).

   \begin{table}[H]
		\centering
		\caption{Kodiak Shelikof District catch summary for the 2014/15 season.}
		
		\label{table:ksh1}
		\begin{tabular}{lcccccc}
					& 		&  Catch 	& Dredge  & Number  &  		 \\ 
			Year	& GHL 	&(lb meat)  & (hours) & hauls  & cpue$^a$\\ 
			\hline	
			1993/94& &	105,017&	2,491&	1,684&	42\\
         1994/95&	&	320,111&	8,662	&5,204&	37\\
         1995/96&	closed&	&	&	&	\\
         1996/97&	&	219,305&	3,466&	1,914&	63\\
         1997/98&	&	258,346&	5,488&	3,042&	47\\
         1998/99&	&	179,870&	4,076&	2,109&	44\\
         1999/00&	180,000&	187,963&	4,295&	2,004&	44\\
         2000/01&	180,000&	180,087&	2,905&	1,403&	62\\
         2001/02&	180,000&	179,198&	3,398&	1,830&	53\\
         2002/03&	180,000&	179,957&	3,799&	2,071&	47\\
         2003/04&	180,000&	180,011&	3,258&	1,722&	64\\
         2004/05&	180,000&	174,622&	3,467&	1,793&	50\\
         2005/06&	160,000&	159,879&	2,278&	1,217&	70\\
         2006/07&	160,000&	161,263&	2,181&	1,280&	74\\
         2007/08&	170,000&	170,224&	2,937&	1,736&	58\\
         2008/09&	170,000&	12,660&	262&	179&	48\\
         2009/10&	170,000&	169,973&	3,496&	1,921&	49\\
         2010/11&	170,000&	171,065&	3,507&	2,218&	49\\
         2011/12&	135,000&	133,079&	2,437&	1,660&	55\\
         2012/13&	105,000&	106,051&	2,002&	1,347&	53\\
         2013/14&	105,000&	108,128&	2,541&	1,680&	43\\
         2014/15&   65,000$^b$     & 65,938 & 1,617&   1,040&   41\\
			\hline	
			\multicolumn{3}{l}{$^a$lb scallop meat/dredge hour}	
         \multicolumn{3}{l}{$^b$Inseason reduction from 105,000}
		\end{tabular} 
	\end{table}
   
<<ksh, fig.pos="H", fig.cap="Maps of District KSH fishing locations by fishing year. The left pane shows the cpue distribution for all of the hauls, the right pane shows the number of hauls.",echo=FALSE, warning=FALSE ,fig.height=8, cache=TRUE,dev='png', dpi=300>>=
#######################
#KSH
#######################

#split by bed
ksh$bed = NA
ksh<-within(ksh,bed[Set_Lat > 58.35]<-1)
ksh<-within(ksh,bed[Set_Lat < 58.35]<-'2-7')

ksh$Bed <- factor(ksh$bed)

bvalues <- c('1'='#e41a1c','2-7'='#377eb8') 
bbreaks <- c('1', '2-7')

#this plot was used to determine breaks in beds
#ggplot(ksh,aes(Set_Lon, Set_Lat, color=Bed))+geom_point()
#remove incomplete data
ksh <- ksh[complete.cases(ksh),]

#map of sample locations

kshmap <- ggplot()+geom_polygon(data=ak,aes(long,lat,group=group, color=Bed),fill=8,color='black') +
   theme(panel.background=element_rect(fill='white')) + 
   xlab(expression(paste(Longitude^o,~'W'))) +
   ylab(expression(paste(Latitude^o,~'W'))) + 
   coord_map(xlim=c(min(ksh$Set_Lon,na.rm=T)-.2,max(ksh$Set_Lon,na.rm=T)+.2),
             ylim=c(min(ksh$Set_Lat,na.rm=T)-.2,max(ksh$Set_Lat,na.rm=T)+.2))

kshmap+geom_point(data=ksh, aes(Set_Lon,Set_Lat, color=Bed), alpha=.2)+facet_wrap(~ Year)+
   guides(colour = guide_legend(override.aes = list(alpha = 1)))+
      theme(legend.key = element_blank(),legend.position = c(0.1, 0.9),legend.background = 
            element_rect(fill = "#ffffffaa", colour = NA),legend.key.height=unit(.6,'line'))+
   scale_fill_manual(values=bvalues,breaks=bbreaks, name='Bed')+
   scale_color_manual(values=bvalues,breaks=bbreaks, name='Bed')
@

<<kshcpue, fig.pos="H", fig.cap="Density and number of tows by bed and year for District KSH cpue. The left pane shows the cpue distribution for all of the hauls, the right pane shows the number of hauls.",echo=FALSE, warning=FALSE ,fig.height=6, cache=TRUE, dev='png', dpi=300>>=
#RAW density and number of tows
m1 <- ggplot(ksh, aes(mwt.cpue,fill=Year,color=Year))+geom_density()+facet_grid(Bed~., scales='free_y')+xlab('log(cpue)')+
   scale_fill_manual(values=values,breaks=breaks, name='Year')+
   scale_color_manual(values=values,breaks=breaks, name='Year')+
   guides(colour = guide_legend(override.aes = list(alpha = 1)))+ 
   theme(legend.key = element_blank(),legend.position = c(0.1, 0.25),legend.background = 
            element_rect(fill = "#ffffffaa", colour = NA),legend.key.height=unit(.6,'line'))

m2 <- ggplot(ksh, aes(mwt.cpue,fill=Year,color=Year))+geom_histogram()+facet_grid(Bed~., scales='free_y')+xlab('log(cpue)')+
   scale_fill_manual(values=values,breaks=breaks, name='Year')+
   scale_color_manual(values=values,breaks=breaks, name='Year')+
   guides( fill=FALSE, color=FALSE)+ theme(legend.key = element_blank())
grid.arrange(m1,m2,ncol=2)
@

<<kshfit, fig.pos="H", fig.cap="Density and number of tows by bed and year for District KSH standardized cpue. Note the different scales for the y-axis. The left pane shows the cpue distribution for all of the hauls, the right pane shows the number of hauls.",echo=FALSE, warning=FALSE ,fig.height=6, cache=TRUE, dev='png', dpi=300>>=
#Model the CPUE

fit <- gam(mwt.cpue~s(Depth,k=4)+te(Set_Lon,Set_Lat)+Year+s(Bed, bs='re')+vessel-1, data=ksh, gamma=1.4)

#plot(ksh$Bed,resid(fit))
ksh$fit <- fitted(fit)
#ggplot(ksh, aes(year, mwa.cpue, color=Bed, fill=Bed))+stat_summary(fun.y=mean, geom='smooth')
f1 <- ggplot(ksh, aes(fit,fill=Year,color=Year))+geom_density()+facet_grid(Bed~., scales='free_y')+
   scale_fill_manual(values=values,breaks=breaks, name='Year')+
   scale_color_manual(values=values,breaks=breaks, name='Year')+
   guides(colour = guide_legend(override.aes = list(alpha = 1)))+ 
   theme(legend.key = element_blank(),legend.position = c(0.1, 0.25),legend.background = 
            element_rect(fill = "#ffffffaa", colour = NA),legend.key.height=unit(.6,'line'))

f2 <- ggplot(ksh, aes(fit,fill=Year,color=Year))+geom_histogram()+facet_grid(Bed~., scales='free_y')+
   scale_fill_manual(values=values,breaks=breaks, name='Year')+
   scale_color_manual(values=values,breaks=breaks, name='Year')+
   guides( fill=FALSE, color=FALSE)+ theme(legend.key = element_blank())
grid.arrange(f1,f2,ncol=2)
@

<<kshfit2, fig.pos="H", fig.cap="Standardized and raw CPUE by year and bed for District KSH. Standardized cpue have bootstrap estimated 95\\% confidence levels, the raw cpue have normal approximate 95\\% confidence levels.",echo=FALSE, warning=FALSE ,fig.height=3.9, cache=TRUE, dev='png', dpi=300>>=
r1 <- ggplot(ksh, aes(year, fit, color=Bed, fill=Bed))+stat_summary(fun.data=mean_cl_boot, geom='smooth')+
   scale_fill_manual(values=bvalues,breaks=bbreaks, name='Bed')+
   scale_color_manual(values=bvalues,breaks=bbreaks, name='Bed')+
   theme(legend.key = element_blank(),legend.position = c(0.75, 0.1),legend.background = 
            element_rect(fill = "#ffffffaa", colour = NA),legend.key.height=unit(.6,'line'))+ylab('standardized cpue')

a <- aggregate(mwt.cpue~year+Bed,data=ksh, FUN=mean)
b <- aggregate(mwt.cpue~year+Bed,data=ksh, FUN=sd)
names(b) <- c('year','Bed', 'sd')
c <- aggregate(mwt.cpue~year+Bed,data=ksh, FUN=length)
names(c) <- c('year','Bed', 'n')
d <- merge(a,b, by=c('year','Bed'))
d <- merge(c,d, by=c('year','Bed'))
d$lci <- d$mwt.cpue-2*d$sd/sqrt(d$n)
d$uci <- d$mwt.cpue+2*d$sd/sqrt(d$n)
r2 <- ggplot(d, aes(year,mwt.cpue, fill=Bed))+geom_line(aes(color=Bed))+
   geom_ribbon(aes(ymin=lci, ymax=uci),alpha=.2)+
      scale_fill_manual(values=bvalues,breaks=bbreaks, name='Bed')+
   scale_color_manual(values=bvalues,breaks=bbreaks, name='Bed')+coord_cartesian(ylim=c(3,4.5))
      guides( fill=FALSE, color=FALSE)+ theme(legend.key = element_blank())+ylab('raw cpue')
grid.arrange(r1,r2,ncol=2)
@


<<kshvessel, fig.pos="H", fig.cap="Annual vessel effect from model fit, District KSH.",echo=FALSE, warning=FALSE ,fig.height=3.9, cache=TRUE,dev='png',dpi=300>>=
#Model the CPUE
#ggplot(kne, aes(Year,fit, fill=Bed))+geom_boxplot()
#ggplot(kne, aes(vessel,fit, fill=Bed))+geom_boxplot()
ggplot(ksh, aes(Year,fit, fill=vessel))+geom_boxplot(width=.35)
@


<<kshsh, fig.pos="H", fig.cap="Shell heights by bed and year for District KSH. Note the different scales for the y-axis. The left pane shows the shell height distribution for all of the hauls, the right pane shows the number of shell heights measured.",echo=FALSE, warning=FALSE ,fig.height=6, cache=TRUE, dev='png', dpi=300>>=
#Shell heights
ksh.sh <- merge(ksh,sh,by=c('Fishery', 'District','Haul_ID','ADFG'))

#SH by year
s1 <- ggplot(ksh.sh, aes(Shell_Height, fill=Year,color=Year))+geom_density()+facet_grid(Bed~.)+
   scale_fill_manual(values=values,breaks=breaks, name='Year')+
   scale_color_manual(values=values,breaks=breaks, name='Year')+
   guides(colour = guide_legend(override.aes = list(alpha = 1)))+ 
   theme(legend.key = element_blank(),legend.position = c(0.18, 0.15),legend.background = 
   element_rect(fill = "#ffffffaa", colour = NA),legend.key.height=unit(.6,'line'))
                                           
s2 <- ggplot(ksh.sh, aes(Shell_Height, fill=Year,color=Year))+geom_histogram()+facet_grid(Bed~., scales='free_y')+
   scale_fill_manual(values=values,breaks=breaks, name='Year')+
   scale_color_manual(values=values,breaks=breaks, name='Year')+
   guides(colour = guide_legend(override.aes = list(alpha = 1)))+
   guides( fill=FALSE, color=FALSE)+ theme(legend.key = element_blank())
grid.arrange(s1,s2,ncol=2)
@

<<kshsh14, fig.pos="H", fig.cap="Retained and discarded shell heights by bed for District KSH in 2014. Note the different scales for the y-axis. The left pane shows the shell height distribution for all of the hauls, the right pane shows the number of shell heights measured.",echo=FALSE, warning=FALSE ,fig.height=6, cache=TRUE, dev='png', dpi=300>>=
#SH by bed
s1 <- ggplot(subset(ksh.sh, year==2014), aes(Shell_Height, fill=Rtnd_Disc,color=Rtnd_Disc))+geom_density(alpha=.2)+facet_grid(Bed~.)+
   scale_color_manual( values=c('D'='#e41a1c','R'='#377eb8'), labels=c('discard', 'retain'),name='')+
   scale_fill_manual( values=c('D'='#e41a1c','R'='#377eb8'), labels=c('discard', 'retain'),name='')+ 
   theme(legend.key = element_blank(),legend.position = c(0.18, 0.75),legend.background = 
   element_rect(fill = "#ffffffaa", colour = NA),legend.key.height=unit(.6,'line'))
s2 <- ggplot(subset(ksh.sh, year==2014), aes(Shell_Height, fill=Rtnd_Disc,color=Rtnd_Disc))+geom_histogram(alpha=.2)+facet_grid(Bed~., scales='free_y')+
   scale_color_manual( values=c('D'='#e41a1c','R'='#377eb8'), labels=c('discard', 'retain'),name='')+
   scale_fill_manual( values=c('D'='#e41a1c','R'='#377eb8'), labels=c('discard', 'retain'),name='')+
   guides( fill=FALSE, color=FALSE)+ theme(legend.key = element_blank())
grid.arrange(s1,s2,ncol=2)
@


<<kshsh3, fig.pos="H", fig.cap="Shell heights by year, all beds combined, for District KSH. The left pane shows the shell height distribution for all of the hauls, the right pane shows the number of shell heights measured.",echo=FALSE, warning=FALSE ,fig.height=8.5, cache=TRUE,dev='png', dpi=300>>=

#SH by year
s1 <- ggplot(ksh.sh, aes(Shell_Height, fill=Rtnd_Disc,color=Rtnd_Disc))+geom_density(alpha=.2)+facet_grid(Year~.)+
   scale_color_manual( values=c('D'='#e41a1c','R'='#377eb8'), labels=c('discard', 'retain'),name='')+
   scale_fill_manual( values=c('D'='#e41a1c','R'='#377eb8'), labels=c('discard', 'retain'),name='')+ 
   theme(legend.key = element_blank(),legend.position = c(0.2, 0.25),legend.background = 
   element_rect(fill = "#ffffffaa", colour = NA),legend.key.height=unit(.6,'line'))

s2 <- ggplot(ksh.sh, aes(Shell_Height, fill=Rtnd_Disc,color=Rtnd_Disc))+geom_histogram(alpha=.2)+facet_grid(Year~.)+
   scale_color_manual( values=c('D'='#e41a1c','R'='#377eb8'), labels=c('discard', 'retain'),name='')+
   scale_fill_manual( values=c('D'='#e41a1c','R'='#377eb8'), labels=c('discard', 'retain'),name='')+
   guides( fill=FALSE, color=FALSE)+ theme(legend.key = element_blank())
grid.arrange(s1,s2,ncol=2)
@


<<kshage, fig.pos="H", fig.cap="Shell ages (annuli) by bed and year for District KSH. Note the different scales for the y-axis. The left pane shows the shell age distribution for all of the hauls, the right pane shows the number of shells used for aging.",echo=FALSE, warning=FALSE ,fig.height=6, cache=TRUE, dev='png', dpi=300>>=                               
 #Ages
                                           
ksh.age <- merge(ksh, ages,by=c('Fishery', 'District','Haul_ID','ADFG', 'set_date', 'year', 'date', 'Year'))
                                           
                                           
#age by year
a1 <- ggplot(ksh.age, aes(annuli, fill=Year, color=Year))+geom_density()+facet_grid(Bed~., scales='free_y')+
   scale_fill_manual(values=values, breaks=breaks, name='Year')+
   scale_color_manual(values=values,  breaks=breaks, name='Year')+
   guides(colour = guide_legend(override.aes = list(alpha = 1)))+ 
   theme(legend.key = element_blank(),legend.position = c(0.75, 0.15),legend.background = 
            element_rect(fill = "#ffffffaa", colour = NA),legend.key.height=unit(.6,'line'))
a2 <- ggplot(ksh.age, aes(annuli, fill=Year, color=Year))+geom_histogram()+facet_grid(Bed~., scales='free_y')+
   scale_fill_manual(values=values, breaks=breaks, name='Year')+
   scale_color_manual(values=values,  breaks=breaks, name='Year')+
   guides(colour = guide_legend(override.aes = list(alpha = 1)))+
   guides( fill=FALSE, color=FALSE)+ theme(legend.key = element_blank())
grid.arrange(a1,a2,ncol=2)
@                                 

<<kshage2, fig.pos="H", fig.cap="Shell ages (annuli) by bed and year for District KNE. The left pane shows the shell age distribution for all of the hauls, the right pane shows the number of shells used for aging.",echo=FALSE, warning=FALSE ,fig.height=8.5, cache=TRUE, dev='png', dpi=300>>=                               
 #Ages
                                           
                        
#age by year
a1 <- ggplot(ksh.age, aes(annuli,fill=Rtnd_Disc))+geom_density(alpha=.3)+facet_grid(Year~., scale='free_y')+
   guides(colour = guide_legend(override.aes = list(alpha = 1)))+ 
   theme(legend.key = element_blank(),legend.position = c(0.75, 0.08),legend.background = 
            element_rect(fill = "#ffffffaa", colour = NA),legend.key.height=unit(.6,'line'))
a2 <- ggplot(ksh.age, aes(annuli,fill=Rtnd_Disc))+geom_histogram(color='white')+facet_grid(Year~.)+
      guides(colour = guide_legend(override.aes = list(alpha = 1)))+
   guides( fill=FALSE, color=FALSE)+ theme(legend.key = element_blank())
grid.arrange(a1,a2,ncol=2)
@   

<<kshagesh, fig.pos="H", fig.cap="Comparison between shells measured for height and shell height of aged scallops by bed and year for District KSH. The left pane shows the density of all shell heights collected (blue) and the density of shell heights from ages shells (gray). The right pane shows the densities of shell heights from retained shells, discarded shell, and aged shells.",echo=FALSE, warning=FALSE ,fig.height=8.5, cache=TRUE, dev='png', dpi=300>>=


#kshmap+geom_point(data=subset(ksh.age, year<2012),aes(Set_Lon,Set_Lat,color=annuli,width=1.2),alpha=.2) +
#   guides(colour = guide_legend(override.aes = list(alpha = 1)))+facet_grid(Year~.)+
#   scale_colour_gradientn(colours =rainbow(5))

#kshmap+geom_point(data=subset(ksh.age, year>2011),aes(Set_Lon,Set_Lat,color=annuli,width=1.2),alpha=.2) +
#   guides(colour = guide_legend(override.aes = list(alpha = 1)))+facet_grid(Year~.)+
#   scale_colour_gradientn(colours=rainbow(5))

#ggplot(ksh.age, aes(annuli))+geom_density(alpha=.2,fill=4)+facet_grid(Year~.)
#ggplot(ksh.age, aes(annuli))+geom_histogram(alpha=.2,color='black', fill=4)+facet_grid(Year~.)

#difference between shell height samples and shell height ages
as1 <- ggplot(ksh.age, aes(Shell_Height))+geom_density(alpha=.2,fill='black')+facet_grid(Year~.)+
   geom_density(data=ksh.sh, aes(Shell_Height), alpha=.2,fill=4)

as2 <- ggplot(ksh.age, aes(Shell_Height))+geom_density(alpha=.2,fill='black')+facet_grid(Year~.)+
   geom_density(data=ksh.sh, aes(Shell_Height, fill=Rtnd_Disc), alpha=.2)+guides(colour = guide_legend(override.aes = list(alpha = 1)))+ 
   theme(legend.key = element_blank(),legend.position = c(0.15, 0.23),legend.background = 
            element_rect(fill = "#ffffffaa", colour = NA),legend.key.height=unit(.6,'line'))+
   scale_fill_manual( values=c('D'='#e41a1c','R'='#377eb8'), labels=c('discard', 'retain'),name='')
grid.arrange(as1,as2,ncol=2)
@

<<kshagex,echo=FALSE,message=FALSE,warning=FALSE, dev='png', dpi=300>>=
#Extras
#ggplot(ksh.age, aes(annuli, Meat_Weight))+geom_point(alpha=.2,color='black')+facet_grid(Year~.)+
#   stat_smooth()+coord_cartesian(xlim=c(0,20))
#ggplot(ksh.age, aes(annuli, Meat_Weight, group=Year,color=Year,fill=Year))+geom_point(alpha=.2,color='black')+
#   stat_smooth()+coord_cartesian(xlim=c(0,20))


#ggplot(ksh.age, aes(Depth,annuli, group=Year,color=Year,fill=Year))+geom_point(alpha=.2,color='black')+stat_smooth()
#ggplot(ksh.age, aes(Depth,annuli, group=Bed,color=Bed,fill=Bed))+geom_point(alpha=.2,color='black')+stat_smooth(method='lm')
#ggplot(ksh.sh, aes(Depth,Shell_Height, group=Year,color=Year,fill=Year))+geom_point(alpha=.2,color='black')+stat_smooth(method='lm')
#ggplot(ksh.sh, aes(Depth,Shell_Height, group=Bed,color=Bed,fill=Bed))+geom_point(alpha=.2,color='black')+stat_smooth(method='lm')


#ggplot(ksh.age, aes(Depth,annuli, group=Year,color=Year,fill=Year))+geom_point(alpha=.2,color='black')+stat_smooth()
#ggplot(ksh.sh, aes(Shell_Height, Meat_Weight,group=Year,color=Year,fill=Year))+geom_point(alpha=.2,color='black')+stat_smooth(method='lm')
@


<<kshcrab, fig.pos="H", fig.cap="Estimated Tanner Crab and Pacific Halibut catch for District KSH.",echo=FALSE, warning=FALSE ,fig.height=4, cache=TRUE, dev='png', dpi=300, eval=TRUE>>=   
ksh.by <- merge(by, ksh, by=c('Fishery', 'District','ADFG', 'set_date', 'year', 'date', 'Year', 'vessel'))

a <- aggregate(Halibut_Count~year,data=subset(by, District=='KSH'), FUN=sum)
a1 <- aggregate(Tanner_Count~year,data=subset(by, District=='KSH'), FUN=sum)
b <- aggregate(Sample_Hrs~year,data=subset(by, District=='KSH'), FUN=sum)
c <- aggregate(Dredge_Hrs~year,data=ksh, FUN=sum)

d <- merge(a,b, by='year')
d <- merge(a1,d, by='year')
d <- merge(c,d, by='year')

d$hal <- d$Halibut_Count/d$Sample_Hrs*d$Dredge_Hrs
d$tan <- d$Tanner_Count/d$Sample_Hrs*d$Dredge_Hrs

d <- d[,c(1,6,7)]
d<- melt(d, id.vars=c( 'year'))
ggplot(d, aes(year, value, color=variable, group=variable))+geom_line()+geom_point(size=3)+
    scale_color_discrete(name="species",
                         breaks=c("tan", "hal"),
                         labels=c("Tanner", "Halibut"))
@

<<kshdisc, fig.pos="H", fig.cap="Scallop estimated discard weight for District KSH.",echo=FALSE, warning=FALSE ,fig.height=4, cache=TRUE, dev='png', dpi=300, eval=TRUE>>=   
ksh.by <- merge(by, ksh, by=c('Fishery', 'District','ADFG', 'set_date', 'year', 'date', 'Year', 'vessel'))

a <- aggregate(Sample_Hrs~year,data=subset(by, District=='KSH'), FUN=sum)
a1 <- aggregate(Discard_Weight~year,data=subset(by, District=='KSH'), FUN=sum)
a2 <- aggregate(Broken_Weight~year,data=subset(by, District=='KSH'), FUN=sum)
a3 <- aggregate(Rem_Disc_Wt~year,data=subset(by, District=='KSH'), FUN=sum)
b <- aggregate(Dredge_Hrs~year,data=ksh, FUN=sum)
c <- aggregate(Round_Weight~year,data=ksh, FUN=sum)

d <- merge(a,a1, by='year')
d <- merge(d,a2, by='year')
d <- merge(d,a3, by='year')
d <- merge(b,d, by='year')
d <- merge(c,d, by='year')
d$wt <- d[,5]+d[,6]+d[,7]
d$disc <- d$wt/d$Sample_Hrs*d$Dredge_Hrs
d$per <- d$disc/d$Round_Weight*100
ggplot(d, aes(year, disc))+geom_line()+geom_point(size=3)+ylim(0, max(d$disc))+ylab('Scallop discard weight (lbs)')
    
@


<<tablksw, eval=FALSE, echo=FALSE>>=
a <- aggregate(Dredge_Hrs~year, data=ksw, FUN=sum)
b <- aggregate(Meat_Weight~year, data=ksw, FUN=sum)
c <- merge(a,b, by='year')
d <- aggregate(Haul_ID~year, data=ksw, FUN=length)
d <- merge(c,d, by='year')
d$cpue <- d$Meat_Weight/d$Dredge_Hrs
d
@

\subsection{Kodiak Southwest District}
\subsubsection{Fishery performance}
The 2014/15 Kodiak Shelikof District scallop fishery opened on July 1. 2014 with a GHL of 25,000 lb scallop meat. Two vessels particpated in the fishery (Figure~\ref{fig:kswvessel}) harvesting 24,973 lb scallop meat with a cpue of 46 lb meat/dredge hour (Table~\ref{table:ksw1}). This high cpue is most similar to levels observed in 2000-2002. 


\subsubsection{Size and age structure of catch}
Shell heights were similar to those observed in the 2013/14 catch, with the bulk of the samples being 9-years old. There appears to be some shells of a size to recruit to the fishery soon, though smaller individuals are poorly represented.

\subsubsection{Scallop discards and crab/halibut bycatch}

An estimated 17,952 Tanner Crab, a substantial increase from previous years, and 141 Pacific Halibut were incidentically caught (Figure~\ref{fig:kswcrab}). Estimated scallop discards were 7,928 lb (3\% of total round weight landed).
   \begin{table}[H]
   	\centering
		\caption{Kodiak Southwest District catch summary for the 2014/15 season.}
		
		\label{table:ksw1}
		\begin{tabular}{lcccccc}
					& 		&  Catch 	& Dredge  & Number  &  		 \\ 
			Year	& GHL 	&(lb meat)  & (hours) & hauls  & cpue$^a$\\ 
			\hline	
		   2009/10&	25,000&	3,480    &154     &	155   &	23\\
         2010/11&	NA    &	NA       &	NA    &  NA    &	NA\\
         2011/12&	25,000&	25,110   &	453   &	307   &	55\\
         2012/13&	25,000&	25,014   &	666   &	427   &	38\\
         2013/14&	25,000&	20,340   &	522   &	341   &	39\\
         2014/15& 25,000& 24,973    & 548    &  340   &   46\\
			\hline	
			\multicolumn{3}{l}{$^a$lb scallop meat/dredge hour}	
		\end{tabular} 
	\end{table}
   
<<ksw, fig.pos="H", fig.cap="Maps of District KSW fishing locations by fishing year.",echo=FALSE, warning=FALSE ,fig.height=8, cache=TRUE,dev='png', dpi=300>>=
#######################
#KSW
#######################

#split by bed
ksw$bed = NA
ksw<-within(ksw,bed[Set_Lat > 56.7]<-1)
ksw<-within(ksw,bed[Set_Lat < 56.7]<-2)

ksw$Bed <- factor(ksw$bed)

bvalues <- c('1'='#e41a1c','2'='#377eb8') 
bbreaks <- c('1', '2')

#ggplot(ksw,aes(Set_Lon, Set_Lat, color=Bed))+geom_point()+facet_grid(Year~.)
#remove incomplete data
ksw <- ksw[complete.cases(ksw),]

#map of sample locations

kswmap <- ggplot()+geom_polygon(data=ak,aes(long,lat,group=group),fill=8,color='black') +
   theme(panel.background=element_rect(fill='white')) + 
   xlab(expression(paste(Longitude^o,~'W'))) +
   ylab(expression(paste(Latitude^o,~'W'))) + 
   coord_map(xlim=c(min(ksw$Set_Lon,na.rm=T)-.5,max(ksw$Set_Lon,na.rm=T)+.5),
             ylim=c(min(ksw$Set_Lat,na.rm=T)-.5,max(ksw$Set_Lat,na.rm=T)+.5))

kswmap+geom_point(data=ksw, aes(Set_Lon,Set_Lat, color=Bed), alpha=.2)+facet_wrap(~ Year)+
   guides(colour = guide_legend(override.aes = list(alpha = 1)))+
   theme(legend.key = element_blank(),legend.position = c(0.1, 0.9),legend.background = 
            element_rect(fill = "#ffffffaa", colour = NA),legend.key.height=unit(.6,'line'))+
   scale_fill_manual(values=bvalues,breaks=bbreaks, name='Bed')+
   scale_color_manual(values=bvalues,breaks=bbreaks, name='Bed')
@

<<kswcpue, fig.pos="H", fig.cap="Density and number of tows by bed and year for District KSW cpue. The left pane shows the cpue distribution for all of the hauls, the right pane shows the number of hauls.",echo=FALSE, warning=FALSE ,fig.height=6, cache=TRUE, dev='png', dpi=300>>=
#RAW density and number of tows
m1 <- ggplot(ksw, aes(mwt.cpue,fill=Year,color=Year))+geom_density()+facet_grid(Bed~., scales='free_y')+xlab('log(cpue)')+
   scale_fill_manual(values=values,breaks=breaks, name='Year')+
   scale_color_manual(values=values,breaks=breaks, name='Year')+
   guides(colour = guide_legend(override.aes = list(alpha = 1)))+ 
   theme(legend.key = element_blank(),legend.position = c(0.15, 0.45),legend.background = 
            element_rect(fill = "#ffffffaa", colour = NA),legend.key.height=unit(.6,'line'))

m2 <- ggplot(ksw, aes(mwt.cpue,fill=Year,color=Year))+geom_histogram()+facet_grid(Bed~., scales='free_y')+xlab('log(cpue)')+
   scale_fill_manual(values=values,breaks=breaks, name='Year')+
   scale_color_manual(values=values,breaks=breaks, name='Year')+
   guides( fill=FALSE, color=FALSE)+ theme(legend.key = element_blank())
grid.arrange(m1,m2,ncol=2)
@

<<kswfit, fig.pos="H", fig.cap="Density and number of tows by bed and year for District KSW standardized cpue. Note the different scales for the y-axis. The left pane shows the cpue distribution for all of the hauls, the right pane shows the number of hauls.",echo=FALSE, warning=FALSE ,fig.height=6, cache=TRUE, dev='png', dpi=300>>=
#Model the CPUE

fit <- gam(mwt.cpue~s(Depth,k=4)+te(Set_Lon,Set_Lat)+Year+s(Bed, bs='re')+vessel-1, data=ksw, gamma=1.4)
#plot(kne$Bed,resid(fit))
ksw$fit <- fitted(fit)
f1 <- ggplot(ksw, aes(fit,fill=Year,color=Year))+geom_density()+facet_grid(Bed~., scales='free_y')+
   scale_fill_manual(values=values,breaks=breaks, name='Year')+
   scale_color_manual(values=values,breaks=breaks, name='Year')+
   guides(colour = guide_legend(override.aes = list(alpha = 1)))+ 
   theme(legend.key = element_blank(),legend.position = c(0.15, 0.25),legend.background = 
            element_rect(fill = "#ffffffaa", colour = NA),legend.key.height=unit(.6,'line'))

f2 <- ggplot(ksw, aes(fit,fill=Year,color=Year))+geom_histogram()+facet_grid(Bed~., scales='free_y')+
   scale_fill_manual(values=values,breaks=breaks, name='Year')+
   scale_color_manual(values=values,breaks=breaks, name='Year')+
   guides( fill=FALSE, color=FALSE)+ theme(legend.key = element_blank())
grid.arrange(f1,f2,ncol=2)
@

<<kswvessel, fig.pos="H", fig.cap="Annual vessel effect from model fit, District KSW.",echo=FALSE, warning=FALSE ,fig.height=3.9, cache=TRUE,dev='png',dpi=300>>=
#Model the CPUE
#ggplot(kne, aes(Year,fit, fill=Bed))+geom_boxplot()
#ggplot(kne, aes(vessel,fit, fill=Bed))+geom_boxplot()
ggplot(ksw, aes(Year,fit, fill=vessel))+geom_boxplot(width=.35)
@


<<kswfit2, fig.pos="H", fig.cap="Standardized and raw CPUE by year and bed for District KSW. Standardized cpue have bootstrap estimated 95\\% confidence levels, the raw cpue have normal approximate 95\\% confidence levels.",echo=FALSE, warning=FALSE ,fig.height=4, cache=TRUE, dev='png', dpi=300>>=
r1 <- ggplot(ksw, aes(year, fit, color=Bed, fill=Bed))+stat_summary(fun.data=mean_cl_boot, geom='smooth')+
   scale_fill_manual(values = bvalues,breaks= bbreaks, name='bed')+
   scale_color_manual(values = bvalues,breaks= bbreaks, name='bed')+ 
   theme(legend.key = element_blank(),legend.position = c(0.75, 0.1),legend.background = 
            element_rect(fill = "#ffffffaa", colour = NA),legend.key.height=unit(.6,'line'))

a <- aggregate(mwt.cpue~year+Bed,data=ksw, FUN=mean)
b <- aggregate(mwt.cpue~year+Bed,data=ksw, FUN=sd)
names(b) <- c('year','Bed', 'sd')
c <- aggregate(mwt.cpue~year+Bed,data=ksw, FUN=length)
names(c) <- c('year','Bed', 'n')
d <- merge(a,b, by=c('year','Bed'))
d <- merge(c,d, by=c('year','Bed'))
d$lci <- d$mwt.cpue-2*d$sd/sqrt(d$n)
d$uci <- d$mwt.cpue+2*d$sd/sqrt(d$n)
r2 <- ggplot(d, aes(year,mwt.cpue, fill=Bed))+geom_line(aes(color=Bed))+
   geom_ribbon(aes(ymin=lci, ymax=uci), alpha=.2)+
   scale_fill_manual(values = bvalues,breaks= bbreaks, name='bed')+
   scale_color_manual(values = bvalues,breaks= bbreaks, name='bed')+ 
      guides( fill=FALSE, color=FALSE)+ theme(legend.key = element_blank())
grid.arrange(r1,r2,ncol=2)
@

<<kswsh, fig.pos="H", fig.cap="Shell heights by bed and year for District KSW. Note the different scales for the y-axis. The left pane shows the shell heights distribution for all of the hauls, the right pane shows the number of shells sampled at a given height.",echo=FALSE, warning=FALSE ,fig.height=6, cache=TRUE,dev='png', dpi=300>>=
#Shell heights
ksw.sh <- merge(ksw,sh,by=c('Fishery', 'District','Haul_ID','ADFG'))

#SH by year
s1 <- ggplot(ksw.sh, aes(Shell_Height, fill=Year,color=Year))+geom_density()+facet_grid(Bed~.)+
   scale_fill_manual(values=values,breaks=breaks, name='Year')+
   scale_color_manual(values=values,breaks=breaks, name='Year')+
   guides(colour = guide_legend(override.aes = list(alpha = 1)))+ 
   theme(legend.key = element_blank(),legend.position = c(0.15, 0.2),legend.background = 
   element_rect(fill = "#ffffffaa", colour = NA),legend.key.height=unit(.6,'line'))
                                           
s2 <- ggplot(ksw.sh, aes(Shell_Height, fill=Year,color=Year))+geom_histogram()+facet_grid(Bed~., scales='free_y')+
   scale_fill_manual(values=values,breaks=breaks, name='Year')+
   scale_color_manual(values=values,breaks=breaks, name='Year')+
   guides(colour = guide_legend(override.aes = list(alpha = 1)))+
   guides( fill=FALSE, color=FALSE)+ theme(legend.key = element_blank())
grid.arrange(s1,s2,ncol=2)
@

<<kswsh14, fig.pos="H",  fig.cap="Retained and discarded shell heights by bed for District KSW in 2014. Note that no harvest occurred in bed 1. The left pane shows the shell heights distribution for all of the hauls, the right pane shows the number of shells sampled at a given height.",echo=FALSE, warning=FALSE ,fig.height=4, message=FALSE,cache=TRUE,dev='png', dpi=300>>=
s1 <- ggplot(subset(ksw.sh, year==2014), aes(Shell_Height, fill=Rtnd_Disc,color=Rtnd_Disc))+geom_density(alpha=.2)+facet_grid(Bed~.)+
   scale_color_manual( values=c('D'='#e41a1c','R'='#377eb8'), labels=c('discard', 'retain'),name='')+
   scale_fill_manual( values=c('D'='#e41a1c','R'='#377eb8'), labels=c('discard', 'retain'),name='')+ 
   theme(legend.key = element_blank(),legend.position = c(0.2, 0.45),legend.background = 
   element_rect(fill = "#ffffffaa", colour = NA),legend.key.height=unit(.6,'line'))
s2 <- ggplot(subset(ksw.sh, year==2014), aes(Shell_Height, fill=Rtnd_Disc,color=Rtnd_Disc))+geom_histogram(alpha=.2)+facet_grid(Bed~., scales='free_y')+
   scale_color_manual( values=c('D'='#e41a1c','R'='#377eb8'), labels=c('discard', 'retain'),name='')+
   scale_fill_manual( values=c('D'='#e41a1c','R'='#377eb8'), labels=c('discard', 'retain'),name='')+
   guides( fill=FALSE, color=FALSE)+ theme(legend.key = element_blank())
grid.arrange(s1,s2,ncol=2)
@


<<kswsh3, fig.pos="H", fig.cap="Shell heights by year, all beds combined, for District KNE. The left pane shows the shell heights distribution for all of the hauls, the right pane shows the number of shells sampled at a given height.",echo=FALSE, warning=FALSE ,fig.height=8.5, cache=TRUE,dev='png', dpi=300>>=

#SH by year
s1 <- ggplot(ksw.sh, aes(Shell_Height, fill=Rtnd_Disc,color=Rtnd_Disc))+geom_density(alpha=.2)+facet_grid(Year~.)+
   scale_color_manual( values=c('D'='#e41a1c','R'='#377eb8'), labels=c('discard', 'retain'),name='')+
   scale_fill_manual( values=c('D'='#e41a1c','R'='#377eb8'), labels=c('discard', 'retain'),name='')+ 
   theme(legend.key = element_blank(),legend.position = c(0.2, 0.25),legend.background = 
   element_rect(fill = "#ffffffaa", colour = NA),legend.key.height=unit(.6,'line'))

s2 <- ggplot(ksw.sh, aes(Shell_Height, fill=Rtnd_Disc,color=Rtnd_Disc))+geom_histogram(alpha=.2)+facet_grid(Year~.)+
   scale_color_manual( values=c('D'='#e41a1c','R'='#377eb8'), labels=c('discard', 'retain'),name='')+
   scale_fill_manual( values=c('D'='#e41a1c','R'='#377eb8'), labels=c('discard', 'retain'),name='')+
   guides( fill=FALSE, color=FALSE)+ theme(legend.key = element_blank())
grid.arrange(s1,s2,ncol=2)
@


<<kswage, fig.pos="H", fig.cap="Shell ages (annuli) by bed and year for District KSW. Note that there are no age samples from bed 1. Left pane shows the distribution of ages, the right pane shows the number of samples aged.",echo=FALSE,error=FALSE, warning=FALSE ,fig.height=4, message=FALSE,cache=TRUE, dev='png', dpi=300>>=                               
 #Ages
                                           
ksw.age <- merge(ksw, ages,by=c('Fishery', 'District','Haul_ID','ADFG', 'set_date', 'year', 'date', 'Year'))
                                           
#age by year
a1 <- ggplot(ksw.age, aes(annuli, fill=Year, color=Year))+geom_density()+
   scale_fill_manual(values=values, breaks=breaks, name='Year')+
   scale_color_manual(values=values,  breaks=breaks, name='Year')+
   guides(colour = guide_legend(override.aes = list(alpha = 1)))+guides(colour = guide_legend(override.aes = list(alpha = 1)))+
   guides( fill=FALSE, color=FALSE)+ theme(legend.key = element_blank())
a2 <- ggplot(ksw.age, aes(annuli, fill=Year, color=Year))+geom_histogram()+
   scale_fill_manual(values=values, breaks=breaks, name='Year')+
   scale_color_manual(values=values,  breaks=breaks, name='Year')+ 
   theme(legend.key = element_blank(),legend.position = c(0.8, 0.75),legend.background = 
            element_rect(fill = "#ffffffaa", colour = NA),legend.key.height=unit(.6,'line'))
   
grid.arrange(a1,a2,ncol=2)
@ 

<<kswage2, fig.pos="H", fig.cap="Shell ages (annuli) by bed and year for District KSW. The left pane shows the shell age distribution for all of the hauls, the right pane shows the number of shells used for aging.",echo=FALSE, warning=FALSE ,fig.height=8.5, cache=TRUE, dev='png', dpi=300>>=                               
 #Ages
                                           
                        
#age by year
a1 <- ggplot(ksw.age, aes(annuli,fill=Rtnd_Disc))+geom_density(alpha=.3)+facet_grid(Year~., scale='free_y')+
   guides(colour = guide_legend(override.aes = list(alpha = 1)))+ 
   theme(legend.key = element_blank(),legend.position = c(0.75, 0.15),legend.background = 
            element_rect(fill = "#ffffffaa", colour = NA),legend.key.height=unit(.6,'line'))
a2 <- ggplot(ksw.age, aes(annuli,fill=Rtnd_Disc))+geom_histogram(color='white')+facet_grid(Year~.)+
      guides(colour = guide_legend(override.aes = list(alpha = 1)))+
   guides( fill=FALSE, color=FALSE)+ theme(legend.key = element_blank())
grid.arrange(a1,a2,ncol=2)
@

<<kswagesh, fig.pos="H", fig.cap="Comparison between shells measured for height and shell height of aged scallops by year for District KSW. The left pane shows the density of all shell heights collected (blue) and the density of shell heights from ages shells (gray). The right pane shows the densities of shell heights from retained shells, discarded shell, and aged shells.",echo=FALSE,error=FALSE, warning=FALSE ,fig.height=8.5, cache=TRUE, dev='png', dpi=300>>=


#kswmap+geom_point(data=subset(ksw.age, year<2012),aes(Set_Lon,Set_Lat,color=annuli,width=1.2),alpha=.2) +
#   guides(colour = guide_legend(override.aes = list(alpha = 1)))+facet_grid(Year~.)+
#   scale_colour_gradientn(colours =rainbow(5))

#kswmap+geom_point(data=subset(ksw.age, year>2011),aes(Set_Lon,Set_Lat,color=annuli,width=1.2),alpha=.2) +
#   guides(colour = guide_legend(override.aes = list(alpha = 1)))+facet_grid(Year~.)+
#   scale_colour_gradientn(colours=rainbow(5))

#ggplot(ksw.age, aes(annuli))+geom_density(alpha=.2,fill=4)+facet_grid(Year~.)
#ggplot(ksw.age, aes(annuli))+geom_histogram(alpha=.2,color='black', fill=4)+facet_grid(Year~.)

#difference between shell height samples and shell height ages
as1 <- ggplot(ksw.age, aes(Shell_Height))+geom_density(alpha=.2,fill='black')+facet_grid(Year~.)+
   geom_density(data=ksw.sh, aes(Shell_Height), alpha=.2,fill=4)

as2 <- ggplot(ksw.age, aes(Shell_Height))+geom_density(alpha=.2,fill='black')+facet_grid(Year~.)+
   geom_density(data=ksw.sh, aes(Shell_Height, fill=Rtnd_Disc), alpha=.2)+guides(colour = guide_legend(override.aes = list(alpha = 1)))+ 
   theme(legend.key = element_blank(),legend.position = c(0.18, 0.33),legend.background = 
            element_rect(fill = "#ffffffaa", colour = NA),legend.key.height=unit(.6,'line'))+
   scale_fill_manual( values=c('D'='#e41a1c','R'='#377eb8'), labels=c('discard', 'retain'),name='')
grid.arrange(as1,as2,ncol=2)
@


<<kswagex, fig.pos="H", fig.cap="Shell ages (annuli) by bed and year for District KSW. Note that there are no age samples from bed 1.",echo=FALSE, warning=FALSE ,fig.height=4, cache=TRUE, dev='png', dpi=300, eval=FALSE>>=
#ggplot(ksw.age, aes(annuli, Meat_Weight))+geom_point(alpha=.2,color='black')+facet_grid(Year~.)+
#   stat_smooth()+coord_cartesian(xlim=c(0,20))
#ggplot(ksw.age, aes(annuli, Meat_Weight, group=Year,color=Year,fill=Year))+geom_point(alpha=.2,color='black')+
#   stat_smooth()+coord_cartesian(xlim=c(0,20))


#ggplot(ksw.age, aes(Depth,annuli, group=Year,color=Year,fill=Year))+geom_point(alpha=.2,color='black')+stat_smooth()
#ggplot(ksw.age, aes(Depth,annuli, group=Bed,color=Bed,fill=Bed))+geom_point(alpha=.2,color='black')+stat_smooth(method='lm')
#ggplot(ksw.sh, aes(Depth,Shell_Height, group=Year,color=Year,fill=Year))+geom_point(alpha=.2,color='black')+stat_smooth(method='lm')
#ggplot(ksw.sh, aes(Depth,Shell_Height, group=Bed,color=Bed,fill=Bed))+geom_point(alpha=.2,color='black')+stat_smooth(method='lm')


#ggplot(ksw.age, aes(Depth,annuli, group=Year,color=Year,fill=Year))+geom_point(alpha=.2,color='black')+stat_smooth()
#ggplot(ksw.sh, aes(Shell_Height, Meat_Weight,group=Year,color=Year,fill=Year))+geom_point(alpha=.2,color='black')+stat_smooth(method='lm')
@

<<kswcrab, fig.pos="H", fig.cap="Estimated Tanner Crab and Pacific Halibut catch for District KSW.",echo=FALSE, warning=FALSE ,fig.height=4, cache=TRUE, dev='png', dpi=300, eval=TRUE>>=   
ksw.by <- merge(by, ksw, by=c('Fishery', 'District','ADFG', 'set_date', 'year', 'date', 'Year', 'vessel'))

a <- aggregate(Halibut_Count~year,data=subset(by, District=='KSW'), FUN=sum)
a1 <- aggregate(Tanner_Count~year,data=subset(by, District=='KSW'), FUN=sum)
a2 <- aggregate(King_Count~year,data=subset(by, District=='KSW'), FUN=sum)
b <- aggregate(Sample_Hrs~year,data=subset(by, District=='KSW'), FUN=sum)
c <- aggregate(Dredge_Hrs~year,data=ksw, FUN=sum)

d <- merge(a,b, by='year')
d <- merge(a1,d, by='year')
d <- merge(a2,d, by='year')
d <- merge(c,d, by='year')

d$hal <- d$Halibut_Count/d$Sample_Hrs*d$Dredge_Hrs
d$tan <- d$Tanner_Count/d$Sample_Hrs*d$Dredge_Hrs
d$king <- d$King_Count/d$Sample_Hrs*d$Dredge_Hrs

d <- d[,c(1,6,7)]
d<- melt(d, id.vars=c( 'year'))
ggplot(d, aes(year, value, color=variable, group=variable))+geom_line()+geom_point(size=3)+
    scale_color_discrete(name="species",
                         breaks=c("tan", "hal"),
                         labels=c("Tanner", "Halibut"))
@

<<kswdisc, fig.pos="H", fig.cap="Scallop estimated discard weight for District KSW.",echo=FALSE, warning=FALSE ,fig.height=4, cache=TRUE, dev='png', dpi=300, eval=TRUE>>=   
ksw.by <- merge(by, ksw, by=c('Fishery', 'District','ADFG', 'set_date', 'year', 'date', 'Year', 'vessel'))

a <- aggregate(Sample_Hrs~year,data=subset(by, District=='KSW'), FUN=sum)
a1 <- aggregate(Discard_Weight~year,data=subset(by, District=='KSW'), FUN=sum)
a2 <- aggregate(Broken_Weight~year,data=subset(by, District=='KSW'), FUN=sum)
a3 <- aggregate(Rem_Disc_Wt~year,data=subset(by, District=='KSW'), FUN=sum)
b <- aggregate(Dredge_Hrs~year,data=ksw, FUN=sum)
c <- aggregate(Round_Weight~year,data=ksw, FUN=sum)

d <- merge(a,a1, by='year')
d <- merge(d,a2, by='year')
d <- merge(d,a3, by='year')
d <- merge(b,d, by='year')
d <- merge(c,d, by='year')
d$wt <- d[,5]+d[,6]+d[,7]
d$disc <- d$wt/d$Sample_Hrs*d$Dredge_Hrs
d$per <- d$disc/d$Round_Weight*100
ggplot(d, aes(year, disc))+geom_line()+geom_point(size=3)+ylim(0, max(d$disc))+ylab('Scallop discard weight (lbs)')
    
@
\section{Dutch Harbor Area O}
\subsubsection{Fishery performance}
The 2014/15 Area O scallop fishery opened on July 1. 2014 with a GHL of 5,000 lb scallop meat. One vessel particpated in the fishery (Figure~\ref{fig:ovessel}) harvesting 5,160 lb scallop meat with a cpue of 70 lb meat/dredge hour (Table~\ref{table:o1}). 


\subsubsection{Size and age structure of catch}

Shell heights in 2014/15 show a strongly bimodal distribution with peaks at 110 and 160 mm, indicating a potential poor recruitment to the fishery next year. 
\subsubsection{Scallop discards and crab/halibut bycatch}

An estimated 1,037 Tanner Crab, and no Pacific Halibut were incidentically caught (Figure~\ref{fig:qcrab}). Estimated scallop discards were 3,916 lb (9.5\% of total round weight landed).

<<tablo, eval=FALSE, echo=FALSE>>=
a <- aggregate(Dredge_Hrs~year, data=o, FUN=sum)
b <- aggregate(Meat_Weight~year, data=o, FUN=sum)
c <- merge(a,b, by='year')
d <- aggregate(Haul_ID~year, data=o, FUN=length)
d <- merge(c,d, by='year')
d$cpue <- d$Meat_Weight/d$Dredge_Hrs
d
@

\begin{table}[H]
   \centering
   \caption{Area O catch summary for the 2014/15 season.}
   
   \label{table:o1}
   \begin{tabular}{lcccccc}
				& 		&  Catch 	& Dredge  	& Number  	&  		 \\ 
		Year	& GHL 	&(lb meat)  & (hours) 	& hauls  	& cpue$^a$\\ 
		\hline	
1993/94&   170,000&	38,731&	838&	&	46\\
1994/95&	170,000&	1,931&	81&		&24\\
1995/96&	170,000&	26,950&	1,047&	&	26\\
1996/97&	170,000&		&		&&\\
1997/98&	170,000&	5,790&	171&		&34\\
1998/99&	110,000&	46,432&	1,025&	&	45\\
1999/00&	110,000&	6,465&	273&		&24\\
2000/01&	closed&			&	&&\\
2001/02&	closed&			&	&&\\
2002/03&	10,000&	6,000&	184&&		33\\
2003/04&	closed&			&	&&\\
2004/05&	closed&			&	&&\\
2005/06&	closed&			&	&&\\
2006/07&	closed&			&	&&\\
2007/08&	closed&			&	&&\\
2008/09&	10,000&	10,040&	228&	&	44\\
2009/10&	10,000&	6,080&	103&	66&	59\\
2010/11&	10,000&	5,642&	83&	51&	68\\
2011/12&	10,000&	5,570&	77&	54&	73\\
2012/13&	5,000&	5,100&	64&	50&	79\\
2013/14&	5,000&	5,225&	56&	28&	94\\
2014/15&	5,000&	5,160&	73&	57&	70\\
		
		\hline	
		\multicolumn{3}{l}{$^a$lb scallop meat/dredge hour}	\\

	\end{tabular} 
\end{table}

<<o, fig.pos="H", fig.cap="Maps of Area O fishing locations by fishing year.",echo=FALSE, warning=FALSE ,fig.height=7, cache=TRUE, dev='png', dpi=300>>=
#######################
#O
#######################

#split by bed
o$bed = NA
o<-within(o,bed[Set_Lat > 53.5]<-1)
o<-within(o,bed[Set_Lat < 53.5]<-2)
o<-within(o,bed[Set_Lon < -168.4]<-4)

o$Bed <- factor(o$bed)
#ggplot(o,aes(Set_Lon, Set_Lat, color=Bed))+geom_point()
bvalues <- c('1'='#e41a1c','2'='#377eb8','4'='#238b45') 
bbreaks <- c('1', '2','4')


#remove incomplete data
o <- o[complete.cases(o),]

#map of sample locations

omap <- ggplot()+geom_polygon(data=ak,aes(long,lat,group=group),fill=8,color='black') +
   theme(panel.background=element_rect(fill='white')) + 
   xlab(expression(paste(Longitude^o,~'W'))) +
   ylab(expression(paste(Latitude^o,~'W'))) + 
   coord_map(xlim=c(min(o$Set_Lon,na.rm=T)-.5,max(o$Set_Lon,na.rm=T)+.5),
             ylim=c(min(o$Set_Lat,na.rm=T)-.5,max(o$Set_Lat,na.rm=T)+.5))

omap+geom_point(data=o, aes(Set_Lon,Set_Lat,color=Bed), alpha=.2)+facet_wrap(~ Year)+
   guides(colour = guide_legend(override.aes = list(alpha = 1)))+
   theme(legend.key = element_blank(),legend.position = c(0.1, 0.9),legend.background = 
            element_rect(fill = "#ffffffaa", colour = NA),legend.key.height=unit(.6,'line'))+
   scale_fill_manual(values=bvalues,breaks=bbreaks, name='Bed')+
   scale_color_manual(values=bvalues,breaks=bbreaks, name='Bed')
@

<<ocpue, fig.pos="H", fig.cap="Density and number of tows by bed and year for Area O cpue. The left pane shows the cpue distribution for all of the hauls, the right pane shows the number of hauls.",echo=FALSE, warning=FALSE ,fig.height=6, cache=TRUE, dev='png', dpi=300>>=
#RAW density and number of tows
m1 <- ggplot(o, aes(mwt.cpue,fill=Year,color=Year))+geom_density()+facet_grid(Bed~., scales='free_y')+xlab('log(cpue)')+
   scale_fill_manual(values=values,breaks=breaks, name='Year')+
   scale_color_manual(values=values,breaks=breaks, name='Year')+
   guides(colour = guide_legend(override.aes = list(alpha = 1)))+ 
   theme(legend.key = element_blank(),legend.position = c(0.15, 0.45),legend.background = 
            element_rect(fill = "#ffffffaa", colour = NA),legend.key.height=unit(.6,'line'))

m2 <- ggplot(o, aes(mwt.cpue,fill=Year,color=Year))+geom_histogram()+facet_grid(Bed~., scales='free_y')+xlab('log(cpue)')+
   scale_fill_manual(values=values,breaks=breaks, name='Year')+
   scale_color_manual(values=values,breaks=breaks, name='Year')+
   guides( fill=FALSE, color=FALSE)+ theme(legend.key = element_blank())
grid.arrange(m1,m2,ncol=2)
@


<<ofit,fig.pos="H", fig.cap="Density and number of tows by bed and year for Area O standardized cpue. Note the different scales for the y-axis. The left pane shows the cpue distribution for all of the hauls, the right pane shows the number of hauls.",echo=FALSE, warning=FALSE ,fig.height=6, cache=TRUE,dev='png', dpi=300>>=
#Model the CPUE

fit <- gam(mwt.cpue~s(Depth,k=4)+te(Set_Lon,Set_Lat)+Year+s(Bed, bs='re')+vessel-1, data=o, gamma=1.4)
#plot(kne$Bed,resid(fit))
o$fit <- fitted(fit)
f1 <- ggplot(o, aes(fit,fill=Year,color=Year))+geom_density()+facet_grid(Bed~., scales='free_y')+
   scale_fill_manual(values=values,breaks=breaks, name='Year')+
   scale_color_manual(values=values,breaks=breaks, name='Year')+
   guides(colour = guide_legend(override.aes = list(alpha = 1)))+ 
   theme(legend.key = element_blank(),legend.position = c(0.15, 0.4),legend.background = 
            element_rect(fill = "#ffffffaa", colour = NA),legend.key.height=unit(.6,'line'))

f2 <- ggplot(o, aes(fit,fill=Year,color=Year))+geom_histogram()+facet_grid(Bed~., scales='free_y')+
   scale_fill_manual(values=values,breaks=breaks, name='Year')+
   scale_color_manual(values=values,breaks=breaks, name='Year')+
   guides( fill=FALSE, color=FALSE)+ theme(legend.key = element_blank())
grid.arrange(f1,f2,ncol=2)
@


<<ovessel, fig.pos="H", fig.cap="Annual vessel effect from model fit, Area O.",echo=FALSE, warning=FALSE ,fig.height=4, cache=TRUE,dev='png',dpi=300, dpi=300>>=
#Model the CPUE
#ggplot(o, aes(Year,fit, fill=Bed))+geom_boxplot()
#ggplot(o, aes(vessel,fit, fill=Bed))+geom_boxplot()
ggplot(o, aes(Year,fit, fill=vessel))+geom_boxplot(width=.35)
@

<<ofit2, fig.pos="H", fig.cap="Standardized and raw CPUE by year and bed for Area O. Standardized cpue have bootstrap estimated 95\\% confidence levels, the raw cpue have normal approximate 95\\% confidence levels.",echo=FALSE, warning=FALSE ,fig.height=4, cache=TRUE,dev='png', dpi=300>>=
r1 <- ggplot(o, aes(year, fit, color=Bed, fill=Bed))+stat_summary(fun.data=mean_cl_boot, geom='smooth')+
   scale_fill_manual(values = c('1'='#a6bddb40','2'='#998ec340','4'='#fee0b660'),
         breaks= c('1', '2','4'), name='bed')+
   scale_color_manual(values = c('1'='#54278840','2'='#998ec340', '4'='#fee0b680'),
         breaks= c('1', '2','4'), name='bed')+ 
   theme(legend.key = element_blank(),legend.position = c(0.75, 0.1),legend.background = 
            element_rect(fill = "#ffffffaa", colour = NA),legend.key.height=unit(.6,'line'))+ylab('standardized cpue')

a <- aggregate(mwt.cpue~year+Bed,data=o, FUN=mean)
b <- aggregate(mwt.cpue~year+Bed,data=o, FUN=sd)
names(b) <- c('year','Bed', 'sd')
c <- aggregate(mwt.cpue~year+Bed,data=o, FUN=length)
names(c) <- c('year','Bed', 'n')
d <- merge(a,b, by=c('year','Bed'))
d <- merge(c,d, by=c('year','Bed'))
d$lci <- d$mwt.cpue-2*d$sd/sqrt(d$n)
d$uci <- d$mwt.cpue+2*d$sd/sqrt(d$n)
r2 <- ggplot(d, aes(year,mwt.cpue, fill=Bed))+geom_line(aes(color=Bed))+
   geom_ribbon(aes(ymin=lci, ymax=uci))+
   scale_fill_manual(values = c('1'='#a6bddb40','2'='#998ec340','4'='#fee0b660'),
         breaks= c('1', '2','4'), name='bed')+
   scale_color_manual(values = c('1'='#54278840','2'='#998ec340', '4'='#fee0b680'),
         breaks= c('1', '2','4'), name='bed')+ 
      guides( fill=FALSE, color=FALSE)+ theme(legend.key = element_blank())+ylab('raw cpue')
grid.arrange(r1,r2,ncol=2)
@

<<osh, fig.pos="H", fig.cap="Shell heights by bed and year for Area O. Note the different scales for the y-axis. The left pane shows the shell heights distribution for all of the hauls, the right pane shows the number of shells sampled at a given height.",echo=FALSE, warning=FALSE ,fig.height=6, cache=TRUE,dev='png', dpi=300>>=
#Shell heights
o.sh <- merge(o,sh,by=c('Fishery', 'District','Haul_ID','ADFG'))

#SH by year
s1 <- ggplot(o.sh, aes(Shell_Height, fill=Year,color=Year))+geom_density()+facet_grid(Bed~.)+
   scale_fill_manual(values=values,breaks=breaks, name='Year')+
   scale_color_manual(values=values,breaks=breaks, name='Year')+
   guides(colour = guide_legend(override.aes = list(alpha = 1)))+ 
   theme(legend.key = element_blank(),legend.position = c(0.15, 0.5),legend.background = 
            element_rect(fill = "#ffffffaa", colour = NA),legend.key.height=unit(.6,'line'))

s2 <- ggplot(o.sh, aes(Shell_Height, fill=Year,color=Year))+geom_histogram()+facet_grid(Bed~., scales='free_y')+
   scale_fill_manual(values=values,breaks=breaks, name='Year')+
   scale_color_manual(values=values,breaks=breaks, name='Year')+
   guides(colour = guide_legend(override.aes = list(alpha = 1)))+
   guides( fill=FALSE, color=FALSE)+ theme(legend.key = element_blank())
grid.arrange(s1,s2,ncol=2)
@


<<osh14, fig.pos="H", fig.cap="Retained and discarded shell heights by bed for Area O in 2014. Note discards were only recorded for bed 4. The left pane shows the shell heights distribution for all of the hauls, the right pane shows the number of shells sampled at a given height.",echo=FALSE, warning=FALSE ,fig.height=4, cache=TRUE,dev='png', dpi=300>>=
#SH by bed
s1 <- ggplot(subset(o.sh, year==2014), aes(Shell_Height, fill=Rtnd_Disc,color=Rtnd_Disc))+geom_density(alpha=.2)+
   scale_color_manual( values=c('D'='#e41a1c','R'='#377eb8'), labels=c('discard', 'retain'),name='')+
   scale_fill_manual( values=c('D'='#e41a1c','R'='#377eb8'), labels=c('discard', 'retain'),name='')+ 
   theme(legend.key = element_blank(),legend.position = c(0.15, 0.6),legend.background = 
   element_rect(fill = "#ffffffaa", colour = NA),legend.key.height=unit(.6,'line'))
s2 <- ggplot(subset(o.sh, year==2014), aes(Shell_Height, fill=Rtnd_Disc,color=Rtnd_Disc))+geom_histogram(alpha=.2)+
   scale_color_manual( values=c('D'='#e41a1c','R'='#377eb8'), labels=c('discard', 'retain'),name='')+
   scale_fill_manual( values=c('D'='#e41a1c','R'='#377eb8'), labels=c('discard', 'retain'),name='')+
   guides( fill=FALSE, color=FALSE)+ theme(legend.key = element_blank())
grid.arrange(s1,s2,ncol=2)
@


<<osh3, fig.pos="H", fig.cap="Shell heights by year, all beds combined, for Area O. The left pane shows the shell heights distribution for all of the hauls, the right pane shows the number of shells sampled at a given height.",echo=FALSE, warning=FALSE ,fig.height=8.5, cache=TRUE,dev='png', dpi=300>>=

#SH by year
s1 <- ggplot(o.sh, aes(Shell_Height, fill=Rtnd_Disc,color=Rtnd_Disc))+geom_density(alpha=.2)+facet_grid(Year~.)+
   scale_color_manual( values=c('D'='#e41a1c','R'='#377eb8'), labels=c('discard', 'retain'),name='')+
   scale_fill_manual( values=c('D'='#e41a1c','R'='#377eb8'), labels=c('discard', 'retain'),name='')+ 
   theme(legend.key = element_blank(),legend.position = c(0.2, 0.25),legend.background = 
   element_rect(fill = "#ffffffaa", colour = NA),legend.key.height=unit(.6,'line'))

s2 <- ggplot(o.sh, aes(Shell_Height, fill=Rtnd_Disc,color=Rtnd_Disc))+geom_histogram(alpha=.2)+facet_grid(Year~.)+
   scale_color_manual( values=c('D'='#e41a1c','R'='#377eb8'), labels=c('discard', 'retain'),name='')+
   scale_fill_manual( values=c('D'='#e41a1c','R'='#377eb8'), labels=c('discard', 'retain'),name='')+
   guides( fill=FALSE, color=FALSE)+ theme(legend.key = element_blank())
grid.arrange(s1,s2,ncol=2)
@


<<oage, fig.pos="H", fig.cap="Shell ages (annuli) by bed and year for Area O.",echo=FALSE, warning=FALSE,error=FALSE ,fig.height=4, cache=TRUE,dev='png', dpi=300>>=   
#Ages

o.age <- merge(o, ages,by=c('Fishery', 'District','Haul_ID','ADFG', 'set_date', 'year', 'date', 'Year'))


#age by year
a1 <- ggplot(o.age, aes(annuli, fill=Year, color=Year))+geom_density()+facet_grid(Bed~., scales='free_y')+
   scale_fill_manual(values=values, breaks=breaks, name='Year')+
   scale_color_manual(values=values,  breaks=breaks, name='Year')+
   guides(colour = guide_legend(override.aes = list(alpha = 1)))+guides(colour = guide_legend(override.aes = list(alpha = 1)))+
   guides( fill=FALSE, color=FALSE)+ theme(legend.key = element_blank())
a2 <- ggplot(o.age, aes(annuli, fill=Year, color=Year))+geom_histogram()+facet_grid(Bed~., scales='free_y')+
   scale_fill_manual(values=values, breaks=breaks, name='Year')+
   scale_color_manual(values=values,  breaks=breaks, name='Year')+ 
   theme(legend.key = element_blank(),legend.position = c(0.75, 0.75),legend.background = 
            element_rect(fill = "#ffffffaa", colour = NA),legend.key.height=unit(.6,'line'))
   
grid.arrange(a1,a2,ncol=2)
@

<<oage2, fig.pos="H", fig.cap="Shell ages (annuli) by year for Area O.",echo=FALSE, warning=FALSE ,fig.height=8.5, cache=TRUE, dev='png', dpi=300>>=                               
 #Ages
                                           
                        
#age by year
a1 <- ggplot(o.age, aes(annuli,fill=Rtnd_Disc))+geom_density(alpha=.3)+facet_grid(Year~., scale='free_y')+
   guides(colour = guide_legend(override.aes = list(alpha = 1)))+ 
   theme(legend.key = element_blank(),legend.position = c(0.75, 0.08),legend.background = 
            element_rect(fill = "#ffffffaa", colour = NA),legend.key.height=unit(.6,'line'))
a2 <- ggplot(o.age, aes(annuli,fill=Rtnd_Disc))+geom_histogram(color='white')+facet_grid(Year~.)+
      guides(colour = guide_legend(override.aes = list(alpha = 1)))+
   guides( fill=FALSE, color=FALSE)+ theme(legend.key = element_blank())
grid.arrange(a1,a2,ncol=2)
@   

<<oagesh, fig.pos="H", fig.cap="Comparison between shells measured for height and shell height of aged scallops by year for Area O. The left pane shows the density of all shell heights collected (blue) and the density of shell heights from ages shells (gray). The right pane shows the densities of shell heights from retained shells, discarded shell, and aged shells.",echo=FALSE, warning=FALSE ,error=FALSE,fig.height=8.5, cache=TRUE,message=FALSE, dev='png', dpi=300>>=

#ggplot(o.age, aes(annuli))+geom_histogram(alpha=.2)+facet_grid(Year~.)
#omap+geom_point(data=subset(o.age, year<2012),aes(Set_Lon,Set_Lat,color=annuli,width=1.2),alpha=.2) +
#   guides(colour = guide_legend(override.aes = list(alpha = 1)))+facet_grid(Year~.)+
#   scale_colour_gradientn(colours =rainbow(5))

#omap+geom_point(data=subset(o.age, year>2011),aes(Set_Lon,Set_Lat,color=annuli,width=1.2),alpha=.2) +
#   guides(colour = guide_legend(override.aes = list(alpha = 1)))+facet_grid(Year~.)+
#   scale_colour_gradientn(colours=rainbow(5))

#ggplot(o.age, aes(annuli))+geom_density(alpha=.2,fill=4)+facet_grid(Year~.)
#ggplot(o.age, aes(annuli))+geom_histogram(alpha=.2,color='black', fill=4)+facet_grid(Year~.)

#difference between shell height samples and shell height ages
as1 <- ggplot(o.age, aes(Shell_Height))+geom_density(alpha=.2,fill='black')+facet_grid(Year~.)+
   geom_density(data=o.sh, aes(Shell_Height), alpha=.2,fill=4)

as2 <- ggplot(o.age, aes(Shell_Height))+geom_density(alpha=.2,fill='black')+facet_grid(Year~.)+
   geom_density(data=o.sh, aes(Shell_Height, fill=Rtnd_Disc), alpha=.2)+guides(colour = guide_legend(override.aes = list(alpha = 1)))+ 
   theme(legend.key = element_blank(),legend.position = c(0.15, 0.23),legend.background = 
            element_rect(fill = "#ffffffaa", colour = NA),legend.key.height=unit(.6,'line'))+
   scale_fill_manual( values=c('D'='#e41a1c','R'='#377eb8'), labels=c('discard', 'retain'),name='')
grid.arrange(as1,as2,ncol=2)
@

<<oagex, echo=FALSE, warning=FALSE ,dev='png', dpi=300>>=
#ggplot(o.age, aes(annuli, Meat_Weight))+geom_point(alpha=.2,color='black')+facet_grid(Year~.)+
   #stat_smooth()+coord_cartesian(xlim=c(0,20))
#ggplot(o.age, aes(annuli, Meat_Weight, group=Year,color=Year,fill=Year))+geom_point(alpha=.2,color='black')+
   #stat_smooth()+coord_cartesian(xlim=c(0,20))


#ggplot(o.age, aes(Depth,annuli, group=Year,color=Year,fill=Year))+geom_point(alpha=.2,color='black')+stat_smooth()
#ggplot(o.age, aes(Depth,annuli, group=Bed,color=Bed,fill=Bed))+geom_point(alpha=.2,color='black')+stat_smooth(method='lm')
#ggplot(o.sh, aes(Depth,Shell_Height, group=Year,color=Year,fill=Year))+geom_point(alpha=.2,color='black')+stat_smooth(method='lm')
#ggplot(o.sh, aes(Depth,Shell_Height, group=Bed,color=Bed,fill=Bed))+geom_point(alpha=.2,color='black')+stat_smooth(method='lm')


#ggplot(o.age, aes(Depth,annuli, group=Year))+geom_point(alpha=.2,color='black')+stat_smooth()
#ggplot(o.sh, aes(Shell_Height, Meat_Weight,group=Year,color=Year,fill=Year))+geom_point(alpha=.2,color='black')+stat_smooth(method='lm')
@

<<ocrab, fig.pos="H", fig.cap="Estimated Tanner Crab and Pacific Halibut catch for Area O.",echo=FALSE, warning=FALSE ,fig.height=4, cache=TRUE, dev='png', dpi=300, eval=TRUE>>=   
o.by <- merge(by, o, by=c('Fishery', 'District','ADFG', 'set_date', 'year', 'date', 'Year', 'vessel'))

a <- aggregate(Halibut_Count~year,data=subset(by, District=='O'), FUN=sum)
a1 <- aggregate(Tanner_Count~year,data=subset(by, District=='O'), FUN=sum)
b <- aggregate(Sample_Hrs~year,data=subset(by, District=='O'), FUN=sum)
c <- aggregate(Dredge_Hrs~year,data=o, FUN=sum)

d <- merge(a,b, by='year')
d <- merge(a1,d, by='year')
d <- merge(c,d, by='year')

d$hal <- d$Halibut_Count/d$Sample_Hrs*d$Dredge_Hrs
d$tan <- d$Tanner_Count/d$Sample_Hrs*d$Dredge_Hrs

d <- d[,c(1,6,7)]
d<- melt(d, id.vars=c( 'year'))
ggplot(d, aes(year, value, color=variable, group=variable))+geom_line()+geom_point(size=3)+
    scale_color_discrete(name="species",
                         breaks=c("tan", "hal"),
                         labels=c("Tanner", "Halibut"))
@

<<odisc, fig.pos="H", fig.cap="Scallop estimated discard weight for Area O.",echo=FALSE, warning=FALSE ,fig.height=4, cache=TRUE, dev='png', dpi=300, eval=TRUE>>=   
o.by <- merge(by, o, by=c('Fishery', 'District','ADFG', 'set_date', 'year', 'date', 'Year', 'vessel'))

a <- aggregate(Sample_Hrs~year,data=subset(by, District=='O'), FUN=sum)
a1 <- aggregate(Discard_Weight~year,data=subset(by, District=='O'), FUN=sum)
a2 <- aggregate(Broken_Weight~year,data=subset(by, District=='O'), FUN=sum)
a3 <- aggregate(Rem_Disc_Wt~year,data=subset(by, District=='O'), FUN=sum)
b <- aggregate(Dredge_Hrs~year,data=o, FUN=sum)
c <- aggregate(Round_Weight~year,data=o, FUN=sum)

d <- merge(a,a1, by='year')
d <- merge(d,a2, by='year')
d <- merge(d,a3, by='year')
d <- merge(b,d, by='year')
d <- merge(c,d, by='year')
d$wt <- d[,5]+d[,6]+d[,7]
d$disc <- d$wt/d$Sample_Hrs*d$Dredge_Hrs
d$per <- d$disc/d$Round_Weight*100
ggplot(d, aes(year, disc))+geom_line()+geom_point(size=3)+ylim(0, max(d$disc))+ylab('Scallop discard weight (lbs)')
    
@

\section{Bering Sea Area Q}

\subsubsection{Fishery performance}
The 2014/15 Area Q scallop fishery opened on July 1. 2014 with a GHL of 15,000 lb scallop meat. Two vessels particpated in the fishery (Figure~\ref{fig:qvessel}) harvesting 12,445 lb scallop meat with a cpue of 24 lb meat/dredge hour (Table~\ref{table:q1}). Catch per unit effort decreased substantially in the 2014/15 season.


\subsubsection{Size and age structure of catch}

The catch in 2014/15 was dominated by older larger individuals with few young shell scallops caught. Smaller, younger scallops were poorly represented in the catch.

\subsubsection{Scallop discards and crab/halibut bycatch}

An estimated 24,943 Tanner Crab, a substantial decrease from the previous year, 9,868 Opilio Crab, 19 Pacific Halibut and 223 King Crab were incidentically caught (Figure~\ref{fig:qcrab}). Estimated scallop discards were 7,961 lb (3.5\% of total round weight landed).

<<tablq, eval=FALSE, echo=FALSE>>=
a <- aggregate(Dredge_Hrs~year, data=q, FUN=sum)
b <- aggregate(Round_Weight~year, data=q, FUN=sum)
c <- merge(a,b, by='year')
d <- aggregate(Haul_ID~year, data=q, FUN=length)
d <- merge(c,d, by='year')
d$cpue <- d$Round_Weight/d$Dredge_Hrs
d
@

\begin{table}[H]
   \centering
   \caption{Area Q catch summary for the 2014/15 season.}
   
	\label{table:q1}
	\begin{tabular}{lrrrrcc}
		& 		&  Catch 	& Dredge  	& Number  	&  		 \\ 
		Year	& GHL 	&(lb meat)  & (hours) 	& hauls  	& cpue$^a$\\ 
		\hline	
		1993/94&		&	284,414&		5,764&		3,326&	49\\
		1994/95&		&	505,439	&	11,113&		6,508	&45\\
		1995/96&	closed&			&	&& \\
		1996/97&	600,000&		150,295&		2,313&		951&	65\\
		1997/98&	600,000&		97,002&		2,246&		1,280	&43\\
		1998/99	&	400,000&		96,795&		2,319&		1,178	&42\\
		1999/00	&	400,000&		164,481&		3,294&		1,514&	50\\
		2000/01	&	200,000&		205,520&		3,355&		1,564&	61\\
		2001/02	&	200,000&		140,365&		3,072&		1,401&	46\\
		2002/03	&	105,000&		90,562&		2,038&		1,010&	44\\
		2003/04	&	105,000&		42,590&		1,020&		517&	41\\
		2004/05	&	50,000&		10,050&		275&		145&	37\\
		2005/06	&	50,000&		23,241&		602	&	303&	39\\
		2006/07	&	50,000&		48,775&		1,138&		583&	43\\
		2007/08	&	50,000&		50,299&		1,083&		540&	46\\
		2008/09	&	50,000&		49,995&		960	&	642&	52\\
		2009/10	&	50,000&		48,885&		1,274&		726&	38\\
		2010/11	&	50,000&		50,099&		972	&	597&	52\\
		2011/12	&	50,000&		50,275&		984	&	626&	51\\
		2012/13	&	50,000&		50,045&		943	&	695&	53\\
		2013/14	&	50,000&		49,989&		1,086&		719&	46\\
		2014/15 & 50,000 & 12,445$^b$ & 525 & 330 & 24\\
		
		
		\hline	
		\multicolumn{3}{l}{$^a$lb scallop meat/dredge hour}	\\
   	\multicolumn{3}{l}{$^b$reduced due to "weak meat"}	\\
      \end{tabular} 
\end{table}
<<q, fig.pos="H", fig.cap="Maps of Area Q fishing locations by fishing year.",echo=FALSE, warning=FALSE ,fig.height=6, cache=TRUE,dev='png', dpi=300>>=
#######################
#Q
#######################
#excluded samples outside of the main bed
q <- subset(q,Set_Lon>-166)
#remove incomplete data
q <- q[complete.cases(q),]

#map of sample locations

qmap <- ggplot()+geom_polygon(data=ak,aes(long,lat,group=group, color=Bed),fill=8,color='black') +
   theme(panel.background=element_rect(fill='white')) + 
   xlab(expression(paste(Longitude^o,~'W'))) +
   ylab(expression(paste(Latitude^o,~'W'))) + 
   coord_map(xlim=c(-166.2,max(q$Set_Lon,na.rm=T)+.5),
             ylim=c(min(q$Set_Lat,na.rm=T)-.5,56.2))

qmap+geom_point(data=q, aes(Set_Lon,Set_Lat), alpha=.2)+facet_wrap(~ Year)+
   guides(colour = guide_legend(override.aes = list(alpha = 1)))+
   theme(legend.key = element_blank(),legend.position = c(0.1, 0.9),legend.background = 
            element_rect(fill = "#ffffffaa", colour = NA),legend.key.height=unit(.6,'line'))
@

<<qcpue, fig.pos="H", fig.cap="Density and number of tows by bed and year for Area Q cpue.",echo=FALSE, warning=FALSE ,fig.height=4, cache=TRUE, dev='png', dpi=300>>=
#RAW density and number of tows
m1 <- ggplot(q, aes(mwt.cpue,fill=Year,color=Year))+geom_density()+xlab('log(cpue)')+
   scale_fill_manual(values=values,breaks=breaks, name='Year')+
   scale_color_manual(values=values,breaks=breaks, name='Year')+
   guides(colour = guide_legend(override.aes = list(alpha = 1)))+ 
   theme(legend.key = element_blank(),legend.position = c(0.65, 0.45),legend.background = 
            element_rect(fill = "#ffffffaa", colour = NA),legend.key.height=unit(.6,'line'))

m2 <- ggplot(q, aes(mwt.cpue,fill=Year,color=Year))+geom_histogram()+xlab('log(cpue)')+
   scale_fill_manual(values=values,breaks=breaks, name='Year')+
   scale_color_manual(values=values,breaks=breaks, name='Year')+
   guides( fill=FALSE, color=FALSE)+ theme(legend.key = element_blank())
grid.arrange(m1,m2,ncol=2)
@

<<qfit,fig.pos="H", fig.cap="Density and number of tows by bed and year for Area Q standardized cpue.",echo=FALSE, warning=FALSE ,fig.height=4, cache=TRUE, dev='png', dpi=300>>=
#Model the CPUE

fit <- gam(mwt.cpue~s(Depth,k=4)+te(Set_Lon,Set_Lat)+Year+vessel-1, data=q, gamma=1.4)
#plot(kne$Bed,resid(fit))
q$fit <- fitted(fit)
f1 <- ggplot(q, aes(fit,fill=Year,color=Year))+geom_density()+
   scale_fill_manual(values=values,breaks=breaks, name='Year')+
   scale_color_manual(values=values,breaks=breaks, name='Year')+
   guides(colour = guide_legend(override.aes = list(alpha = 1)))+ 
   theme(legend.key = element_blank(),legend.position = c(0.15, 0.4),legend.background = 
            element_rect(fill = "#ffffffaa", colour = NA),legend.key.height=unit(.6,'line'))

f2 <- ggplot(q, aes(fit,fill=Year,color=Year))+geom_histogram()+
   scale_fill_manual(values=values,breaks=breaks, name='Year')+
   scale_color_manual(values=values,breaks=breaks, name='Year')+
   guides( fill=FALSE, color=FALSE)+ theme(legend.key = element_blank())
grid.arrange(f1,f2,ncol=2)
@


<<qvessel,fig.pos="H", fig.cap="Annual vessel effect from model fit, Area Q.",echo=FALSE, warning=FALSE ,fig.height=4, cache=TRUE,dev='png',dpi=300>>=
#Model the CPUE
#ggplot(q, aes(Year,fit, fill=Bed))+geom_boxplot()
#ggplot(q, aes(vessel,fit, fill=Bed))+geom_boxplot()
ggplot(q, aes(Year,fit, fill=vessel))+geom_boxplot(width=.35)
@

<<qfit2, fig.pos="H", fig.cap="Standardized and raw CPUE by year and bed for Area Q. Standardized cpue have bootstrap estimated 95\\% confidence levels, the raw cpue have normal approximate 95\\% confidence levels.",echo=FALSE, warning=FALSE ,fig.height=4, cache=TRUE, dev='png', dpi=300>>=
r1 <- ggplot(q, aes(year, fit))+stat_summary(fun.data=mean_cl_boot, geom='smooth')+coord_cartesian(ylim=c(3.3,4.1))+ylab('standardized cpue')


a <- aggregate(mwt.cpue~year,data=q, FUN=mean)
b <- aggregate(mwt.cpue~year,data=q, FUN=sd)
names(b) <- c('year', 'sd')
c <- aggregate(mwt.cpue~year,data=q, FUN=length)
names(c) <- c('year', 'n')
d <- merge(a,b, by=c('year'))
d <- merge(c,d, by=c('year'))
d$lci <- d$mwt.cpue-2*d$sd/sqrt(d$n)
d$uci <- d$mwt.cpue+2*d$sd/sqrt(d$n)
r2 <- ggplot(d, aes(year,mwt.cpue))+geom_line()+
   geom_ribbon(aes(ymin=lci, ymax=uci),alpha=.2)+coord_cartesian(ylim=c(3.3,4.1))+ylab('raw cpue')
grid.arrange(r1,r2,ncol=2)
@

<<qsh, fig.pos="H", fig.cap="Shell heights by bed and year for Area Q. The left pane shows the shell heights distribution for all of the hauls, the right pane shows the number of shells sampled at a given height.",echo=FALSE, warning=FALSE ,fig.height=4, cache=TRUE,dev='png', dpi=300>>=
#Shell heights
q.sh <- merge(q,sh,by=c('Fishery', 'District','Haul_ID','ADFG'))

#SH by year
s1 <- ggplot(q.sh, aes(Shell_Height, fill=Year,color=Year))+geom_density()+
   scale_fill_manual(values=values,breaks=breaks, name='Year')+
   scale_color_manual(values=values,breaks=breaks, name='Year')+
   guides(colour = guide_legend(override.aes = list(alpha = 1)))+ 
   theme(legend.key = element_blank(),legend.position = c(0.15, 0.5),legend.background = 
            element_rect(fill = "#ffffffaa", colour = NA),legend.key.height=unit(.6,'line'))

s2 <- ggplot(q.sh, aes(Shell_Height, fill=Year,color=Year))+geom_histogram()+
   scale_fill_manual(values=values,breaks=breaks, name='Year')+
   scale_color_manual(values=values,breaks=breaks, name='Year')+
   guides(colour = guide_legend(override.aes = list(alpha = 1)))+
   guides( fill=FALSE, color=FALSE)+ theme(legend.key = element_blank())
grid.arrange(s1,s2,ncol=2)
@

<<qsh14, fig.pos="H", fig.cap="Retained and discarded shell heights by bed for Area Q in 2014. The left pane shows the shell heights distribution for all of the hauls, the right pane shows the number of shells sampled at a given height.",echo=FALSE, warning=FALSE ,fig.height=4, cache=TRUE, dev='png', dpi=300>>=
#SH by bed
s1 <- ggplot(subset(q.sh, year==2014), aes(Shell_Height, fill=Rtnd_Disc,color=Rtnd_Disc))+geom_density(alpha=.2)+
   scale_color_manual( values=c('D'='#e41a1c','R'='#377eb8'), labels=c('discard', 'retain'),name='')+
   scale_fill_manual( values=c('D'='#e41a1c','R'='#377eb8'), labels=c('discard', 'retain'),name='')+ 
   theme(legend.key = element_blank(),legend.position = c(0.15, 0.4),legend.background = 
   element_rect(fill = "#ffffffaa", colour = NA),legend.key.height=unit(.6,'line'))
s2 <- ggplot(subset(q.sh, year==2014), aes(Shell_Height, fill=Rtnd_Disc,color=Rtnd_Disc))+geom_histogram(alpha=.2)+
   scale_color_manual( values=c('D'='#e41a1c','R'='#377eb8'), labels=c('discard', 'retain'),name='')+
   scale_fill_manual( values=c('D'='#e41a1c','R'='#377eb8'), labels=c('discard', 'retain'),name='')+
   guides( fill=FALSE, color=FALSE)+ theme(legend.key = element_blank())
grid.arrange(s1,s2,ncol=2)
@


<<qsh3, fig.pos="H", fig.cap="Shell heights by year for Area Q. The left pane shows the shell heights distribution for all of the hauls, the right pane shows the number of shells sampled at a given height.",echo=FALSE, warning=FALSE ,fig.height=8.5, cache=TRUE,dev='png', dpi=300>>=

#SH by year
s1 <- ggplot(q.sh, aes(Shell_Height, fill=Rtnd_Disc,color=Rtnd_Disc))+geom_density(alpha=.2)+facet_grid(Year~.)+
   scale_color_manual( values=c('D'='#e41a1c','R'='#377eb8'), labels=c('discard', 'retain'),name='')+
   scale_fill_manual( values=c('D'='#e41a1c','R'='#377eb8'), labels=c('discard', 'retain'),name='')+ 
   theme(legend.key = element_blank(),legend.position = c(0.2, 0.25),legend.background = 
   element_rect(fill = "#ffffffaa", colour = NA),legend.key.height=unit(.6,'line'))

s2 <- ggplot(q.sh, aes(Shell_Height, fill=Rtnd_Disc,color=Rtnd_Disc))+geom_histogram(alpha=.2)+facet_grid(Year~.)+
   scale_color_manual( values=c('D'='#e41a1c','R'='#377eb8'), labels=c('discard', 'retain'),name='')+
   scale_fill_manual( values=c('D'='#e41a1c','R'='#377eb8'), labels=c('discard', 'retain'),name='')+
   guides( fill=FALSE, color=FALSE)+ theme(legend.key = element_blank())
grid.arrange(s1,s2,ncol=2)
@



<<qage, fig.pos="H", fig.cap="Shell ages (annuli) by bed and year for Area Q. ",echo=FALSE, warning=FALSE ,fig.height=4, cache=TRUE, dev='png', dpi=300>>=   
#Ages

q.age <- merge(q, ages,by=c('Fishery', 'District','Haul_ID','ADFG', 'set_date', 'year', 'date', 'Year'))


#age by year
a1 <- ggplot(q.age, aes(annuli, fill=Year, color=Year))+geom_density()+
   scale_fill_manual(values=values, breaks=breaks, name='Year')+
   scale_color_manual(values=values,  breaks=breaks, name='Year')+
   guides(colour = guide_legend(override.aes = list(alpha = 1)))+guides(colour = guide_legend(override.aes = list(alpha = 1)))+
   guides( fill=FALSE, color=FALSE)+ theme(legend.key = element_blank())
a2 <- ggplot(q.age, aes(annuli, fill=Year, color=Year))+geom_histogram()+
   scale_fill_manual(values=values, breaks=breaks, name='Year')+
   scale_color_manual(values=values,  breaks=breaks, name='Year')+ 
   theme(legend.key = element_blank(),legend.position = c(0.75, 0.75),legend.background = 
            element_rect(fill = "#ffffffaa", colour = NA),legend.key.height=unit(.6,'line'))
   
grid.arrange(a1,a2,ncol=2)
@

<<qage2, fig.pos="H", fig.cap="Shell ages (annuli) by bed and year for Area Q.",echo=FALSE, warning=FALSE ,fig.height=8.5, cache=TRUE, dev='png', dpi=300>>=                               
 #Ages
                                           
                        
#age by year
a1 <- ggplot(q.age, aes(annuli,fill=Rtnd_Disc))+geom_density()+facet_grid(Year~., scale='free_y')+
   guides(colour = guide_legend(override.aes = list(alpha = 1)))+ 
   theme(legend.key = element_blank(),legend.position = c(0.75, 0.08),legend.background = 
            element_rect(fill = "#ffffffaa", colour = NA),legend.key.height=unit(.6,'line'))
a2 <- ggplot(q.age, aes(annuli,fill=Rtnd_Disc))+geom_histogram(color='white')+facet_grid(Year~.)+
      guides(colour = guide_legend(override.aes = list(alpha = 1)))+
   guides( fill=FALSE, color=FALSE)+ theme(legend.key = element_blank())
grid.arrange(a1,a2,ncol=2)
@   

<<qagesh, fig.pos="H", fig.cap="Comparison between shells measured for height and shell height of aged scallops by year for Area Q. The left pane shows the density of all shell heights collected (blue) and the density of shell heights from ages shells (gray). The right pane shows the densities of shell heights from retained shells, discarded shell, and aged shells.",echo=FALSE, warning=FALSE ,fig.height=8.5, cache=TRUE, dev='png', dpi=300>>=

#qmap+geom_point(data=subset(q.age, year<2012),aes(Set_Lon,Set_Lat,color=annuli,width=1.2),alpha=.2) +
##   guides(colour = guide_legend(override.aes = list(alpha = 1)))+facet_grid(Year~.)+
#   scale_colour_gradientn(colours =rainbow(5))

#qmap+geom_point(data=subset(q.age, year>2011),aes(Set_Lon,Set_Lat,color=annuli,width=1.2),alpha=.2) +
#   guides(colour = guide_legend(override.aes = list(alpha = 1)))+facet_grid(Year~.)+
#   scale_colour_gradientn(colours=rainbow(5))

#ggplot(q.age, aes(annuli))+geom_density(alpha=.2,fill=4)+facet_grid(Year~.)
#ggplot(q.age, aes(annuli))+geom_histogram(alpha=.2,color='black', fill=4)+facet_grid(Year~.)

#difference between shell height samples and shell height ages
as1 <- ggplot(q.age, aes(Shell_Height))+geom_density(alpha=.2,fill='black')+facet_grid(Year~.)+
   geom_density(data=q.sh, aes(Shell_Height), alpha=.2,fill=4)

as2 <- ggplot(q.age, aes(Shell_Height))+geom_density(alpha=.2,fill='black')+facet_grid(Year~.)+
   geom_density(data=q.sh, aes(Shell_Height, fill=Rtnd_Disc), alpha=.2)+guides(colour = guide_legend(override.aes = list(alpha = 1)))+ 
   theme(legend.key = element_blank(),legend.position = c(0.15, 0.23),legend.background = 
            element_rect(fill = "#ffffffaa", colour = NA),legend.key.height=unit(.6,'line'))+
   scale_fill_manual( values=c('D'='#e41a1c','R'='#377eb8'), labels=c('discard', 'retain'),name='')
grid.arrange(as1,as2,ncol=2)
@

<<qagex, echo=FALSE, warning=FALSE,eval=FALSE, dev='png', dpi=300>>=
ggplot(q.age, aes(Shell_Height))+geom_density(alpha=.2,fill='black')+facet_grid(Year~.)+
   geom_density(data=q.sh, aes(Shell_Height), alpha=.2,fill=4)

ggplot(q.age, aes(Shell_Height))+geom_density(alpha=.2,fill='black')+facet_grid(Year~Bed, scales='free_y')+
   geom_density(data=q.sh, aes(Shell_Height, fill=Rtnd_Disc), alpha=.2)


ggplot(q.age, aes(annuli, Meat_Weight))+geom_point(alpha=.2,color='black')+facet_grid(Year~.)+
   stat_smooth()+coord_cartesian(xlim=c(0,20))
ggplot(q.age, aes(annuli, Meat_Weight, group=Year,color=Year,fill=Year))+geom_point(alpha=.2,color='black')+
   stat_smooth()+coord_cartesian(xlim=c(0,20))


ggplot(q.age, aes(Depth,annuli, group=Year,color=Year,fill=Year))+geom_point(alpha=.2,color='black')+stat_smooth()
ggplot(q.age, aes(Depth,annuli))+geom_point(alpha=.2,color='black')+stat_smooth(method='lm')
ggplot(q.sh, aes(Depth,Shell_Height, group=Year,color=Year,fill=Year))+geom_point(alpha=.2,color='black')+stat_smooth(method='lm')
ggplot(q.sh, aes(Depth,Shell_Height))+geom_point(alpha=.2,color='black')+stat_smooth(method='lm')


ggplot(q.age, aes(Depth,annuli, group=Year))+geom_point(alpha=.2,color='black')+stat_smooth()
ggplot(q.sh, aes(Shell_Height, Meat_Weight,group=Year,color=Year,fill=Year))+geom_point(alpha=.2,color='black')+stat_smooth(method='lm')
@

<<qcrab, fig.pos="H", fig.cap="Estimated Tanner Crab and Pacific Halibut catch for Area Q.",echo=FALSE, warning=FALSE ,fig.height=4, cache=TRUE, dev='png', dpi=300, eval=TRUE>>=   
q.by <- merge(by, q, by=c('Fishery', 'District','ADFG', 'set_date', 'year', 'date', 'Year', 'vessel'))

a <- aggregate(Halibut_Count~year,data=subset(by, District=='Q'), FUN=sum)
a1 <- aggregate(Tanner_Count~year,data=subset(by, District=='Q'), FUN=sum)
a2 <- aggregate(Opilio_Count~year,data=subset(by, District=='Q'), FUN=sum)
a3 <- aggregate(King_Count~year,data=subset(by, District=='Q'), FUN=sum)
b <- aggregate(Sample_Hrs~year,data=subset(by, District=='Q'), FUN=sum)
c <- aggregate(Dredge_Hrs~year,data=q, FUN=sum)

d <- merge(a,b, by='year')
d <- merge(a1,d, by='year')
d <- merge(a2,d, by='year')
d <- merge(a3,d, by='year')
d <- merge(c,d, by='year')

d$hal <- d$Halibut_Count/d$Sample_Hrs*d$Dredge_Hrs
d$tan <- d$Tanner_Count/d$Sample_Hrs*d$Dredge_Hrs
d$opi <- d$Opilio_Count/d$Sample_Hrs*d$Dredge_Hrs
d$king <- d$King_Count/d$Sample_Hrs*d$Dredge_Hrs

d <- d[,c(1,7:11)]
d<- melt(d, id.vars=c( 'year'))
ggplot(d, aes(year, value, color=variable, group=variable))+geom_line()+geom_point(size=3)+
    scale_color_discrete(name="species",
                         breaks=c("tan", "hal", "opi", 'king'),
                         labels=c("Tanner", "Halibut", "Opilio", "King"))
@


<<qdisc, fig.pos="H", fig.cap="Scallop estimated discard weight for Area Q.",echo=FALSE, warning=FALSE ,fig.height=4, cache=TRUE, dev='png', dpi=300, eval=TRUE>>=   
q.by <- merge(by, q, by=c('Fishery', 'District','ADFG', 'set_date', 'year', 'date', 'Year', 'vessel'))

a <- aggregate(Sample_Hrs~year,data=subset(by, District=='Q'), FUN=sum)
a1 <- aggregate(Discard_Weight~year,data=subset(by, District=='Q'), FUN=sum)
a2 <- aggregate(Broken_Weight~year,data=subset(by, District=='Q'), FUN=sum)
a3 <- aggregate(Rem_Disc_Wt~year,data=subset(by, District=='Q'), FUN=sum)
b <- aggregate(Dredge_Hrs~year,data=q, FUN=sum)
c <- aggregate(Round_Weight~year,data=q, FUN=sum)

d <- merge(a,a1, by='year')
d <- merge(d,a2, by='year')
d <- merge(d,a3, by='year')
d <- merge(b,d, by='year')
d <- merge(c,d, by='year')
d$wt <- d[,5]+d[,6]+d[,7]
d$disc <- d$wt/d$Sample_Hrs*d$Dredge_Hrs
d$per <- d$disc/d$Round_Weight*100
ggplot(d, aes(year, disc))+geom_line()+geom_point(size=3)+ylim(0, max(d$disc))+ylab('Scallop discard weight (lbs)')
    
@













\section{Unimak Bight Exploratory Fishery Area M}
\subsubsection{Fishery performance}
The 2014/15 Area M scallop fishery opened on July 1. 2014 with a GHL of 15,000 lb scallop meat. Two vessels particpated in the fishery (Figure~\ref{fig:mvessel}) harvesting 15,000 lb scallop meat with a cpue of 53 lb meat/dredge hour (Table~\ref{table:m1}). 


\subsubsection{Size and age structure of catch}

Shell heights and ages have been similar from 2012-2014. There is a reduction in the bimodal distribution in retained shell heights as the larger shelled individuals are removed from the population.

\subsubsection{Scallop discards and crab/halibut bycatch}

An estimated 13,914 Tanner Crab, a substantial increase from previous years, and 51 Pacific Halibut were incidentically caught (Figure~\ref{fig:kswcrab}). Estimated scallop discards were 19,029 lb (8.3\% of total round weight landed).

<<tablm, eval=FALSE, echo=FALSE>>=
a <- aggregate(Dredge_Hrs~year, data=m, FUN=sum)
b <- aggregate(Meat_Weight~year, data=m, FUN=sum)
c <- merge(a,b, by='year')
d <- aggregate(Haul_ID~year, data=m, FUN=length)
d <- merge(c,d, by='year')
d$cpue <- d$Meat_Weight/d$Dredge_Hrs
d
@

\begin{table}[H]
   \centering
	\caption{Area M catch summary for the 2014/15 season.}
	
	\label{table:m1}
	\begin{tabular}{lcccccc}
				& 		&  Catch 	& Dredge  	& Number  	&  		 \\ 
		Year	& GHL 	&(lb meat)  & (hours) 	& hauls  	& cpue$^a$\\ 
		\hline	
		1993/94&   		&	112,087	&	1,847	&	957		&	61\\
		1994/95&		& 65,282	&	1,664	&	1,115	&	39\\
		1995/96&	closed&			&			&			&\\
		1996/97&	200,000&	12,560&	327		&	177		&	38\\
		1997/98&	200,000&	51,616&	1,752	&	1,050	&	29\\
		1998/99&	200,000&	63,290&	1,612	&	681		&	39\\
		1999/00&	200,000&	75,535&	2,025	&	1,099	&	37\\
		2000/01&	33,000&	7,660	&	320		&	188		&	24\\
		2001/02&	closed&			&			&		&	\\
		2002/03&	closed&			&			&		&	\\
		2003/04&	10,000&	No Effort&			&		&\\			
		2004/05&	10,000&	No Effort&	&		&\\		
		2005/06&	10,000&	No Effort&	&&\\		
		2006/07&	25,000&	155&	64&	73&	2\\
		2007/08&	10,000&	No Effort&&&		\\	
		2008/09&	10,000&	2,460&	154&	114&	16\\
		2009/10&	closed&	&&		&	\\
		2010/11&	closed&	&&		&	\\
		2011/12&	closed&	&&		&	\\
		2012/13&	15,000$^b$&	15,040&	255&	248&	59\\
		2013/14&	15,000$^b$&	15,155&	247&	152&	61\\
		2014/15&	15,000$^b$	&15,000		&	285			&	211			&	53\\
		
		\hline	
		\multicolumn{3}{l}{$^a$lb scallop meat/dredge hour}	\\
		\multicolumn{7}{l}{$^b$Exploratory Unimak Bight fishery opened by Commissioner's Permit}
	\end{tabular} 
\end{table}
<<m, fig.pos="H", fig.cap="Maps of Area M fishing locations by fishing year.",echo=FALSE, warning=FALSE ,fig.height=6, cache=TRUE,dev='png', dpi=300>>=
#######################
#M
#######################

#remove incomplete data
m <- m[complete.cases(m),]

#map of sample locations

mmap <- ggplot()+geom_polygon(data=ak,aes(long,lat,group=group),fill=8,color='black') +
   theme(panel.background=element_rect(fill='white')) + 
   xlab(expression(paste(Longitude^o,~'W'))) +
   ylab(expression(paste(Latitude^o,~'W'))) + 
   coord_map(xlim=c(min(m$Set_Lon,na.rm=T)-.5,max(m$Set_Lon,na.rm=T)+.5),
             ylim=c(min(m$Set_Lat,na.rm=T)-.5,max(m$Set_Lat,na.rm=T)+.5))

mmap+geom_point(data=m, aes(Set_Lon,Set_Lat), alpha=.2)+facet_wrap(~ Year)+
   guides(colour = guide_legend(override.aes = list(alpha = 1)))+
   theme(legend.key = element_blank(),legend.position = c(0.1, 0.9),legend.background = 
            element_rect(fill = "#ffffffaa", colour = NA),legend.key.height=unit(.6,'line'))
@

<<mcpue, fig.pos="H", fig.cap="Density and number of tows by year for Area M cpue.",echo=FALSE, warning=FALSE ,fig.height=4, cache=TRUE, dev='png', dpi=300>>=
#RAW density and number of tows
m1 <- ggplot(m, aes(mwt.cpue,fill=Year,color=Year))+geom_density()+xlab('log(cpue)')+
   scale_fill_manual(values=values,breaks=breaks, name='Year')+
   scale_color_manual(values=values,breaks=breaks, name='Year')+
   guides(colour = guide_legend(override.aes = list(alpha = 1)))+ 
   theme(legend.key = element_blank(),legend.position = c(0.15, 0.45),legend.background = 
            element_rect(fill = "#ffffffaa", colour = NA),legend.key.height=unit(.6,'line'))

m2 <- ggplot(m, aes(mwt.cpue,fill=Year,color=Year))+geom_histogram()+xlab('log(cpue)')+
   scale_fill_manual(values=values,breaks=breaks, name='Year')+
   scale_color_manual(values=values,breaks=breaks, name='Year')+
   guides( fill=FALSE, color=FALSE)+ theme(legend.key = element_blank())
grid.arrange(m1,m2,ncol=2)
@

<<mfit, fig.pos="H", fig.cap="Density and number of tows by bed and year for Area M standardized cpue.",echo=FALSE, warning=FALSE ,fig.height=4, cache=TRUE, dev='png', dpi=300>>=
#Model the CPUE

fit <- gam(mwt.cpue~s(Depth,k=4)+te(Set_Lon,Set_Lat)+Year+vessel-1, data=m, gamma=1.4)
#plot(kne$Bed,resid(fit))
m$fit <- fitted(fit)
f1 <- ggplot(m, aes(fit,fill=Year,color=Year))+geom_density()+
   scale_fill_manual(values=values,breaks=breaks, name='Year')+
   scale_color_manual(values=values,breaks=breaks, name='Year')+
   guides(colour = guide_legend(override.aes = list(alpha = 1)))+ 
   theme(legend.key = element_blank(),legend.position = c(0.15, 0.4),legend.background = 
            element_rect(fill = "#ffffffaa", colour = NA),legend.key.height=unit(.6,'line'))

f2 <- ggplot(m, aes(fit,fill=Year,color=Year))+geom_histogram()+
   scale_fill_manual(values=values,breaks=breaks, name='Year')+
   scale_color_manual(values=values,breaks=breaks, name='Year')+
   guides( fill=FALSE, color=FALSE)+ theme(legend.key = element_blank())
grid.arrange(f1,f2,ncol=2)
@


<<mvessel, fig.pos="H", fig.cap="Annual vessel effect from model fit, Area M.",echo=FALSE, warning=FALSE ,fig.height=4, cache=TRUE,dev='png',dpi=300>>=
#Model the CPUE
#ggplot(q, aes(Year,fit, fill=Bed))+geom_boxplot()
#ggplot(q, aes(vessel,fit, fill=Bed))+geom_boxplot()
ggplot(m, aes(Year,fit, fill=vessel))+geom_boxplot(width=.35)
@

<<mfit2, fig.pos="H", fig.cap="Standardized and raw CPUE by year and bed for Area M. Standardized cpue have bootstrap estimated 95\\% confidence levels, the raw cpue have normal approximate 95\\% confidence levels.",echo=FALSE, warning=FALSE ,fig.height=4, cache=TRUE, dev='png', dpi=300>>=
r1 <- ggplot(m, aes(year, fit))+stat_summary(fun.data=mean_cl_boot, geom='smooth')+coord_cartesian(ylim=c(3.9,4.3))+
   ylab('standardized cpue')


a <- aggregate(mwt.cpue~year,data=m, FUN=mean)
b <- aggregate(mwt.cpue~year,data=m, FUN=sd)
names(b) <- c('year', 'sd')
c <- aggregate(mwt.cpue~year,data=m, FUN=length)
names(c) <- c('year', 'n')
d <- merge(a,b, by=c('year'))
d <- merge(c,d, by=c('year'))
d$lci <- d$mwt.cpue-2*d$sd/sqrt(d$n)
d$uci <- d$mwt.cpue+2*d$sd/sqrt(d$n)
r2 <- ggplot(d, aes(year,mwt.cpue))+geom_line()+
   geom_ribbon(aes(ymin=lci, ymax=uci),alpha=.2)+coord_cartesian(ylim=c(3.9,4.3))+ylab('raw cpue')
grid.arrange(r1,r2,ncol=2)
@

<<msh, fig.pos="H", fig.cap="Shell heights by year for Area M. The left pane shows the shell heights distribution for all of the hauls, the right pane shows the number of shells sampled at a given height.",echo=FALSE, warning=FALSE ,fig.height=4, cache=TRUE,dev='png', dpi=300>>=
#Shell heights
m.sh <- merge(m,sh,by=c('Fishery', 'District','Haul_ID','ADFG'))

#SH by year
s1 <- ggplot(m.sh, aes(Shell_Height, fill=Year,color=Year))+geom_density()+
   scale_fill_manual(values=values,breaks=breaks, name='Year')+
   scale_color_manual(values=values,breaks=breaks, name='Year')+
   guides(colour = guide_legend(override.aes = list(alpha = 1)))+ 
   theme(legend.key = element_blank(),legend.position = c(0.15, 0.5),legend.background = 
            element_rect(fill = "#ffffffaa", colour = NA),legend.key.height=unit(.6,'line'))

s2 <- ggplot(m.sh, aes(Shell_Height, fill=Year,color=Year))+geom_histogram()+
   scale_fill_manual(values=values,breaks=breaks, name='Year')+
   scale_color_manual(values=values,breaks=breaks, name='Year')+
   guides(colour = guide_legend(override.aes = list(alpha = 1)))+
   guides( fill=FALSE, color=FALSE)+ theme(legend.key = element_blank())
grid.arrange(s1,s2,ncol=2)
@

<<msh14, fig.pos="H", fig.cap="Retained and discarded shell heights for Area M in 2014. The left pane shows the shell heights distribution for all of the hauls, the right pane shows the number of shells sampled at a given height.",echo=FALSE, warning=FALSE ,fig.height=4, cache=TRUE, dev='png', dpi=300, eval=FALSE>>=
#SH by bed
s1 <- ggplot(subset(m.sh, year==2014), aes(Shell_Height))+geom_density(alpha=.2)+
   scale_color_manual( values=c('D'='#e41a1c','R'='#377eb8'), labels=c('discard', 'retain'),name='')+
   scale_fill_manual( values=c('D'='#e41a1c','R'='#377eb8'), labels=c('discard', 'retain'),name='')+ 
   theme(legend.key = element_blank(),legend.position = c(0.15, 0.4),legend.background = 
   element_rect(fill = "#ffffffaa", colour = NA),legend.key.height=unit(.6,'line'))
s2 <- ggplot(subset(m.sh, year==2014), aes(Shell_Height, fill=Rtnd_Disc,color=Rtnd_Disc))+geom_histogram(alpha=.2)+
   scale_color_manual( values=c('D'='#e41a1c','R'='#377eb8'), labels=c('discard', 'retain'),name='')+
   scale_fill_manual( values=c('D'='#e41a1c','R'='#377eb8'), labels=c('discard', 'retain'),name='')+
   guides( fill=FALSE, color=FALSE)+ theme(legend.key = element_blank())
grid.arrange(s1,s2,ncol=2)
@


<<msh3,fig.pos="H", fig.cap="Shell heights by year for Area M. The left pane shows the shell heights distribution for all of the hauls, the right pane shows the number of shells sampled at a given height.",echo=FALSE, warning=FALSE ,fig.height=8.5, cache=TRUE,dev='png', dpi=300>>=

#SH by year
s1 <- ggplot(m.sh, aes(Shell_Height, fill=Rtnd_Disc,color=Rtnd_Disc))+geom_density(alpha=.2)+facet_grid(Year~.)+
   scale_color_manual( values=c('D'='#e41a1c','R'='#377eb8'), labels=c('discard', 'retain'),name='')+
   scale_fill_manual( values=c('D'='#e41a1c','R'='#377eb8'), labels=c('discard', 'retain'),name='')+ 
   theme(legend.key = element_blank(),legend.position = c(0.2, 0.25),legend.background = 
   element_rect(fill = "#ffffffaa", colour = NA),legend.key.height=unit(.6,'line'))

s2 <- ggplot(m.sh, aes(Shell_Height, fill=Rtnd_Disc,color=Rtnd_Disc))+geom_histogram(alpha=.2)+facet_grid(Year~.)+
   scale_color_manual( values=c('D'='#e41a1c','R'='#377eb8'), labels=c('discard', 'retain'),name='')+
   scale_fill_manual( values=c('D'='#e41a1c','R'='#377eb8'), labels=c('discard', 'retain'),name='')+
   guides( fill=FALSE, color=FALSE)+ theme(legend.key = element_blank())
grid.arrange(s1,s2,ncol=2)
@



<<mage, fig.pos="H", fig.cap="Shell ages (annuli) by bed and year for Area M. ",echo=FALSE, warning=FALSE ,fig.height=4, cache=TRUE, dev='png', dpi=300>>=   
#Ages

m.age <- merge(m, ages,by=c('Fishery', 'District','Haul_ID','ADFG', 'set_date', 'year', 'date', 'Year'))


#age by year
a1 <- ggplot(m.age, aes(annuli, fill=Year, color=Year))+geom_density()+
   scale_fill_manual(values=values, breaks=breaks, name='Year')+
   scale_color_manual(values=values,  breaks=breaks, name='Year')+
   guides(colour = guide_legend(override.aes = list(alpha = 1)))+guides(colour = guide_legend(override.aes = list(alpha = 1)))+
   guides( fill=FALSE, color=FALSE)+ theme(legend.key = element_blank())
a2 <- ggplot(m.age, aes(annuli, fill=Year, color=Year))+geom_histogram()+
   scale_fill_manual(values=values, breaks=breaks, name='Year')+
   scale_color_manual(values=values,  breaks=breaks, name='Year')+ 
   theme(legend.key = element_blank(),legend.position = c(0.75, 0.75),legend.background = 
            element_rect(fill = "#ffffffaa", colour = NA),legend.key.height=unit(.6,'line'))
   
grid.arrange(a1,a2,ncol=2)
@

<<mage2, fig.pos="H", fig.cap="Shell ages (annuli) by year for Area M.",echo=FALSE, warning=FALSE ,fig.height=6, cache=TRUE, dev='png', dpi=300>>=                               
 #Ages
                                           
                        
#age by year
a1 <- ggplot(m.age, aes(annuli))+geom_density(alpha=.3, fill=4)+facet_grid(Year~., scale='free_y')+
   guides(colour = guide_legend(override.aes = list(alpha = 1)))+ 
   theme(legend.key = element_blank(),legend.position = c(0.75, 0.08),legend.background = 
            element_rect(fill = "#ffffffaa", colour = NA),legend.key.height=unit(.6,'line'))
a2 <- ggplot(m.age, aes(annuli))+geom_histogram(color='white',alpha=.3, fill=4)+facet_grid(Year~.)+
      guides(colour = guide_legend(override.aes = list(alpha = 1)))+
   guides( fill=FALSE, color=FALSE)+ theme(legend.key = element_blank())
grid.arrange(a1,a2,ncol=2)
@   

<<magesh, fig.pos="H", fig.cap="Comparison between shells measured for height and shell height of aged scallops by year for Area M. The left pane shows the density of all shell heights collected (blue) and the density of shell heights from ages shells (gray). The right pane shows the densities of shell heights from retained shells, discarded shell, and aged shells.",echo=FALSE, warning=FALSE ,fig.height=8.5, cache=TRUE, dev='png', dpi=300>>=

#qmap+geom_point(data=subset(q.age, year<2012),aes(Set_Lon,Set_Lat,color=annuli,width=1.2),alpha=.2) +
##   guides(colour = guide_legend(override.aes = list(alpha = 1)))+facet_grid(Year~.)+
#   scale_colour_gradientn(colours =rainbow(5))

#qmap+geom_point(data=subset(q.age, year>2011),aes(Set_Lon,Set_Lat,color=annuli,width=1.2),alpha=.2) +
#   guides(colour = guide_legend(override.aes = list(alpha = 1)))+facet_grid(Year~.)+
#   scale_colour_gradientn(colours=rainbow(5))

#ggplot(q.age, aes(annuli))+geom_density(alpha=.2,fill=4)+facet_grid(Year~.)
#ggplot(q.age, aes(annuli))+geom_histogram(alpha=.2,color='black', fill=4)+facet_grid(Year~.)

#difference between shell height samples and shell height ages
as1 <- ggplot(m.age, aes(Shell_Height))+geom_density(alpha=.2,fill='black')+facet_grid(Year~.)+
   geom_density(data=m.sh, aes(Shell_Height), alpha=.2,fill=4)

as2 <- ggplot(m.age, aes(Shell_Height))+geom_density(alpha=.2,fill='black')+facet_grid(Year~.)+
   geom_density(data=m.sh, aes(Shell_Height, fill=Rtnd_Disc), alpha=.2)+guides(colour = guide_legend(override.aes = list(alpha = 1)))+ 
   theme(legend.key = element_blank(),legend.position = c(0.15, 0.23),legend.background = 
            element_rect(fill = "#ffffffaa", colour = NA),legend.key.height=unit(.6,'line'))+
   scale_fill_manual( values=c('D'='#e41a1c','R'='#377eb8'), labels=c('discard', 'retain'),name='')
grid.arrange(as1,as2,ncol=2)
@

<<magex, echo=FALSE, warning=FALSE,eval=FALSE, dev='png', dpi=300>>=
ggplot(m.age, aes(Shell_Height))+geom_density(alpha=.2,fill='black')+facet_grid(Year~.)+
   geom_density(data=q.sh, aes(Shell_Height), alpha=.2,fill=4)

ggplot(m.age, aes(Shell_Height))+geom_density(alpha=.2,fill='black')+facet_grid(Year~Bed, scales='free_y')+
   geom_density(data=q.sh, aes(Shell_Height, fill=Rtnd_Disc), alpha=.2)


ggplot(m.age, aes(annuli, Meat_Weight))+geom_point(alpha=.2,color='black')+facet_grid(Year~.)+
   stat_smooth()+coord_cartesian(xlim=c(0,20))
ggplot(m.age, aes(annuli, Meat_Weight, group=Year,color=Year,fill=Year))+geom_point(alpha=.2,color='black')+
   stat_smooth()+coord_cartesian(xlim=c(0,20))


ggplot(m.age, aes(Depth,annuli, group=Year,color=Year,fill=Year))+geom_point(alpha=.2,color='black')+stat_smooth()
ggplot(m.age, aes(Depth,annuli))+geom_point(alpha=.2,color='black')+stat_smooth(method='lm')
ggplot(m.sh, aes(Depth,Shell_Height, group=Year,color=Year,fill=Year))+geom_point(alpha=.2,color='black')+stat_smooth(method='lm')
ggplot(m.sh, aes(Depth,Shell_Height))+geom_point(alpha=.2,color='black')+stat_smooth(method='lm')


ggplot(m.age, aes(Depth,annuli, group=Year))+geom_point(alpha=.2,color='black')+stat_smooth()
ggplot(m.sh, aes(Shell_Height, Meat_Weight,group=Year,color=Year,fill=Year))+geom_point(alpha=.2,color='black')+stat_smooth(method='lm')
@


<<mcrab, fig.pos="H", fig.cap="Estimated Tanner Crab and Pacific Halibut catch for Area M.",echo=FALSE, warning=FALSE ,fig.height=4, cache=TRUE, dev='png', dpi=300, eval=TRUE>>=   
m.by <- merge(by, m, by=c('Fishery', 'District','ADFG', 'set_date', 'year', 'date', 'Year', 'vessel'))

a <- aggregate(Halibut_Count~year,data=subset(by, District=='UB'), FUN=sum)
a1 <- aggregate(Tanner_Count~year,data=subset(by, District=='UB'), FUN=sum)
b <- aggregate(Sample_Hrs~year,data=subset(by, District=='UB'), FUN=sum)
c <- aggregate(Dredge_Hrs~year,data=m, FUN=sum)

d <- merge(a,b, by='year')
d <- merge(a1,d, by='year')
d <- merge(c,d, by='year')

d$hal <- d$Halibut_Count/d$Sample_Hrs*d$Dredge_Hrs
d$tan <- d$Tanner_Count/d$Sample_Hrs*d$Dredge_Hrs

d <- d[,c(1,6,7)]
d<- melt(d, id.vars=c( 'year'))
ggplot(d, aes(year, value, color=variable, group=variable))+geom_line()+geom_point(size=3)+
    scale_color_discrete(name="species",
                         breaks=c("tan", "hal"),
                         labels=c("Tanner", "Halibut"))
@


<<mdisc, fig.pos="H", fig.cap="Scallop estimated discard weight for Area M.",echo=FALSE, warning=FALSE ,fig.height=4, cache=TRUE, dev='png', dpi=300, eval=TRUE>>=   
m.by <- merge(by, m, by=c('Fishery', 'District','ADFG', 'set_date', 'year', 'date', 'Year', 'vessel'))

a <- aggregate(Sample_Hrs~year,data=subset(by, District=='UB'), FUN=sum)
a1 <- aggregate(Discard_Weight~year,data=subset(by, District=='UB'), FUN=sum)
a2 <- aggregate(Broken_Weight~year,data=subset(by, District=='UB'), FUN=sum)
a3 <- aggregate(Rem_Disc_Wt~year,data=subset(by, District=='UB'), FUN=sum)
b <- aggregate(Dredge_Hrs~year,data=m, FUN=sum)
c <- aggregate(Round_Weight~year,data=m, FUN=sum)

d <- merge(a,a1, by='year')
d <- merge(d,a2, by='year')
d <- merge(d,a3, by='year')
d <- merge(b,d, by='year')
d <- merge(c,d, by='year')
d$wt <- d[,5]+d[,6]+d[,7]
d$disc <- d$wt/d$Sample_Hrs*d$Dredge_Hrs
d$per <- d$disc/d$Round_Weight*100
ggplot(d, aes(year, disc))+geom_line()+geom_point(size=3)+ylim(0, max(d$disc))+ylab('Scallop discard weight (lbs)')
    
@
\end{document}