<<set-parent, echo=FALSE,cache=FALSE,eval=FALSE>>=
set_parent('2015_scallop.Rnw')
@

<<loadyak,echo=FALSE,message=FALSE,warning=FALSE>>=
#load inputs
library(lubridate)
library(extrafont);library(ggplot2)
#font_import() only do this one time - it takes a while
loadfonts(device="win")
windowsFonts(Times=windowsFont("TT Times New Roman"))
theme_set(theme_bw(base_size=12,base_family='Times New Roman')+theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank()))
library(mgcv)
library(maps)
library(mapdata)
library(mapproj)
library(gridExtra)
library(gtools)
library(RColorBrewer)
library(plyr)
library(xtable)
library(reshape2)
library(xtable)

#import data To update with a new year simply add a new file and bind it with the others
scallops09 <- read.csv("C:/Users/bcwilliams/Documents/Fisheries/scallops/Data/2009-scallopCatchByHaul.csv")
scallops10 <- read.csv("C:/Users/bcwilliams/Documents/Fisheries/scallops/Data/2010-scallopCatchByHaul.csv")
scallops11 <- read.csv("C:/Users/bcwilliams/Documents/Fisheries/scallops/Data/2011-scallopCatchByHaul.csv")
scallops12 <- read.csv("C:/Users/bcwilliams/Documents/Fisheries/scallops/Data/2012-scallopCatchByHaul.csv")
scallops13 <- read.csv("C:/Users/bcwilliams/Documents/Fisheries/scallops/Data/2013-scallopCatchByHaul.csv")
scallops14 <- read.csv("C:/Users/bcwilliams/Documents/Fisheries/scallops/Data/2014-scallopCatchByHaul.csv")
scallops <- rbind(scallops09,scallops10, scallops11, scallops12,scallops13, scallops14)

sh09 <- read.csv("C:/Users/bcwilliams/Documents/Fisheries/scallops/Data/2009-scallopShellHeights.csv")
sh10 <-  read.csv("C:/Users/bcwilliams/Documents/Fisheries/scallops/Data/2010-scallopShellHeights.csv")
sh11 <- read.csv("C:/Users/bcwilliams/Documents/Fisheries/scallops/Data/2011-scallopShellHeights.csv")
sh12 <- read.csv("C:/Users/bcwilliams/Documents/Fisheries/scallops/Data/2012-scallopShellHeights.csv")
sh13 <- read.csv("C:/Users/bcwilliams/Documents/Fisheries/scallops/Data/2013-scallopShellHeights.csv")
sh14 <- read.csv("C:/Users/bcwilliams/Documents/Fisheries/scallops/Data/2014-scallopShellHeights.csv")
sh <- rbind(sh09,sh10,sh11,sh12,sh13,sh14)

cr09 <- read.csv("C:/Users/bcwilliams/Documents/Fisheries/scallops/Data/2009-crabSizes.csv")
cr10 <-  read.csv("C:/Users/bcwilliams/Documents/Fisheries/scallops/Data/2010-crabSizes.csv")
cr11 <- read.csv("C:/Users/bcwilliams/Documents/Fisheries/scallops/Data/2011-crabSizes.csv")
cr12 <- read.csv("C:/Users/bcwilliams/Documents/Fisheries/scallops/Data/2012-crabSizes.csv")
cr13 <- read.csv("C:/Users/bcwilliams/Documents/Fisheries/scallops/Data/2013-crabSizes.csv")
cr14 <- read.csv("C:/Users/bcwilliams/Documents/Fisheries/scallops/Data/2014-crabSizes.csv")
crab <- rbind(cr09,cr10,cr11,cr12,cr13,cr14)

by09 <- read.csv("C:/Users/bcwilliams/Documents/Fisheries/scallops/Data/2009-scallopBycatchByDay.csv")
by10 <-  read.csv("C:/Users/bcwilliams/Documents/Fisheries/scallops/Data/2010-scallopBycatchByDay.csv")
by11 <- read.csv("C:/Users/bcwilliams/Documents/Fisheries/scallops/Data/2011-scallopBycatchByDay.csv")
by12 <- read.csv("C:/Users/bcwilliams/Documents/Fisheries/scallops/Data/2012-scallopBycatchByDay.csv")
by13 <- read.csv("C:/Users/bcwilliams/Documents/Fisheries/scallops/Data/2013-scallopBycatchByDay.csv")
by14 <- read.csv("C:/Users/bcwilliams/Documents/Fisheries/scallops/Data/2014-scallopBycatchByDay.csv")
by <- rbind(by09,by10,by11,by12,by13,by14)

ages <- read.csv("C:/Users/bcwilliams/Documents/Fisheries/scallops/Data/scallop_ages_bcw.csv")
ages <- ages[,2:47]
ages14 <- read.csv("C:/Users/bcwilliams/Documents/Fisheries/scallops/Data/2014ScallopShellAgeData.csv")


#adjust names to match other files
names(ages14) <- c('id', 'trip_id', 'haul_id', 'aged_by','fishery', 'fishery_season','district','vessel','trip_or_packet','date','small_or_retained','haul','shell','annuli','letter_code','number_code','shell_height' ,'a1','a2','a3','a4','a5','a6','a7','a8','a9','a10' ,'a11', 'a12','a13','a14','a15','a16','a17','a18','a19','a20','a21','a22','a23','a24','a25','a26','a27')

ages<- smartbind(ages,ages14)

names(ages) <- c('id', 'Trip_ID', 'Haul_ID', 'aged_by','date_aged','Fishery', 'season','District','ADFG','packetnum','stat_area','Set_Date','Rtnd_Disc','haul','shell_num','annuli','code_let','code_num','Shell_Height','a1','a2','a3','a4','a5','a6','a7','a8','a9','a10' ,'a11', 'a12','a13','a14','a15','a16','a17','a18','a19','a20','a21','a22','a23','a24','a25','a26','a27')
#adjust dates
scallops$set_date <- as.Date(scallops$Set_Date, "%m-%d-%Y")
scallops$year <- as.numeric(format(scallops$set_date, "%Y"))
scallops$date <- yday(scallops$set_date)
scallops$year <- ifelse(scallops$date<100, scallops$year-1, scallops$year)
scallops$Year <- factor(scallops$year)
scallops$vessel <- factor(scallops$ADFG)

ages$set_date <- as.Date(ages$Set_Date, "%m/%d/%Y")
ages$year <- as.numeric(format(ages$set_date, "%Y"))
ages$date <- yday(ages$set_date)
ages$year <- ifelse(ages$date<100, ages$year-1, ages$year)
ages$Year <- factor(ages$year)

by$set_date <- as.Date(by$Set_Date, "%m-%d-%Y")
by$year <- as.numeric(format(by$set_date, "%Y"))
by$date <- yday(by$set_date)
by$year <- ifelse(by$date<100, by$year-1, by$year)
by$Year <- factor(by$year)
by$vessel <- factor(by$ADFG)

#plotting smotting
#year 2009-2014 colors and breaks
values <- c('2014'='#542788bb','2013'='#998ec340','2012'='#d8daeb40',
         '2011'='#fee0b640','2010'='#f1a34040','2009'='#b3580640') 
breaks <- c('2014', '2013','2012','2011','2010','2009')
@

<<akmapyak, fig.pos="H", fig.cap="Map of all scallop dredge hauls. Top pane shows fishing locations from the 2009/10-2014/15 fishing season. Bottom pane shows fishing locations from the 2014/15 fishing season.",echo=FALSE, warning=FALSE ,fig.height=7, cache=TRUE,dev='png', dpi=300>>=
# Map
ak <- map_data('worldHires', c('USA:Alaska','Canada'))
@

<<cpueyak, fig.pos="H", fig.cap="Log transformed cpue (weight/area swept) by round weight and shell weight.",echo=FALSE, warning=FALSE ,fig.height=4, cache=TRUE,dev='png', dpi=300, message=FALSE>>=

#remove data where dredge hours & area swept are zero
scallops <- subset(scallops,Area_Swept.nm2.>0)

#calculate round weight cpue by time and by area 
scallops$rw.cpue.t <- scallops$Round_Weight/scallops$Dredge_Hrs
scallops$rw.cpue.a <- scallops$Round_Weight/scallops$Area_Swept.nm2.

#calculate meat weight cpue by time and by area
scallops$mw.cpue.t <- scallops$Meat_Weight/scallops$Dredge_Hrs
scallops$mw.cpue.a <- scallops$Meat_Weight/scallops$Area_Swept.nm2.

#Subset scallop data to eliminate zeros in the cpue
scallop <- subset(scallops,rw.cpue.t>0)

#look for normality in cpue data
#h1 <- ggplot(scallop,aes(rw.cpue.t))+geom_histogram()
#h2 <- ggplot(scallop,aes(rw.cpue.a))+geom_histogram()+xlab('Round weight CPUE')
#h3 <- ggplot(scallop,aes(mw.cpue.t))+geom_histogram()
#h4 <- ggplot(scallop,aes(mw.cpue.a))+geom_histogram()+xlab('Meat weight CPUE')
#grid.arrange(h2,h4,ncol=2)

#adjust area cpue for log transformed data (Cambell et al 1996; Cambell 2004)
rwt.adjust <- mean(scallop$rw.cpue.t)*.10
rwa.adjust <- mean(scallop$rw.cpue.a)*.10
mwt.adjust <- mean(scallop$mw.cpue.t)*.10
mwa.adjust <- mean(scallop$mw.cpue.a)*.10

#log transform cpue data
scallop$rwt.cpue <- log(scallop$rw.cpue.t+rwt.adjust)
scallop$rwa.cpue <- log(scallop$rw.cpue.a+rwa.adjust)
scallop$mwt.cpue <- log(scallop$mw.cpue.t+mwt.adjust)
scallop$mwa.cpue <- log(scallop$mw.cpue.t+mwa.adjust)

#Subset data
eki <- subset(scallop,District=='EKI')
wki <- subset(scallop,District=='WKI')
yak <- subset(scallop,District=='YAK' |District=='D16' )
d16 <- subset(scallop,District=='D16')
kne <- subset(scallop,District=='KNE' )
ksh <- subset(scallop,District=='KSH' )
ksw <- subset(scallop,District=='KSW' )
m <- subset(scallop,District=='UB' )
o <- subset(scallop,District=='O')
q <- subset(scallop,District=='Q')
c <- subset(scallop,District=='C' )
@

<<yak, fig.pos="H", fig.cap="Maps of Area D fishing locations by fishing year.",echo=FALSE, warning=FALSE ,fig.height=8.5, cache=TRUE,dev='png', dpi=300>>=
#######################
#Yak
#######################

#split by bed
yak$bed = NA
yak<-within(yak,bed[Set_Lon > -138.3]<-6)#actually bed D16
yak<-within(yak,bed[Set_Lon < -138.3]<-5)
yak<-within(yak,bed[Set_Lon < -138.79]<-4)
yak<-within(yak,bed[Set_Lon < -140.1]<-3)
yak<-within(yak,bed[Set_Lon < -142.15]<-2)
yak<-within(yak,bed[Set_Lon < -142.7]<-1)
yak<-within(yak,bed[Set_Lon < -143.5]<-0)#actually bed B

#remove incomplete data
yak <- yak[complete.cases(yak),]
yak$Bed <- factor(yak$bed)
#change bed names
replace <- c("0"="B", "6"='D16')
yak$Bed <- revalue(yak$Bed, replace)

#Model the CPUE

fit <- gam(mwt.cpue~s(Depth,k=4)+te(Set_Lon,Set_Lat)+Year+s(Bed, bs='re')+vessel-1, data=yak, gamma=1.4)
#ggplot(yak, aes(year, fit, color=Bed, fill=Bed))+stat_summary(fun.data=mean_cl_boot, geom='smooth')
#plot(yak$Bed,resid(fit))
yak$fit <- fitted(fit)

@

\section{Area D Scallop Observer Data Summary}
\subsection{Yakutat \& District 16}
   \subsubsection{Fishery performance}
   A total of 120,353 pounds of meat were retained from three vessels (ADF\&G \#40924, \#54966, \#58200) that participated in the 2014/2015 Yakutat District fishery (Table~\ref{table:yakt1}). Two vessels (ADF\&G \#40924, \#58200) participated in the District 16 fishery (note that all of Bed 6 is included in this assessment) and caught a total of 9,140 pounds of scallop meat (Table~\ref{table:d16t1}).

It is evident that there is substantial spatial fishing variability within a given bed by year (Figures~\ref{fig:yakmap} and \ref{fig:yak2}). The non-standardized cpue shows a general trend in 2014/15 of higher cpue to the West (bed B) and lower cpue to the East (bed D16). In particular bed 3 saw very little directed effort during the 2014/15 season.


\begin{table}[H]
\centering
\caption{Yakutat district catch summary for the 2014/15 season.}

\label{table:yakt1}
   \begin{tabular}{lcccccc}
            &  \multicolumn{2}{c}{Retained catch} & Dredge  & Number  &   \\ 
		Year	&(lb meat)  & (lb round) & hours & hauls  & cpue$^a$    \\ 
\hline	1995	& 242,491& 3,214,968 &  4,712&  2,597&  51   \\ 
		1996	& 238,736& 3,195,254 &  3,982&  2,102&  60    \\ 
		1997/98	& 242,940& 	3,282,860& 	3,956& 	1,958& 	61\\
		1998/99	& 241,678& 	3,475,996& 	4,192& 	2,193& 	58\\
		1999/00	& 249,681& 	3,119,103& 	3,840& 	1,720& 	65\\
		2000/01	& 195,699& 	2,734,559& 	4,241& 	2,111& 	46\\
		2001/02	& 103,800& 	1,521,537& 	2,406& 	1,096& 	43\\
		2002/03	& 122,718& 	1,541,867& 	2,439& 	1,243& 	50\\
		2003/04	& 160,918& 	1,939,004& 	3,358& 	1,716& 	48\\
		2004/05	& 86,950& 	1,262,499& 	2,134& 	1,194& 	41\\
		2005/06	& 199,351& 	2,662,031& 	5,089& 	2,585& 	39\\
		2006/07	& 150,950& 	1,771,229& 	2,817& 	1,533& 	54\\
		2007/08	& 125,960& 	1,593,223& 	2,601& 	1,416& 	48\\
		2008/09	& 150,289& 	2,053,912& 	3,286& 	1,825& 	46\\
		2009/10	& 158,901& 	2,218,840& 	3,975& 	2,580& 	40\\
		2010/11	& 156,612& 	2,087,228& 	3,495& 	2,020& 	45\\
		2011/12	& 157,025& 	2,386,748& 	4,622& 	2,703& 	34\\
		2012/13	& 120,577& 	1,708,044& 	3,402& 	1,988& 	35\\
		2013/14	& 122,290& 	1,540,114&	2,391& 	1,348& 	51\\
		2014/15	& 120,353& 	1,446,693& 	2,727& 	1,597& 	44\\
	\hline	
	\multicolumn{3}{l}{$^a$lb scallop meat/dredge hour}	
	\end{tabular} 
\end{table}

<<yak_xtbl, results='asis', error=FALSE, warning=FALSE,message=FALSE, echo=FALSE>>=

#A cheat for making a table with multirow column names
a <- aggregate((exp(mwt.cpue)-mwt.adjust)~year, data=yak, FUN=median)
names(a) <- c('year', 'median')

b <- aggregate((exp(mwt.cpue)-mwt.adjust)~year, data=yak, FUN=mean)
names(b) <- c('year', 'mean')
c <- aggregate((exp(mwt.cpue)-mwt.adjust)~year, data=yak, FUN=sd)
names(c) <- c('year', 'sd')

d <- aggregate((exp(fit)-mwt.adjust)~year, data=yak, FUN=median)
names(d) <- c('year', 'std median')
e <- aggregate((exp(fit)-mwt.adjust)~year, data=yak, FUN=mean)
names(e) <- c('year', 'std mean')
f <- aggregate((exp(fit)-mwt.adjust)~year, data=yak, FUN=sd)
names(f) <- c('year', 'std sd')
g <- merge(a,b, by='year')
g <- merge(g,c, by='year')
g <- merge(g,d, by='year')
g <- merge(g,e, by='year')
g <- merge(g,f, by='year')

print(xtable(g, align="llcccccc", digits=c(0,0,1,1,1,1,1,1)),only.contents=TRUE,
      include.colnames=FALSE, include.rownames = FALSE, floating=FALSE,type='latex',
      hline.after=NULL, file='goutyak.tex')
@
   \begin{table}[H]
   \centering
   \caption{Yakutat District catch summary for the 2009/10-2014/15 season for raw and standardized data. Data in this table are from the Kodiak Wiki*}
   \label{table:yak2}
   \vspace{1.5ex}
\begin{tabular}{lrrcrrc}
   \hline
 &\multicolumn{3}{c}{Raw cpue} & \multicolumn{3}{c}{Standardized cpue}  \\ 
    Year	& median&	mean& sd	& median&	mean&	sd\\
\hline\\[-1.5ex]

\input{goutyak.tex}
   \hline
    \multicolumn{7}{l}{*Data from Wiki are different from older versions.}
\end{tabular}
   \end{table}
   
   
\begin{table}[H]
\centering
\caption{District 16 catch summary for the 2014/15 season.}

\label{table:d16t1}
   \begin{tabular}{lcccccc}
   			&  \multicolumn{2}{c}{Retained catch} & Dredge  & Number  &   \\ 
		Year	&(lb meat)  & (lb round) & hours & hauls  & cpue$^a$    \\ 
\hline   1995&   33,302	 &  447,469&	1,095&	599&	30\\
         1996&	34,060	  & 422,064&	917&	554&	37\\
         1997/98&	22,890&	265,882&	561&	105&	41\\
         1998/99&	34,153&	384,286&	702&	449&	49\\
         1999/00&	34,624&	292,625&	674&	299&	51\\
         2000/01&	30,904&	310,370&	476&	359&	65\\
         2001/02&	20,398&	245,319&	417&	291&	49\\
         2002/03&	3,685	 &  60,928&	100&	244&	37\\
         2003/04&	1,072	 &  16,780&	18	 &  193&	60\\
         2004/05&	24,430&	326,228&	419&	55	 &  58\\
         2005/06&	13,650&	209,487&	407&	12	  & 34\\
         2006/07&	13,445&	184,106&	309&	111&	44\\
         2007/08&	180	 &  8,888	 &  14	 &  197&	13\\
         2008/09&	20,986&	207,251&	423&	160&	50\\
         2009/10&	13,591&	210,006&	498	&299&	27\\
         2010/11&	2,655&	   31,266&	83	  & 54	 &  32\\
         2011/12&	1,826	 &  21,978&	59	 &  51	 &  31\\
         2012/13&	26,713&	335,178&	734&	448&	36\\
         2013/14&	25,110&	313,000&	634&	368&	40\\
         2014/15&	9,140&	   108,803&	413&	223&	22\\

	\hline	
	\multicolumn{3}{l}{$^a$lb scallop meat/dredge hour}	
	\end{tabular} 
\end{table}


<<d_xtbl, results='asis', error=FALSE, warning=FALSE,message=FALSE, echo=FALSE,fig.pos='H'>>=

#A cheat for making a table with multirow column names
a <- aggregate((exp(mwt.cpue)-mwt.adjust)~year, data=subset(yak, District=='D16'), FUN=median)
names(a) <- c('year', 'median')

b <- aggregate((exp(mwt.cpue)-mwt.adjust)~year, data=subset(yak, District=='D16'), FUN=mean)
names(b) <- c('year', 'mean')
c <- aggregate((exp(mwt.cpue)-mwt.adjust)~year, data=subset(yak, District=='D16'), FUN=sd)
names(c) <- c('year', 'sd')

d <- aggregate((exp(fit)-mwt.adjust)~year, data=subset(yak, District=='D16'), FUN=median)
names(d) <- c('year', 'std median')
e <- aggregate((exp(fit)-mwt.adjust)~year, data=subset(yak, District=='D16'), FUN=mean)
names(e) <- c('year', 'std mean')
f <- aggregate((exp(fit)-mwt.adjust)~year, data=subset(yak, District=='D16'), FUN=sd)
names(f) <- c('year', 'std sd')
g <- merge(a,b, by='year')
g <- merge(g,c, by='year')
g <- merge(g,d, by='year')
g <- merge(g,e, by='year')
g <- merge(g,f, by='year')

print(xtable(g, align="llcccccc", digits=c(0,0,1,1,1,1,1,1)),only.contents=TRUE,
      include.colnames=FALSE, include.rownames = FALSE, floating=FALSE,type='latex',
      hline.after=NULL, file='goutd16.tex')
@
   \begin{table}[H]
   \centering
   \caption{District 16 catch summary for the 2009/10-2014/15 season for raw and standardized data. Data in this table are from the Kodiak Wiki*}
   \label{table:d2}
   \vspace{1.5ex}
\begin{tabular}{lrrcrrc}
   \hline
 &\multicolumn{3}{c}{Raw cpue} & \multicolumn{3}{c}{Standardized cpue}  \\ 
    Year   & median&	mean& sd	& median&	mean&	sd\\
\hline\\[-1.5ex]

\input{goutd16.tex}
   \hline
    \multicolumn{7}{l}{*Data from Wiki are different from older versions.}
\end{tabular}
   \end{table}
   
<<yakmap, fig.pos="H", fig.cap="Maps of Area D fishing locations by fishing year.",echo=FALSE, warning=FALSE ,fig.height=8.5, cache=TRUE,dev='png', dpi=300>>=
#map of sample locations

yakmap <- ggplot()+geom_polygon(data=ak,aes(long,lat,group=group),fill=8,color='black') +
   theme(panel.background=element_rect(fill='white')) + 
   xlab(expression(paste(Longitude^o,~'W'))) +
   ylab(expression(paste(Latitude^o,~'W'))) + 
   coord_map(xlim=c(min(yak$Set_Lon,na.rm=T)-.2,max(yak$Set_Lon,na.rm=T)+.2),
             ylim=c(min(yak$Set_Lat,na.rm=T)-.2,max(yak$Set_Lat,na.rm=T)+.2))

#yakmap1
yakmap+geom_point(data=subset(yak, year<2012),aes(Set_Lon,Set_Lat,color=Bed,width=1.2),alpha=.2) +
   guides(colour = guide_legend(override.aes = list(alpha = 1)))+facet_grid(Year~.)
@

<<yak2, fig.pos="H", fig.cap="Maps of Area D fishing locations by year.",echo=FALSE, warning=FALSE ,fig.height=8.5, cache=TRUE, dev='png', dpi=300>>=
#yakmap2
yakmap+geom_point(data=subset(yak, year>2011),aes(Set_Lon,Set_Lat,color=Bed,width=1.2),alpha=.2) +
   guides(colour = guide_legend(override.aes = list(alpha = 1)))+facet_grid(Year~.)
@


\subsection{Author's assessemnt}
I've presented raw and standardized cpue below in a format that differs from previous observer data summaries. In Figure~\ref{fig:yakcpue} the left panes show the density of cpue data. This is the distribution of cpue by haul irrespective of the number of hauls. The right pane is a histogram showing the number of hauls for a bed in a given year, note that the histogram shows stacked bars. The same plots are shown in Figure~\ref{fig:yakfit} for the standardized data. Figure~\ref{fig:yakfit2} shows annual cpue with 95\% confidence limits. This is followed by plots of shell height and shell ages.
\\

\noindent \textbf{Bed B}\\
Bed B had a higher mean cpue than in past years, and the amount of effort in the area was higher than in most years. The standardized cpue shows a stronger uptick in 2014 than previous years as well as a binomial distribution in cpue. The last time this bed was fished as heavily was in 2009, after which cpue declined the number of tows was lower. The distribution of shell heights was similar to that observed in 2013, however there was a poor showing in 2014 of smaller shell heights, possibly an indication of poor recruitment. Some of the discarded shells were fairly large, an indication that quality may not be great. Last it appears that the 2014 catch was predominantly of age-14 shells, these first appeared in the fishery in 2009.
\\

\noindent \textbf{Bed 1}\\
Bed 1 had a lower cpue in 2014 than in 2013, though peformed better than the previous years. However, the number of hauls in bed 1 was less than in 2013. The shell heights in bed 1 have a strong bimodal distribution, possibly indicating another cohorrt recruiting to the fishery (this assumes that shell measurements are proportional to the distribution of shells in the population). There is also a rather flat age structure.
\\

\noindent \textbf{Bed 2}\\  
Bed 2 had a generally high cpue and a relatively high number of hauls compared to years past. Standardized cpue shows a decline in 2014 from 2013, although shell heights indicate that there may be a size group ready to recruit into the fishery. 
\\

\noindent \textbf{Bed 3}\\  
Cpue in bed 3 was widely distributed, possibly due to test hauls in different areas to ascertain the viability of the bed in 2014? Very few hauls were made in bed 3. The shell heights sampled were similar to thos of previous years, thoug teh age structure was rather flat. This is likely due to the low number of samples available, more than a reflexion of what is going on in the population.
\\

\noindent \textbf{Bed 4}\\  
Bed 4 saw quite limited harvest relative to past years with a cpue in line with that observed in 2013. However standardized cpue shows a decline from 2013 and an overall cpue slightly lower than that observed in 2010. The shell heights sampled were comparable to previous years, though discards were sometimes large, ppotentially indicating poor quality of product. The age distribution is also lower than it was for years with greater numbers of hauls.

\noindent \textbf{Bed 5}\\  
Bed 5 generally has one of the higher cpues, however the number of hauls is low compared to some prior years. Similar to  bed 4 the shell heights were similar to past years, though the discard rate by shell size was high and the age structure is indicates a dominant age cohort(s).
\\

\noindent \textbf{Bed D16}\\  
CPUE in bed D16 was lower in 2014 than in 2013, though the number of hauls were similar. This typically has the lowest cpue of any of the beds. Shell height is more broadly dispersed than in previous years, and teh ages are coparable to previous years, aside from 2009, when older ages were prevelent.

<<yakcpue, fig.pos="H", fig.cap="Density and number of tows by bed and year for Area D cpue. The left pane shows the cpue distribution for all of the hauls, the right pane shows the number of hauls.",echo=FALSE, warning=FALSE ,fig.height=8.5, cache=TRUE, dev='png', dpi=300>>=

#density and number of tows
m1 <- ggplot(yak, aes(mwt.cpue,fill=Year,color=Year))+geom_density()+
   facet_grid(Bed~., scales='free_y')+xlab('log(cpue)')+
   scale_fill_manual(values=values, breaks=breaks, name='Year')+
   scale_color_manual(values=values, breaks=breaks, name='Year')+
   guides(colour = guide_legend(override.aes = list(alpha = 1)))+ 
   theme(legend.key = element_blank(),legend.position = c(0.15, 0.22),legend.background = 
            element_rect(fill = "#ffffffaa", colour = NA),legend.key.height=unit(.6,'line'))

m2 <- ggplot(yak, aes(mwt.cpue,fill=Year,color=Year))+geom_histogram()+
   facet_grid(Bed~.)+xlab('log(cpue)')+
   scale_fill_manual(values=values, breaks=breaks, name='Year')+
   scale_color_manual(values=values, breaks=breaks, name='Year')+
   guides( fill=FALSE, color=FALSE)+ theme(legend.key = element_blank())

grid.arrange(m1,m2,ncol=2)
@

<<yakfit, fig.pos="H", fig.cap="Density and number of tows by bed and year for Area D standardized cpue. The left pane shows the cpue distribution for all of the hauls, the right pane shows the number of hauls.",echo=FALSE, warning=FALSE ,fig.height=8.5, cache=TRUE,dev='png', dpi=300>>=
#plot Yak model fits
f1 <- ggplot(yak, aes(fit,fill=Year,color=Year))+geom_density()+facet_grid(Bed~., scales='free_y')+
   scale_fill_manual(values=values,  
                     breaks=breaks, name='Year')+
   scale_color_manual(values=values,  
                      breaks=breaks, name='Year')+
   guides(colour = guide_legend(override.aes = list(alpha = 1)))+ 
   theme(legend.key = element_blank(),legend.position = c(0.15, 0.22),legend.background = 
            element_rect(fill = "#ffffffaa", colour = NA),legend.key.height=unit(.6,'line'))

f2 <- ggplot(yak, aes(fit,fill=Year,color=Year))+geom_histogram()+facet_grid(Bed~.)+
   scale_fill_manual(values=values,  
                     breaks=breaks, name='Year')+
   scale_color_manual(values=values,  
                      breaks=breaks, name='Year')+
   guides( fill=FALSE, color=FALSE)+ theme(legend.key = element_blank())
grid.arrange(f1,f2,ncol=2)
@

<<yakvessel, fig.pos="H", fig.cap="Annual vessel effect from model fit, Area D.",echo=FALSE, warning=FALSE ,fig.height=4, cache=TRUE,dev='png',dpi=300>>=
#Model the CPUE

#ggplot(yak, aes(Year,fit, fill=interaction(vessel,Bed)))+geom_boxplot()
#ggplot(yak, aes(vessel,fit, fill=Bed))+geom_boxplot()
ggplot(yak, aes(Year,fit, fill=vessel))+geom_boxplot(width=.35)
@

<<yakfit2, fig.pos="H", fig.cap="Standardized and raw cpue by year and bed for District D. Standardized cpue have bootstrap estimates 95\\% confidence levels, the raw cpue have normal approximate 95\\% confidence levels.",echo=FALSE, warning=FALSE ,fig.height=4, cache=TRUE, dev='png', dpi=300>>=
r1 <- ggplot(yak, aes(year, fit, color=Bed, fill=Bed))+stat_summary(fun.data=mean_cl_boot, geom='smooth')+
   scale_fill_manual(values = c('B'='#66250610','1'='#cc4c0210','2'='#fe992910',
         '3'='#e31a1c10','4'='#225ea810','5'='#41b6c410', 'D16'='#54278f10'),
         breaks= c('B', '1','2','3','4','5', 'D16'), name='bed')+
   scale_color_manual(values = c('B'='#662506','1'='#cc4c02','2'='#fe9929',
         '3'='#e31a1c','4'='#225ea8','5'='#41b6c4', 'D16'='#54278f'),
         breaks= c('B', '1','2','3','4','5', 'D16'), name='bed')+
   theme(legend.key = element_blank(),legend.position = c(0.75, 0.2),legend.background = 
            element_rect(fill = "#ffffffaa", colour = NA),legend.key.height=unit(.6,'line'))+ylab('standardized cpue')

a <- aggregate(mwt.cpue~year+Bed,data=yak, FUN=mean)
b <- aggregate(mwt.cpue~year+Bed,data=yak, FUN=sd)
names(b) <- c('year','Bed', 'sd')
c <- aggregate(mwt.cpue~year+Bed,data=yak, FUN=length)
names(c) <- c('year','Bed', 'n')
d <- merge(a,b, by=c('year','Bed'))
d <- merge(c,d, by=c('year','Bed'))
d$lci <- d$mwt.cpue-2*d$sd/sqrt(d$n)
d$uci <- d$mwt.cpue+2*d$sd/sqrt(d$n)
r2 <- ggplot(d, aes(year,mwt.cpue, fill=Bed))+geom_line(aes(color=Bed))+
   geom_ribbon(aes(ymin=lci, ymax=uci))+
   scale_fill_manual(values = c('B'='#66250610','1'='#cc4c0210','2'='#fe992910',
         '3'='#e31a1c10','4'='#225ea810','5'='#41b6c410', 'D16'='#54278f10'),
         breaks= c('B', '1','2','3','4','5', 'D16'), name='bed')+
   scale_color_manual(values = c('B'='#662506','1'='#cc4c02','2'='#fe9929',
         '3'='#e31a1c','4'='#225ea8','5'='#41b6c4', 'D16'='#54278f'),
         breaks= c('B', '1','2','3','4','5', 'D16'), name='bed')+
      guides( fill=FALSE, color=FALSE)+ theme(legend.key = element_blank())+ylab('cpue')
grid.arrange(r1,r2,ncol=2)

@

<<yaksh, fig.pos="H", fig.cap="Shell heights by bed and year for Area D. The left pane shows the density of shell heights, the right pane is a stacked bar histogram of sample sizes by shell height.",echo=FALSE, warning=FALSE ,fig.height=8.5, cache=TRUE,dev='png', dpi=300>>=
#Shell heights
yak.sh <- merge(yak,sh,by=c('Fishery', 'District','Haul_ID','ADFG'))

#SH by year
s1 <- ggplot(yak.sh, aes(Shell_Height, fill=Year,color=Year))+geom_density()+facet_grid(Bed~.)+
   scale_fill_manual(values=values,  
                     breaks=breaks, name='Year')+
   scale_color_manual(values=values,  
                      breaks=breaks, name='Year')+
   guides(colour = guide_legend(override.aes = list(alpha = 1)))+ 
   theme(legend.key = element_blank(),legend.position = c(0.15, 0.075),legend.background = 
            element_rect(fill = "#ffffffaa", colour = NA),legend.key.height=unit(.6,'line'))

s2 <- ggplot(yak.sh, aes(Shell_Height, fill=Year,color=Year))+geom_histogram()+facet_grid(Bed~.)+
   scale_fill_manual(values=values,   breaks=breaks, name='Year')+
   scale_color_manual(values=values,  breaks=breaks, name='Year')+
   guides( fill=FALSE, color=FALSE)+ theme(legend.key = element_blank())
grid.arrange(s1,s2,ncol=2)
@

<<yaksh14, fig.pos="H", fig.cap="Retained and discarded shell heights by bed for Area D in 2014. The left pane shows the density of shell heights, the right pane is a stacked bar histogram of sample sizes by shell height.",echo=FALSE, warning=FALSE ,fig.height=8.5, cache=TRUE, dev='png', dpi=300>>=
#SH by bed
s1 <- ggplot(subset(yak.sh, year==2014), aes(Shell_Height, fill=Rtnd_Disc,color=Rtnd_Disc))+geom_density(alpha=.2)+facet_grid(Bed~.)+
   scale_color_manual( values=c('D'='#e41a1c','R'='#377eb8'), labels=c('discard', 'retain'),name='')+
   scale_fill_manual( values=c('D'='#e41a1c','R'='#377eb8'), labels=c('discard', 'retain'),name='')+ 
   theme(legend.key = element_blank(),legend.position = c(0.2, 0.2),legend.background = 
   element_rect(fill = "#ffffffaa", colour = NA),legend.key.height=unit(.6,'line'))
s2 <- ggplot(subset(yak.sh, year==2014), aes(Shell_Height, fill=Rtnd_Disc,color=Rtnd_Disc))+geom_histogram(alpha=.2)+facet_grid(Bed~.)+
   scale_color_manual( values=c('D'='#e41a1c','R'='#377eb8'), labels=c('discard', 'retain'),name='')+
   scale_fill_manual( values=c('D'='#e41a1c','R'='#377eb8'), labels=c('discard', 'retain'),name='')+
   guides( fill=FALSE, color=FALSE)+ theme(legend.key = element_blank())
grid.arrange(s1,s2,ncol=2)

@

<<yaksh3, fig.pos="H", fig.cap="Retained and discarded shell heights by year for Area D in 2014. The left pane shows the density of shell heights, the right pane is a stacked bar histogram of sample sizes by shell height.",echo=FALSE, warning=FALSE ,fig.height=8.5, cache=TRUE,dev='png', dpi=300>>=

#SH by year
s1 <- ggplot(yak.sh, aes(Shell_Height, fill=Rtnd_Disc,color=Rtnd_Disc))+geom_density(alpha=.2)+facet_grid(Year~.)+
   scale_color_manual( values=c('D'='#e41a1c','R'='#377eb8'), labels=c('discard', 'retain'),name='')+
   scale_fill_manual( values=c('D'='#e41a1c','R'='#377eb8'), labels=c('discard', 'retain'),name='')+ 
   theme(legend.key = element_blank(),legend.position = c(0.2, 0.25),legend.background = 
   element_rect(fill = "#ffffffaa", colour = NA),legend.key.height=unit(.6,'line'))

s2 <- ggplot(yak.sh, aes(Shell_Height, fill=Rtnd_Disc,color=Rtnd_Disc))+geom_histogram(alpha=.2)+facet_grid(Year~.)+
   scale_color_manual( values=c('D'='#e41a1c','R'='#377eb8'), labels=c('discard', 'retain'),name='')+
   scale_fill_manual( values=c('D'='#e41a1c','R'='#377eb8'), labels=c('discard', 'retain'),name='')+
   guides( fill=FALSE, color=FALSE)+ theme(legend.key = element_blank())
grid.arrange(s1,s2,ncol=2)
@

<<yakage, fig.pos="H", fig.cap="Shell ages (annuli) by bed and year for Area D.",echo=FALSE, warning=FALSE ,fig.height=8, cache=TRUE,dev='png', dpi=300>>=
#Ages
yak.age <- merge(yak, ages,by=c('Fishery', 'District','Haul_ID','ADFG', 'set_date', 'year', 'date', 'Year'))
#age by year
a1 <- ggplot(yak.age, aes(annuli, fill=Year, color=Year))+geom_density()+facet_grid(Bed~.)+
   scale_fill_manual(values=values, breaks=breaks, name='Year')+
   scale_color_manual(values=values,  breaks=breaks, name='Year')+
   guides(colour = guide_legend(override.aes = list(alpha = 1)))+ 
   theme(legend.key = element_blank(),legend.position = c(0.75, 0.23),legend.background = 
            element_rect(fill = "#ffffffaa", colour = NA),legend.key.height=unit(.6,'line'))
a2 <- ggplot(yak.age, aes(annuli, fill=Year, color=Year))+geom_histogram()+facet_grid(Bed~.)+
   scale_fill_manual(values=values, breaks=breaks, name='Year')+
   scale_color_manual(values=values,  breaks=breaks, name='Year')+
   guides(colour = guide_legend(override.aes = list(alpha = 1)))+
   guides( fill=FALSE, color=FALSE)+ theme(legend.key = element_blank())
grid.arrange(a1,a2,ncol=2)
@

<<yakage3, fig.pos="H", fig.cap="Shell ages (annuli) by year for Area D, all beds combined. The left pane shows the density of shell heights, the right pane is a stacked bar histogram of sample sizes by shell height.",echo=FALSE, warning=FALSE ,fig.height=8.5, cache=TRUE,dev='png', dpi=300>>=

#SH by year
s1 <- ggplot(yak.age, aes(annuli))+geom_density(alpha=.2, fill='4')+facet_grid(Year~.)+
   theme(legend.key = element_blank(),legend.position = c(0.2, 0.25),legend.background = 
   element_rect(fill = "#ffffffaa", colour = NA),legend.key.height=unit(.6,'line'))

s2 <- ggplot(yak.age, aes(annuli))+geom_histogram(alpha=.2, color='black', fill=4)+facet_grid(Year~.)+
      guides( fill=FALSE, color=FALSE)+ theme(legend.key = element_blank())
grid.arrange(s1,s2,ncol=2)
@

<<yakagesh, fig.pos="H", fig.cap="Comparison between shells measured for height and shell height of aged scallops by bed and year for Area D. The left pane shows the density of all shell heights collected (blue) and the density of shell heights from ages shells (gray). The right pane shows the densities of shell heights from retained shells, discarded shell, and aged shells.",echo=FALSE, warning=FALSE ,fig.height=8.5, cache=TRUE, dev='png', dpi=300>>=
#difference between shell height samples and shell height ages
as1 <- ggplot(yak.age, aes(Shell_Height))+geom_density(alpha=.2,fill='black')+facet_grid(Year~.)+
   geom_density(data=yak.sh, aes(Shell_Height), alpha=.2,fill=4)

as2 <- ggplot(yak.age, aes(Shell_Height))+geom_density(alpha=.2,fill='black')+facet_grid(Year~.)+
   geom_density(data=yak.sh, aes(Shell_Height, fill=Rtnd_Disc), alpha=.2)+guides(colour = guide_legend(override.aes = list(alpha = 1)))+ 
   theme(legend.key = element_blank(),legend.position = c(0.15, 0.23),legend.background = 
            element_rect(fill = "#ffffffaa", colour = NA),legend.key.height=unit(.6,'line'))+
   scale_fill_manual( values=c('D'='#e41a1c','R'='#377eb8'), labels=c('discard', 'retain'),name='')
grid.arrange(as1,as2,ncol=2)

@

<<yakagex,echo=FALSE,message=FALSE,warning=FALSE,dev='png', dpi=300, fig.height=8>>=
#Extras
#yakmap+geom_point(data=subset(yak.age, year<2012),aes(Set_Lon,Set_Lat,color=annuli,width=1.2),alpha=.2) +
   #guides(colour = guide_legend(override.aes = list(alpha = 1)))+facet_grid(Year~.)+scale_colour_gradientn(colours=rainbow(5))
#yakmap+geom_point(data=subset(yak.age, year>2011),aes(Set_Lon,Set_Lat,color=annuli,width=1.2),alpha=.2) +
   #guides(colour = guide_legend(override.aes = list(alpha = 1)))+facet_grid(Year~.)+scale_colour_gradientn(colours=rainbow(5))

#ggplot(yak.age, aes(annuli))+geom_density(alpha=.2,fill=4)+facet_grid(Year~.)
#ggplot(yak.age, aes(annuli))+geom_histogram(alpha=.2,color='black', fill=4)+facet_grid(Year~.)   
#ggplot(yak.age, aes(annuli, Meat_Weight, fill=Bed))+geom_point(alpha=.2,color='black')+stat_smooth(method='gam',formula=y~s(x,k=3))+coord_cartesian(ylim=c(0,155),xlim=c(0,20))

#ggplot(yak.age, aes(annuli, Meat_Weight, group=Year,color=Year,fill=Year))+geom_point(alpha=.2,color='black')+stat_smooth()+coord_cartesian(ylim=c(0,155),xlim=c(0,20))


#ggplot(yak.age, aes(Depth,annuli, group=Year,color=Year,fill=Year))+geom_point(alpha=.2,color='black')+stat_smooth()
#ggplot(yak.sh, aes(Depth,Shell_Height, group=Year,color=Year,fill=Year))+geom_point(alpha=.2,color='black')+stat_smooth(method='lm')


#ggplot(yak.age, aes(Depth,annuli, group=Year,color=Year,fill=Year))+geom_point(alpha=.2,color='black')+stat_smooth(method='gam',formula=y~s(x,k=4))
#ggplot(yak.sh, aes(Meat_Weight,Shell_Height, group=Year,color=Year,fill=Year))+geom_point(alpha=.2,color='black')+stat_smooth(method='lm')
@