\documentclass{article}
\usepackage{color}
\usepackage[hidelinks]{hyperref}
\usepackage{float}
\usepackage[left=1.00in, right=1.00in, top=1.00in, bottom=1.00in]{geometry}
\usepackage[]{authblk}
\pretolerance=99999 
\author{Prepared by:\\Ben Williams\\
   \href{mailto:ben.williams@alaska.gov}{ben.williams@alaska.gov}}
\affil{Alaska Department of Fish \& Game\\
   1255 W 8th Street\\
   Juneau, AK 99811-5526}
\title{Scallop Observer Data Summary\\
   \textbf{\textit{DRAFT}}}

\begin{document}
   \maketitle
   \tableofcontents
\listoftables
\listoffigures

<<load,echo=FALSE,message=FALSE,warning=FALSE>>=
#load inputs
library(lubridate)
library(extrafont);library(ggplot2)
#font_import() only do this one time - it takes a while
loadfonts(device="win")
windowsFonts(Times=windowsFont("TT Times New Roman"))
theme_set(theme_bw(base_size=12,base_family='Times New Roman')+theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank()))
library(mgcv)
library(maps)
library(mapdata)
library(mapproj)
library(gridExtra)
library(gtools)
library(RColorBrewer)
library(plyr)
library(reshape2)

#import data To update with a new year simply add a new file and bind it with the others
scallops09 <- read.csv("C:/Users/bcwilliams/Documents/Fisheries/scallops/Data/2009-scallopCatchByHaul.csv")
scallops10 <- read.csv("C:/Users/bcwilliams/Documents/Fisheries/scallops/Data/2010-scallopCatchByHaul.csv")
scallops11 <- read.csv("C:/Users/bcwilliams/Documents/Fisheries/scallops/Data/2011-scallopCatchByHaul.csv")
scallops12 <- read.csv("C:/Users/bcwilliams/Documents/Fisheries/scallops/Data/2012-scallopCatchByHaul.csv")
scallops13 <- read.csv("C:/Users/bcwilliams/Documents/Fisheries/scallops/Data/2013-scallopCatchByHaul.csv")
scallops14 <- read.csv("C:/Users/bcwilliams/Documents/Fisheries/scallops/Data/2014-scallopCatchByHaul.csv")
scallops <- rbind(scallops09,scallops10, scallops11, scallops12,scallops13, scallops14)

sh09 <- read.csv("C:/Users/bcwilliams/Documents/Fisheries/scallops/Data/2009-scallopShellHeights.csv")
sh10 <-  read.csv("C:/Users/bcwilliams/Documents/Fisheries/scallops/Data/2010-scallopShellHeights.csv")
sh11 <- read.csv("C:/Users/bcwilliams/Documents/Fisheries/scallops/Data/2011-scallopShellHeights.csv")
sh12 <- read.csv("C:/Users/bcwilliams/Documents/Fisheries/scallops/Data/2012-scallopShellHeights.csv")
sh13 <- read.csv("C:/Users/bcwilliams/Documents/Fisheries/scallops/Data/2013-scallopShellHeights.csv")
sh14 <- read.csv("C:/Users/bcwilliams/Documents/Fisheries/scallops/Data/2014-scallopShellHeights.csv")
sh <- rbind(sh09,sh10,sh11,sh12,sh13,sh14)

cr09 <- read.csv("C:/Users/bcwilliams/Documents/Fisheries/scallops/Data/2009-crabSizes.csv")
cr10 <-  read.csv("C:/Users/bcwilliams/Documents/Fisheries/scallops/Data/2010-crabSizes.csv")
cr11 <- read.csv("C:/Users/bcwilliams/Documents/Fisheries/scallops/Data/2011-crabSizes.csv")
cr12 <- read.csv("C:/Users/bcwilliams/Documents/Fisheries/scallops/Data/2012-crabSizes.csv")
cr13 <- read.csv("C:/Users/bcwilliams/Documents/Fisheries/scallops/Data/2013-crabSizes.csv")
cr14 <- read.csv("C:/Users/bcwilliams/Documents/Fisheries/scallops/Data/2014-crabSizes.csv")
crab <- rbind(cr09,cr10,cr11,cr12,cr13,cr14)

by09 <- read.csv("C:/Users/bcwilliams/Documents/Fisheries/scallops/Data/2009-scallopBycatchByDay.csv")
by10 <-  read.csv("C:/Users/bcwilliams/Documents/Fisheries/scallops/Data/2010-scallopBycatchByDay.csv")
by11 <- read.csv("C:/Users/bcwilliams/Documents/Fisheries/scallops/Data/2011-scallopBycatchByDay.csv")
by12 <- read.csv("C:/Users/bcwilliams/Documents/Fisheries/scallops/Data/2012-scallopBycatchByDay.csv")
by13 <- read.csv("C:/Users/bcwilliams/Documents/Fisheries/scallops/Data/2013-scallopBycatchByDay.csv")
by14 <- read.csv("C:/Users/bcwilliams/Documents/Fisheries/scallops/Data/2014-scallopBycatchByDay.csv")
by <- rbind(by09,by10,by11,by12,by13,by14)

ages <- read.csv("C:/Users/bcwilliams/Documents/Fisheries/scallops/Data/scallop_ages_bcw.csv")
ages <- ages[,2:47]
ages14 <- read.csv("C:/Users/bcwilliams/Documents/Fisheries/scallops/Data/2014ScallopShellAgeData.csv")


#adjust names to match other files
names(ages14) <- c('id', 'trip_id', 'haul_id', 'aged_by','fishery', 'fishery_season','district','vessel','trip_or_packet','date','small_or_retained','haul','shell','annuli','letter_code','number_code','shell_height' ,'a1','a2','a3','a4','a5','a6','a7','a8','a9','a10' ,'a11', 'a12','a13','a14','a15','a16','a17','a18','a19','a20','a21','a22','a23','a24','a25','a26','a27')

ages<- smartbind(ages,ages14)

names(ages) <- c('id', 'Trip_ID', 'Haul_ID', 'aged_by','date_aged','Fishery', 'season','District','ADFG','packetnum','stat_area','Set_Date','Rtnd_Disc','haul','shell_num','annuli','code_let','code_num','Shell_Height','a1','a2','a3','a4','a5','a6','a7','a8','a9','a10' ,'a11', 'a12','a13','a14','a15','a16','a17','a18','a19','a20','a21','a22','a23','a24','a25','a26','a27')
#adjust dates
scallops$set_date <- as.Date(scallops$Set_Date, "%m-%d-%Y")
scallops$year <- as.numeric(format(scallops$set_date, "%Y"))
scallops$date <- yday(scallops$set_date)
scallops$year <- ifelse(scallops$date<100, scallops$year-1, scallops$year)
scallops$Year <- factor(scallops$year)
scallops$vessel <- factor(scallops$ADFG)

ages$set_date <- as.Date(ages$Set_Date, "%m/%d/%Y")
ages$year <- as.numeric(format(ages$set_date, "%Y"))
ages$date <- yday(ages$set_date)
ages$year <- ifelse(ages$date<100, ages$year-1, ages$year)
ages$Year <- factor(ages$year)

by$set_date <- as.Date(by$Set_Date, "%m-%d-%Y")
by$year <- as.numeric(format(by$set_date, "%Y"))
by$date <- yday(by$set_date)
by$year <- ifelse(by$date<100, by$year-1, by$year)
by$Year <- factor(by$year)
by$vessel <- factor(by$ADFG)

#plotting smotting
#year 2009-2014 colors and breaks
values <- c('2014'='#542788bb','2013'='#998ec340','2012'='#d8daeb40',
         '2011'='#fee0b640','2010'='#f1a34040','2009'='#b3580640') 
breaks <- c('2014', '2013','2012','2011','2010','2009')
@

<<akmap, fig.pos="H", fig.cap="Map of all scallop dredge hauls. Top pane shows fishing locations from the 2009/10-2014/15 fishing season. Bottom pane shows fishing locations from the 2014/15 fishing season.",echo=FALSE, warning=FALSE ,fig.height=7, cache=TRUE,dev='png', dpi=300>>=
# Map
ak <- map_data('worldHires', c('USA:Alaska','Canada'))
#akmap <- ggplot()+geom_polygon(data=ak,aes(long,lat,group=group),fill=8,color='black') +
#   theme(panel.background=element_rect(fill='white')) + 
#   xlab(expression(paste(Longitude^o,~'W'))) +
#   ylab(expression(paste(Latitude^o,~'W'))) + 
#   coord_map(xlim=c(min(scallops$Set_Lon,na.rm=T)-.2,max(scallops$Set_Lon,na.rm=T)+.2),
#             ylim=c(min(scallops$Set_Lat,na.rm=T)-.2,max(scallops$Set_Lat,na.rm=T)+.2))

#akmap1
#ak1 <- akmap + geom_point(data=scallops,aes(Set_Lon,Set_Lat,color=District),alpha=.35)+
#   scale_colour_manual(values=c('D16'='#662506','YAK'='#cc4c02','EKI'='#fe9929',
#                                'WKI'='#081d58','KNE'='#225ea8','KSH'='#41b6c4','KSW'
#                                ='#54278f','KSEM'='#807dba','UB'='#045a8d', 'Q'="#3690c0"
#                                ,'O'="#e31a1c", 'C'='#31a354'),  
#                       breaks=c('D16', 'YAK','EKI','WKI','KNE','KSH','KSW','KSEM','UB',
#                                'Q','O','C'), name='District')+
#   guides(colour = guide_legend(override.aes = list(alpha = 1, size=3
#   )))+ theme(legend.key = element_blank())+
#   theme(plot.margin=unit(c(0,0,0,0),"mm"))

#akmap2
#ak2 <- akmap + geom_point(data=subset(scallops, year==2014),aes(Set_Lon,Set_Lat,color=District),alpha=.35)+
#   scale_colour_manual(values=c('D16'='#662506','YAK'='#cc4c02','EKI'='#fe9929',
#                                'WKI'='#081d58','KNE'='#225ea8','KSH'='#41b6c4','KSW'
#                                ='#54278f','KSEM'='#807dba','UB'='#045a8d', 'Q'="#3690c0"
#                                ,'O'="#e31a1c"),  
#                       breaks=c('D16', 'YAK','EKI','WKI','KNE','KSH','KSW','KSEM','UB',
#                                'Q','O'), name='District')+
#   guides(colour = guide_legend(override.aes = list(alpha = 1, size=3
#   )))+ theme(legend.key = element_blank())+
#   theme(plot.margin=unit(c(0,0,0,0),"mm"))
#grid.arrange(ak1,ak2,ncol=1)
@


<<cpue, fig.pos="H", fig.cap="Log transformed cpue (weight/area swept) by round weight and shell weight.",echo=FALSE, warning=FALSE ,fig.height=4, cache=TRUE,dev='png', dpi=300, message=FALSE>>=

#remove data where dredge hours & area swept are zero
scallops <- subset(scallops,Area_Swept.nm2.>0)

#calculate round weight cpue by time and by area 
scallops$rw.cpue.t <- scallops$Round_Weight/scallops$Dredge_Hrs
scallops$rw.cpue.a <- scallops$Round_Weight/scallops$Area_Swept.nm2.

#calculate meat weight cpue by time and by area
scallops$mw.cpue.t <- scallops$Meat_Weight/scallops$Dredge_Hrs
scallops$mw.cpue.a <- scallops$Meat_Weight/scallops$Area_Swept.nm2.

#Subset scallop data to eliminate zeros in the cpue
scallop <- subset(scallops,rw.cpue.t>0)

#look for normality in cpue data
#h1 <- ggplot(scallop,aes(rw.cpue.t))+geom_histogram()
#h2 <- ggplot(scallop,aes(rw.cpue.a))+geom_histogram()+xlab('Round weight CPUE')
#h3 <- ggplot(scallop,aes(mw.cpue.t))+geom_histogram()
#h4 <- ggplot(scallop,aes(mw.cpue.a))+geom_histogram()+xlab('Meat weight CPUE')
#grid.arrange(h2,h4,ncol=2)

#adjust area cpue for log transformed data (Cambell et al 1996; Cambell 2004)
rwt.adjust <- mean(scallop$rw.cpue.t)*.10
rwa.adjust <- mean(scallop$rw.cpue.a)*.10
mwt.adjust <- mean(scallop$mw.cpue.t)*.10
mwa.adjust <- mean(scallop$mw.cpue.a)*.10

#log transform cpue data
scallop$rwt.cpue <- log(scallop$rw.cpue.t+rwt.adjust)
scallop$rwa.cpue <- log(scallop$rw.cpue.a+rwa.adjust)
scallop$mwt.cpue <- log(scallop$mw.cpue.t+mwt.adjust)
scallop$mwa.cpue <- log(scallop$mw.cpue.t+mwa.adjust)

#Subset data
eki <- subset(scallop,District=='EKI')
wki <- subset(scallop,District=='WKI')
yak <- subset(scallop,District=='YAK' |District=='D16' )
d16 <- subset(scallop,District=='D16')
kne <- subset(scallop,District=='KNE' )
ksh <- subset(scallop,District=='KSH' )
ksw <- subset(scallop,District=='KSW' )
m <- subset(scallop,District=='UB' )
o <- subset(scallop,District=='O')
q <- subset(scallop,District=='Q')
c <- subset(scallop,District=='C' )
@
\section{Bering Sea Area Q}

\subsubsection{Fishery performance}
The 2014/15 Area Q scallop fishery opened on July 1. 2014 with a GHL of 15,000 lb scallop meat. Two vessels particpated in the fishery (Figure~\ref{fig:qvessel}) harvesting 12,445 lb scallop meat with a cpue of 24 lb meat/dredge hour (Table~\ref{table:q1}). Catch per unit effort decreased substantially in the 2014/15 season.


\subsubsection{Size and age structure of catch}

The catch in 2014/15 was dominated by older larger individuals with few young shell scallops caught. Smaller, younger scallops were poorly represented in the catch.

\subsubsection{Scallop discards and crab/halibut bycatch}

An estimated 24,943 Tanner Crab, a substantial decrease from the previous year, 9,868 Opilio Crab, 19 Pacific Halibut and 223 King Crab were incidentically caught (Figure~\ref{fig:qcrab}). Estimated scallop discards were 7,961 lb (3.5\% of total round weight landed).

<<tablq, eval=FALSE, echo=FALSE>>=
a <- aggregate(Dredge_Hrs~year, data=q, FUN=sum)
b <- aggregate(Meat_Weight~year, data=q, FUN=sum)
c <- merge(a,b, by='year')
d <- aggregate(Haul_ID~year, data=q, FUN=length)
d <- merge(c,d, by='year')
d$cpue <- d$Meat_Weight/d$Dredge_Hrs
d
@

\begin{table}[H]
   \centering
   \caption{Area Q catch summary for the 2014/15 season.}
	
	\label{table:q1}
	\begin{tabular}{lcccccc}
		& 		&  Catch 	& Dredge  	& Number  	&  		 \\ 
		Year	& GHL 	&(lb meat)  & (hours) 	& hauls  	& cpue$^a$\\ 
		\hline	
		1993/94&		&	284,414&		5,764&		3,326&	49\\
		1994/95&		&	505,439	&	11,113&		6,508	&45\\
		1995/96&	closed&			&	&& \\
		1996/97&	600,000&		150,295&		2,313&		951&	65\\
		1997/98&	600,000&		97,002&		2,246&		1,280	&43\\
		1998/99	&	400,000&		96,795&		2,319&		1,178	&42\\
		1999/00	&	400,000&		164,481&		3,294&		1,514&	50\\
		2000/01	&	200,000&		205,520&		3,355&		1,564&	61\\
		2001/02	&	200,000&		140,365&		3,072&		1,401&	46\\
		2002/03	&	105,000&		90,562&		2,038&		1,010&	44\\
		2003/04	&	105,000&		42,590&		1,020&		517&	41\\
		2004/05	&	50,000&		10,050&		275&		145&	37\\
		2005/06	&	50,000&		23,241&		602	&	303&	39\\
		2006/07	&	50,000&		48,775&		1,138&		583&	43\\
		2007/08	&	50,000&		50,299&		1,083&		540&	46\\
		2008/09	&	50,000&		49,995&		960	&	642&	52\\
		2009/10	&	50,000&		48,885&		1,274&		726&	38\\
		2010/11	&	50,000&		50,099&		972	&	597&	52\\
		2011/12	&	50,000&		50,275&		984	&	626&	51\\
		2012/13	&	50,000&		50,045&		943	&	695&	53\\
		2013/14	&	50,000&		49,989&		1,086&		719&	46\\
		2014/15 & 50,000 & 12445 & 525 & 330 & 24\\
		
		
		\hline	
		\multicolumn{3}{l}{$^a$lb scallop meat/dredge hour}	\\
         \end{tabular} 
\end{table}
<<q, fig.pos="H", fig.cap="Maps of Area Q fishing locations by fishing year.",echo=FALSE, warning=FALSE ,fig.height=6, cache=TRUE,dev='png', dpi=300>>=
#######################
#Q
#######################
#excluded samples outside of the main bed
q <- subset(q,Set_Lon>-166)
#remove incomplete data
q <- q[complete.cases(q),]

#map of sample locations

qmap <- ggplot()+geom_polygon(data=ak,aes(long,lat,group=group, color=Bed),fill=8,color='black') +
   theme(panel.background=element_rect(fill='white')) + 
   xlab(expression(paste(Longitude^o,~'W'))) +
   ylab(expression(paste(Latitude^o,~'W'))) + 
   coord_map(xlim=c(-166.2,max(q$Set_Lon,na.rm=T)+.5),
             ylim=c(min(q$Set_Lat,na.rm=T)-.5,56.2))

qmap+geom_point(data=q, aes(Set_Lon,Set_Lat), alpha=.2)+facet_wrap(~ Year)+
   guides(colour = guide_legend(override.aes = list(alpha = 1)))+
   theme(legend.key = element_blank(),legend.position = c(0.1, 0.9),legend.background = 
            element_rect(fill = "#ffffffaa", colour = NA),legend.key.height=unit(.6,'line'))
@

<<qcpue, fig.pos="H", fig.cap="Density and number of tows by bed and year for Area Q cpue.",echo=FALSE, warning=FALSE ,fig.height=4, cache=TRUE, dev='png', dpi=300>>=
#RAW density and number of tows
m1 <- ggplot(q, aes(mwa.cpue,fill=Year,color=Year))+geom_density()+xlab('log(cpue)')+
   scale_fill_manual(values=values,breaks=breaks, name='Year')+
   scale_color_manual(values=values,breaks=breaks, name='Year')+
   guides(colour = guide_legend(override.aes = list(alpha = 1)))+ 
   theme(legend.key = element_blank(),legend.position = c(0.65, 0.45),legend.background = 
            element_rect(fill = "#ffffffaa", colour = NA),legend.key.height=unit(.6,'line'))

m2 <- ggplot(q, aes(mwa.cpue,fill=Year,color=Year))+geom_histogram()+xlab('log(cpue)')+
   scale_fill_manual(values=values,breaks=breaks, name='Year')+
   scale_color_manual(values=values,breaks=breaks, name='Year')+
   guides( fill=FALSE, color=FALSE)+ theme(legend.key = element_blank())
grid.arrange(m1,m2,ncol=2)
@

<<qfit,fig.pos="H", fig.cap="Density and number of tows by bed and year for Area Q standardized cpue.",echo=FALSE, warning=FALSE ,fig.height=4, cache=TRUE, dev='png', dpi=300>>=
#Model the CPUE

fit <- gam(mwt.cpue~s(Depth,k=4)+te(Set_Lon,Set_Lat)+Year+vessel-1, data=q, gamma=1.4)
#plot(kne$Bed,resid(fit))
q$fit <- fitted(fit)
f1 <- ggplot(q, aes(fit,fill=Year,color=Year))+geom_density()+
   scale_fill_manual(values=values,breaks=breaks, name='Year')+
   scale_color_manual(values=values,breaks=breaks, name='Year')+
   guides(colour = guide_legend(override.aes = list(alpha = 1)))+ 
   theme(legend.key = element_blank(),legend.position = c(0.15, 0.4),legend.background = 
            element_rect(fill = "#ffffffaa", colour = NA),legend.key.height=unit(.6,'line'))

f2 <- ggplot(q, aes(fit,fill=Year,color=Year))+geom_histogram()+
   scale_fill_manual(values=values,breaks=breaks, name='Year')+
   scale_color_manual(values=values,breaks=breaks, name='Year')+
   guides( fill=FALSE, color=FALSE)+ theme(legend.key = element_blank())
grid.arrange(f1,f2,ncol=2)
@


<<qvessel,fig.pos="H", fig.cap="Annual vessel effect from model fit, Area Q.",echo=FALSE, warning=FALSE ,fig.height=4, cache=TRUE,dev='png',dpi=300>>=
#Model the CPUE
#ggplot(q, aes(Year,fit, fill=Bed))+geom_boxplot()
#ggplot(q, aes(vessel,fit, fill=Bed))+geom_boxplot()
ggplot(q, aes(Year,fit, fill=vessel))+geom_boxplot(width=.35)
@

<<qfit2, fig.pos="H", fig.cap="Standardized and raw CPUE by year and bed for Area Q. Standardized cpue have bootstrap estimated 95\\% confidence levels, the raw cpue have normal approximate 95\\% confidence levels.",echo=FALSE, warning=FALSE ,fig.height=4, cache=TRUE, dev='png', dpi=300>>=
r1 <- ggplot(q, aes(year, fit))+stat_summary(fun.data=mean_cl_boot, geom='smooth')+coord_cartesian(ylim=c(3.3,4.1))+ylab('standardized cpue')


a <- aggregate(mwt.cpue~year,data=q, FUN=mean)
b <- aggregate(mwt.cpue~year,data=q, FUN=sd)
names(b) <- c('year', 'sd')
c <- aggregate(mwt.cpue~year,data=q, FUN=length)
names(c) <- c('year', 'n')
d <- merge(a,b, by=c('year'))
d <- merge(c,d, by=c('year'))
d$lci <- d$mwt.cpue-2*d$sd/sqrt(d$n)
d$uci <- d$mwt.cpue+2*d$sd/sqrt(d$n)
r2 <- ggplot(d, aes(year,mwt.cpue))+geom_line()+
   geom_ribbon(aes(ymin=lci, ymax=uci),alpha=.2)+coord_cartesian(ylim=c(3.3,4.1))+ylab('raw cpue')
grid.arrange(r1,r2,ncol=2)
@

<<qsh, fig.pos="H", fig.cap="Shell heights by bed and year for Area Q. The left pane shows the shell heights distribution for all of the hauls, the right pane shows the number of shells sampled at a given height.",echo=FALSE, warning=FALSE ,fig.height=4, cache=TRUE,dev='png', dpi=300>>=
#Shell heights
q.sh <- merge(q,sh,by=c('Fishery', 'District','Haul_ID','ADFG'))

#SH by year
s1 <- ggplot(q.sh, aes(Shell_Height, fill=Year,color=Year))+geom_density()+
   scale_fill_manual(values=values,breaks=breaks, name='Year')+
   scale_color_manual(values=values,breaks=breaks, name='Year')+
   guides(colour = guide_legend(override.aes = list(alpha = 1)))+ 
   theme(legend.key = element_blank(),legend.position = c(0.15, 0.5),legend.background = 
            element_rect(fill = "#ffffffaa", colour = NA),legend.key.height=unit(.6,'line'))

s2 <- ggplot(q.sh, aes(Shell_Height, fill=Year,color=Year))+geom_histogram()+
   scale_fill_manual(values=values,breaks=breaks, name='Year')+
   scale_color_manual(values=values,breaks=breaks, name='Year')+
   guides(colour = guide_legend(override.aes = list(alpha = 1)))+
   guides( fill=FALSE, color=FALSE)+ theme(legend.key = element_blank())
grid.arrange(s1,s2,ncol=2)
@

<<qsh14, fig.pos="H", fig.cap="Retained and discarded shell heights by bed for Area Q in 2014. The left pane shows the shell heights distribution for all of the hauls, the right pane shows the number of shells sampled at a given height.",echo=FALSE, warning=FALSE ,fig.height=4, cache=TRUE, dev='png', dpi=300>>=
#SH by bed
s1 <- ggplot(subset(q.sh, year==2014), aes(Shell_Height, fill=Rtnd_Disc,color=Rtnd_Disc))+geom_density(alpha=.2)+
   scale_color_manual( values=c('D'='#e41a1c','R'='#377eb8'), labels=c('discard', 'retain'),name='')+
   scale_fill_manual( values=c('D'='#e41a1c','R'='#377eb8'), labels=c('discard', 'retain'),name='')+ 
   theme(legend.key = element_blank(),legend.position = c(0.15, 0.4),legend.background = 
   element_rect(fill = "#ffffffaa", colour = NA),legend.key.height=unit(.6,'line'))
s2 <- ggplot(subset(q.sh, year==2014), aes(Shell_Height, fill=Rtnd_Disc,color=Rtnd_Disc))+geom_histogram(alpha=.2)+
   scale_color_manual( values=c('D'='#e41a1c','R'='#377eb8'), labels=c('discard', 'retain'),name='')+
   scale_fill_manual( values=c('D'='#e41a1c','R'='#377eb8'), labels=c('discard', 'retain'),name='')+
   guides( fill=FALSE, color=FALSE)+ theme(legend.key = element_blank())
grid.arrange(s1,s2,ncol=2)
@


<<qsh3, fig.pos="H", fig.cap="Shell heights by year for Area Q. The left pane shows the shell heights distribution for all of the hauls, the right pane shows the number of shells sampled at a given height.",echo=FALSE, warning=FALSE ,fig.height=8.5, cache=TRUE,dev='png', dpi=300>>=

#SH by year
s1 <- ggplot(q.sh, aes(Shell_Height, fill=Rtnd_Disc,color=Rtnd_Disc))+geom_density(alpha=.2)+facet_grid(Year~.)+
   scale_color_manual( values=c('D'='#e41a1c','R'='#377eb8'), labels=c('discard', 'retain'),name='')+
   scale_fill_manual( values=c('D'='#e41a1c','R'='#377eb8'), labels=c('discard', 'retain'),name='')+ 
   theme(legend.key = element_blank(),legend.position = c(0.2, 0.25),legend.background = 
   element_rect(fill = "#ffffffaa", colour = NA),legend.key.height=unit(.6,'line'))

s2 <- ggplot(q.sh, aes(Shell_Height, fill=Rtnd_Disc,color=Rtnd_Disc))+geom_histogram(alpha=.2)+facet_grid(Year~.)+
   scale_color_manual( values=c('D'='#e41a1c','R'='#377eb8'), labels=c('discard', 'retain'),name='')+
   scale_fill_manual( values=c('D'='#e41a1c','R'='#377eb8'), labels=c('discard', 'retain'),name='')+
   guides( fill=FALSE, color=FALSE)+ theme(legend.key = element_blank())
grid.arrange(s1,s2,ncol=2)
@



<<qage, fig.pos="H", fig.cap="Shell ages (annuli) by bed and year for Area Q. ",echo=FALSE, warning=FALSE ,fig.height=4, cache=TRUE, dev='png', dpi=300>>=   
#Ages

q.age <- merge(q, ages,by=c('Fishery', 'District','Haul_ID','ADFG', 'set_date', 'year', 'date', 'Year'))


#age by year
a1 <- ggplot(q.age, aes(annuli, fill=Year, color=Year))+geom_density()+
   scale_fill_manual(values=values, breaks=breaks, name='Year')+
   scale_color_manual(values=values,  breaks=breaks, name='Year')+
   guides(colour = guide_legend(override.aes = list(alpha = 1)))+guides(colour = guide_legend(override.aes = list(alpha = 1)))+
   guides( fill=FALSE, color=FALSE)+ theme(legend.key = element_blank())
a2 <- ggplot(q.age, aes(annuli, fill=Year, color=Year))+geom_histogram()+
   scale_fill_manual(values=values, breaks=breaks, name='Year')+
   scale_color_manual(values=values,  breaks=breaks, name='Year')+ 
   theme(legend.key = element_blank(),legend.position = c(0.75, 0.75),legend.background = 
            element_rect(fill = "#ffffffaa", colour = NA),legend.key.height=unit(.6,'line'))
   
grid.arrange(a1,a2,ncol=2)
@

<<qage2, fig.pos="H", fig.cap="Shell ages (annuli) by bed and year for Area Q.",echo=FALSE, warning=FALSE ,fig.height=8.5, cache=TRUE, dev='png', dpi=300>>=                               
 #Ages
                                           
                        
#age by year
a1 <- ggplot(q.age, aes(annuli,fill=Rtnd_Disc))+geom_density()+facet_grid(Year~., scale='free_y')+
   guides(colour = guide_legend(override.aes = list(alpha = 1)))+ 
   theme(legend.key = element_blank(),legend.position = c(0.75, 0.08),legend.background = 
            element_rect(fill = "#ffffffaa", colour = NA),legend.key.height=unit(.6,'line'))
a2 <- ggplot(q.age, aes(annuli,fill=Rtnd_Disc))+geom_histogram(color='white')+facet_grid(Year~.)+
      guides(colour = guide_legend(override.aes = list(alpha = 1)))+
   guides( fill=FALSE, color=FALSE)+ theme(legend.key = element_blank())
grid.arrange(a1,a2,ncol=2)
@   

<<qagesh, fig.pos="H", fig.cap="Comparison between shells measured for height and shell height of aged scallops by year for Area Q. The left pane shows the density of all shell heights collected (blue) and the density of shell heights from ages shells (gray). The right pane shows the densities of shell heights from retained shells, discarded shell, and aged shells.",echo=FALSE, warning=FALSE ,fig.height=8.5, cache=TRUE, dev='png', dpi=300>>=

#qmap+geom_point(data=subset(q.age, year<2012),aes(Set_Lon,Set_Lat,color=annuli,width=1.2),alpha=.2) +
##   guides(colour = guide_legend(override.aes = list(alpha = 1)))+facet_grid(Year~.)+
#   scale_colour_gradientn(colours =rainbow(5))

#qmap+geom_point(data=subset(q.age, year>2011),aes(Set_Lon,Set_Lat,color=annuli,width=1.2),alpha=.2) +
#   guides(colour = guide_legend(override.aes = list(alpha = 1)))+facet_grid(Year~.)+
#   scale_colour_gradientn(colours=rainbow(5))

#ggplot(q.age, aes(annuli))+geom_density(alpha=.2,fill=4)+facet_grid(Year~.)
#ggplot(q.age, aes(annuli))+geom_histogram(alpha=.2,color='black', fill=4)+facet_grid(Year~.)

#difference between shell height samples and shell height ages
as1 <- ggplot(q.age, aes(Shell_Height))+geom_density(alpha=.2,fill='black')+facet_grid(Year~.)+
   geom_density(data=q.sh, aes(Shell_Height), alpha=.2,fill=4)

as2 <- ggplot(q.age, aes(Shell_Height))+geom_density(alpha=.2,fill='black')+facet_grid(Year~.)+
   geom_density(data=q.sh, aes(Shell_Height, fill=Rtnd_Disc), alpha=.2)+guides(colour = guide_legend(override.aes = list(alpha = 1)))+ 
   theme(legend.key = element_blank(),legend.position = c(0.15, 0.23),legend.background = 
            element_rect(fill = "#ffffffaa", colour = NA),legend.key.height=unit(.6,'line'))+
   scale_fill_manual( values=c('D'='#e41a1c','R'='#377eb8'), labels=c('discard', 'retain'),name='')
grid.arrange(as1,as2,ncol=2)
@

<<qagex, echo=FALSE, warning=FALSE,eval=FALSE, dev='png', dpi=300>>=
ggplot(q.age, aes(Shell_Height))+geom_density(alpha=.2,fill='black')+facet_grid(Year~.)+
   geom_density(data=q.sh, aes(Shell_Height), alpha=.2,fill=4)

ggplot(q.age, aes(Shell_Height))+geom_density(alpha=.2,fill='black')+facet_grid(Year~Bed, scales='free_y')+
   geom_density(data=q.sh, aes(Shell_Height, fill=Rtnd_Disc), alpha=.2)


ggplot(q.age, aes(annuli, Meat_Weight))+geom_point(alpha=.2,color='black')+facet_grid(Year~.)+
   stat_smooth()+coord_cartesian(xlim=c(0,20))
ggplot(q.age, aes(annuli, Meat_Weight, group=Year,color=Year,fill=Year))+geom_point(alpha=.2,color='black')+
   stat_smooth()+coord_cartesian(xlim=c(0,20))


ggplot(q.age, aes(Depth,annuli, group=Year,color=Year,fill=Year))+geom_point(alpha=.2,color='black')+stat_smooth()
ggplot(q.age, aes(Depth,annuli))+geom_point(alpha=.2,color='black')+stat_smooth(method='lm')
ggplot(q.sh, aes(Depth,Shell_Height, group=Year,color=Year,fill=Year))+geom_point(alpha=.2,color='black')+stat_smooth(method='lm')
ggplot(q.sh, aes(Depth,Shell_Height))+geom_point(alpha=.2,color='black')+stat_smooth(method='lm')


ggplot(q.age, aes(Depth,annuli, group=Year))+geom_point(alpha=.2,color='black')+stat_smooth()
ggplot(q.sh, aes(Shell_Height, Meat_Weight,group=Year,color=Year,fill=Year))+geom_point(alpha=.2,color='black')+stat_smooth(method='lm')
@

<<qcrab, fig.pos="H", fig.cap="Estimated Tanner Crab and Pacific Halibut catch for Area Q.",echo=FALSE, warning=FALSE ,fig.height=4, cache=TRUE, dev='png', dpi=300, eval=TRUE>>=   
q.by <- merge(by, q, by=c('Fishery', 'District','ADFG', 'set_date', 'year', 'date', 'Year', 'vessel'))

a <- aggregate(Halibut_Count~year,data=subset(by, District=='Q'), FUN=sum)
a1 <- aggregate(Tanner_Count~year,data=subset(by, District=='Q'), FUN=sum)
a2 <- aggregate(Opilio_Count~year,data=subset(by, District=='Q'), FUN=sum)
a3 <- aggregate(King_Count~year,data=subset(by, District=='Q'), FUN=sum)
b <- aggregate(Sample_Hrs~year,data=subset(by, District=='Q'), FUN=sum)
c <- aggregate(Dredge_Hrs~year,data=q, FUN=sum)

d <- merge(a,b, by='year')
d <- merge(a1,d, by='year')
d <- merge(a2,d, by='year')
d <- merge(a3,d, by='year')
d <- merge(c,d, by='year')

d$hal <- d$Halibut_Count/d$Sample_Hrs*d$Dredge_Hrs
d$tan <- d$Tanner_Count/d$Sample_Hrs*d$Dredge_Hrs
d$opi <- d$Opilio_Count/d$Sample_Hrs*d$Dredge_Hrs
d$king <- d$King_Count/d$Sample_Hrs*d$Dredge_Hrs

d <- d[,c(1,7:11)]
d<- melt(d, id.vars=c( 'year'))
ggplot(d, aes(year, value, color=variable, group=variable))+geom_line()+geom_point(size=3)+
    scale_color_discrete(name="species",
                         breaks=c("tan", "hal", "opi", 'king'),
                         labels=c("Tanner", "Halibut", "Opilio", "King"))
@


<<qdisc, fig.pos="H", fig.cap="Scallop estimated discard weight for Area Q.",echo=FALSE, warning=FALSE ,fig.height=4, cache=TRUE, dev='png', dpi=300, eval=TRUE>>=   
q.by <- merge(by, q, by=c('Fishery', 'District','ADFG', 'set_date', 'year', 'date', 'Year', 'vessel'))

a <- aggregate(Sample_Hrs~year,data=subset(by, District=='Q'), FUN=sum)
a1 <- aggregate(Discard_Weight~year,data=subset(by, District=='Q'), FUN=sum)
a2 <- aggregate(Broken_Weight~year,data=subset(by, District=='Q'), FUN=sum)
a3 <- aggregate(Rem_Disc_Wt~year,data=subset(by, District=='Q'), FUN=sum)
b <- aggregate(Dredge_Hrs~year,data=q, FUN=sum)
c <- aggregate(Round_Weight~year,data=q, FUN=sum)

d <- merge(a,a1, by='year')
d <- merge(d,a2, by='year')
d <- merge(d,a3, by='year')
d <- merge(b,d, by='year')
d <- merge(c,d, by='year')
d$wt <- d[,5]+d[,6]+d[,7]
d$disc <- d$wt/d$Sample_Hrs*d$Dredge_Hrs
d$per <- d$disc/d$Round_Weight*100
ggplot(d, aes(year, disc))+geom_line()+geom_point(size=3)+ylim(0, max(d$disc))+ylab('Scallop discard weight (lbs)')
    
@


\end{document}